"""Machine-generated input-constraint validator for problem 'smallest-range-ii'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(A, K):
    if not isinstance(A, list):
        return False
    if not (1 <= len(A) <= 10**4):
        return False
    for x in A:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (0 <= x <= 10**4):
            return False
    if isinstance(K, bool) or not isinstance(K, int):
        return False
    if not (0 <= K <= 10**4):
        return False
    return True
