"""Machine-generated input-constraint validator for problem 'minimum-moves-to-move-a-box-to-their-target-location'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced grid dimensions, rectangular shape, allowed characters, and exact counts of S, B, T. Did not enforce semantic solvability or minimum pushes.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(grid):
    if not isinstance(grid, list):
        return False
    if len(grid) == 0:
        return False
    
    m = len(grid)
    if not (1 <= m <= 20):
        return False
        
    n = len(grid[0])
    if not (1 <= n <= 20):
        return False
        
    allowed_chars = set('#.SBT')
    
    s_count = 0
    b_count = 0
    t_count = 0
    
    for row in grid:
        if not isinstance(row, str):
            return False
        if len(row) != n:
            return False
        for char in row:
            if char not in allowed_chars:
                return False
            if char == 'S':
                s_count += 1
            elif char == 'B':
                b_count += 1
            elif char == 'T':
                t_count += 1
                
    if s_count != 1 or b_count != 1 or t_count != 1:
        return False
        
    return True
