"""Machine-generated input-constraint validator for problem 'valid-tic-tac-toe-state'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced structural constraints (3x3 grid, valid characters). Did not enforce semantic game validity (e.g., turn order, win conditions) as per Rule 2.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(board):
    if not isinstance(board, list):
        return False
    if len(board) != 3:
        return False
    for row in board:
        if not isinstance(row, str):
            return False
        if len(row) != 3:
            return False
        for char in row:
            if char not in (' ', 'X', 'O'):
                return False
    return True
