"""Machine-generated input-constraint validator for problem 'statistics-from-a-large-sample'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'unique mode' constraint as it is a semantic guarantee about the data distribution, not a simple checkable bound on the raw input values.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(count):
    if not isinstance(count, list):
        return False
    if len(count) != 256:
        return False
    for x in count:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if x < 0:
            return False
    total = sum(count)
    if not (1 <= total <= 10**9):
        return False
    return True
