"""Machine-generated input-constraint validator for problem 'valid-palindrome'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  The problem statement provides no explicit constraints on length or character set beyond the type declaration, so only the type is enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s):
    if not isinstance(s, str):
        return False
    return True
