"""Machine-generated input-constraint validator for problem 'verbal-arithmetic-puzzle'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'no leading zero' and 'distinct letter maps to distinct digit' as these are semantic constraints on the solution/assignment, not raw input bounds. Enforced all stated length, type, and character set constraints.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(words, result):
    # Check types
    if not isinstance(words, list):
        return False
    if not isinstance(result, str):
        return False
    
    # Check words length constraint: 2 <= len(words) <= 5
    if not (2 <= len(words) <= 5):
        return False
    
    # Check each word in words
    for w in words:
        if not isinstance(w, str):
            return False
        # Check length constraint: 1 <= len(w) <= 7
        if not (1 <= len(w) <= 7):
            return False
        # Check uppercase letters only
        if not w.isalpha() or not w.isupper():
            return False
    
    # Check result length constraint: 1 <= len(result) <= 7
    if not (1 <= len(result) <= 7):
        return False
    # Check result uppercase letters only
    if not result.isalpha() or not result.isupper():
        return False
    
    # Check at most 10 distinct letters overall
    all_chars = set()
    for w in words:
        all_chars.update(w)
    all_chars.update(result)
    
    if len(all_chars) > 10:
        return False
    
    return True
