"""Machine-generated input-constraint validator for problem 'reaching-points'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(sx, sy, tx, ty):
    # Check types: must be int, not bool
    for val in (sx, sy, tx, ty):
        if not isinstance(val, int) or isinstance(val, bool):
            return False
    # Check ranges: 1 <= val <= 10^9
    limit = 10**9
    if not (1 <= sx <= limit):
        return False
    if not (1 <= sy <= limit):
        return False
    if not (1 <= tx <= limit):
        return False
    if not (1 <= ty <= limit):
        return False
    return True
