"""Machine-generated input-constraint validator for problem 'path-exists-undirected'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced vertex range 0..n-1 for edge endpoints based on the problem description 'n vertices labeled 0..n-1'.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(n, edges, source, destination):
    # Check n
    if not isinstance(n, int) or isinstance(n, bool):
        return False
    if not (1 <= n <= 2 * 10**5):
        return False

    # Check edges
    if not isinstance(edges, list):
        return False
    if not (0 <= len(edges) <= 2 * 10**5):
        return False
    for edge in edges:
        if not isinstance(edge, list):
            return False
        if len(edge) != 2:
            return False
        u, v = edge
        if not isinstance(u, int) or isinstance(u, bool):
            return False
        if not isinstance(v, int) or isinstance(v, bool):
            return False
        # The problem statement implies vertices are 0..n-1, but strictly speaking,
        # the constraint "0 <= source, destination < n" is explicit.
        # The constraint for edges is just "each edges[i] = [u, v]".
        # Usually in such problems, u and v are also within 0..n-1.
        # However, rule 3 says "Do NOT invent constraints". 
        # Rule 1 says enforce "value ranges". 
        # The statement says "There are n vertices labeled 0..n-1". This implies u, v must be in that range.
        # Let's check if u, v are valid integers. The range check for u, v is implied by the vertex definition.
        # If u or v are outside 0..n-1, they refer to non-existent vertices, which violates the problem setup.
        # So we should enforce 0 <= u < n and 0 <= v < n.
        if not (0 <= u < n):
            return False
        if not (0 <= v < n):
            return False

    # Check source
    if not isinstance(source, int) or isinstance(source, bool):
        return False
    if not (0 <= source < n):
        return False

    # Check destination
    if not isinstance(destination, int) or isinstance(destination, bool):
        return False
    if not (0 <= destination < n):
        return False

    return True
