"""Machine-generated input-constraint validator for problem 'partition-to-k-equal-sum-subsets'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums, k):
    if not isinstance(nums, list):
        return False
    if not isinstance(k, int) or isinstance(k, bool):
        return False
    if not (1 <= k <= len(nums) <= 16):
        return False
    for x in nums:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (1 <= x < 10**4):
            return False
    return True
