"""Machine-generated input-constraint validator for problem 'majority-element'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'The input is generated such that a majority element will exist in the array' as it is a semantic guarantee about the content, not a checkable input bound.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums):
    if not isinstance(nums, list):
        return False
    n = len(nums)
    if not (1 <= n <= 5 * 10**4):
        return False
    for x in nums:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (-10**9 <= x <= 10**9):
            return False
    return True
