"""Machine-generated input-constraint validator for problem 'ransom-note'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(ransomNote, magazine):
    if not isinstance(ransomNote, str):
        return False
    if not isinstance(magazine, str):
        return False
    if not (1 <= len(ransomNote) <= 10**5):
        return False
    if not (1 <= len(magazine) <= 10**5):
        return False
    if not all('a' <= c <= 'z' for c in ransomNote):
        return False
    if not all('a' <= c <= 'z' for c in magazine):
        return False
    return True
