"""Machine-generated input-constraint validator for problem 'merge-sorted-arrays'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length bounds, value ranges, integer types (excluding bools), and the non-decreasing sort order constraint. No semantic guarantees about the output were enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(a, b):
    if not isinstance(a, list) or not isinstance(b, list):
        return False
    if not (0 <= len(a) <= 10**5) or not (0 <= len(b) <= 10**5):
        return False
    for x in a:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (-10**9 <= x <= 10**9):
            return False
    for x in b:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (-10**9 <= x <= 10**9):
            return False
    if a != sorted(a):
        return False
    if b != sorted(b):
        return False
    return True
