"""Machine-generated input-constraint validator for problem 'sort-list'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(head):
    if not isinstance(head, list):
        return False
    if not (0 <= len(head) <= 5 * 10**4):
        return False
    for x in head:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (-10**5 <= x <= 10**5):
            return False
    return True
