"""Machine-generated input-constraint validator for problem 'remove-k-digits'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: types, length bounds, k bounds, digit-only content, and no leading zeros rule.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(num, k):
    if not isinstance(num, str):
        return False
    if not isinstance(k, int) or isinstance(k, bool):
        return False
    if not (1 <= len(num) <= 10**5):
        return False
    if not (0 <= k <= len(num)):
        return False
    if not all(c.isdigit() for c in num):
        return False
    if len(num) > 1 and num[0] == '0':
        return False
    return True
