"""Machine-generated input-constraint validator for problem 'vowel-spellchecker'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced list types, length bounds for lists and strings, and alphabetic character constraint. No semantic guarantees to skip.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(wordlist, queries):
    if not isinstance(wordlist, list) or not isinstance(queries, list):
        return False
    if not (1 <= len(wordlist) <= 5000) or not (1 <= len(queries) <= 5000):
        return False
    for w in wordlist:
        if not isinstance(w, str):
            return False
        if not (1 <= len(w) <= 7):
            return False
        if not w.isalpha():
            return False
    for q in queries:
        if not isinstance(q, str):
            return False
        if not (1 <= len(q) <= 7):
            return False
        if not q.isalpha():
            return False
    return True
