"""Machine-generated input-constraint validator for problem 'palindrome-partitioning-iii'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s, k):
    if not isinstance(s, str):
        return False
    if not isinstance(k, int) or isinstance(k, bool):
        return False
    if not (1 <= k <= len(s) <= 100):
        return False
    if not all('a' <= c <= 'z' for c in s):
        return False
    return True
