"""Machine-generated input-constraint validator for problem 'populating-next-right-pointers-in-each-node-ii'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced list type, length range [0, 6000], and element value range [-100, 100] for non-None elements. Skipped structural validity of the tree representation (e.g., whether the array forms a valid binary tree) as it is not explicitly stated as a constraint on the raw input format, only implied by the problem context.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root):
    if not isinstance(root, list):
        return False
    if not (0 <= len(root) <= 6000):
        return False
    for x in root:
        if x is None:
            continue
        if isinstance(x, bool):
            return False
        if not isinstance(x, int):
            return False
        if not (-100 <= x <= 100):
            return False
    return True
