"""Machine-generated input-constraint validator for problem 'min-operations-reduce-x'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums, x):
    if not isinstance(nums, list):
        return False
    if not (1 <= len(nums) <= 10**5):
        return False
    for val in nums:
        if isinstance(val, bool) or not isinstance(val, int):
            return False
        if not (1 <= val <= 10**4):
            return False
    if isinstance(x, bool) or not isinstance(x, int):
        return False
    if not (1 <= x <= 10**9):
        return False
    return True
