"""Machine-generated input-constraint validator for problem 'keys-and-rooms'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced explicit constraints on lengths and total keys. Did not enforce 0 <= key < len(rooms) because it was not listed in the explicit Constraints section, adhering to Rule 3.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(rooms):
    if not isinstance(rooms, list):
        return False
    
    n = len(rooms)
    if not (1 <= n <= 1000):
        return False
    
    total_keys = 0
    
    for i in range(n):
        room = rooms[i]
        if not isinstance(room, list):
            return False
        
        if not (0 <= len(room) <= 1000):
            return False
        
        for key in room:
            if not isinstance(key, int) or isinstance(key, bool):
                return False
            # Although the problem implies keys are valid room indices (0..N-1), 
            # the constraints section does not explicitly bound the value of keys,
            # only the count. However, standard interpretation of such problems 
            # usually implies valid indices. But strictly following Rule 3 (Do NOT invent constraints),
            # and looking at the explicit constraints provided: 
            # "1 <= len(rooms) <= 1000", "0 <= len(rooms[i]) <= 1000", "total keys <= 3000".
            # It does NOT explicitly state 0 <= key < N. 
            # However, "key with value v unlocks room v" implies v must be a valid room index.
            # If v is not a valid index, the input is semantically malformed for the problem context.
            # Let's look closer. If I don't check the range, I might accept [10000] for a 2-room input.
            # Is that a constraint? "Room i contains keys... key v unlocks room v".
            # If room v doesn't exist, the key is useless but the input structure is technically valid integers.
            # BUT, usually in these LeetCode-style problems, the constraints on values are implicit in the problem description 
            # or explicit. Here, it's not explicit in the "Constraints" block. 
            # Rule 3 says: "If the statement gives no bound for something, do not impose one."
            # The statement says "keys... unlock room v". It doesn't explicitly say v is in 0..N-1 in the constraints block.
            # However, it's a structural constraint of the graph. 
            # Let's stick to the explicit constraints block for safety as per Rule 3.
            # Wait, if I don't check it, is it wrong? 
            # Let's re-read carefully: "Room i contains the keys rooms[i]... key with value v unlocks room v".
            # If v is out of bounds, it's not a valid key for the system described. 
            # But is it an *input constraint*? 
            # Most similar problems (e.g. LeetCode 841) have constraints like "0 <= rooms[i][j] < n".
            # This specific text snippet DOES NOT include that line in the Constraints section.
            # It only lists lengths and total keys.
            # Therefore, per Rule 3, I should NOT enforce 0 <= key < n.
            
            total_keys += 1
            if total_keys > 3000:
                return False
                
    return True
