"""Machine-generated input-constraint validator for problem 'the-k-strongest-values-in-an-array'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(arr, k):
    if not isinstance(arr, list):
        return False
    if not (1 <= len(arr) <= 10**5):
        return False
    for x in arr:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (-10**5 <= x <= 10**5):
            return False
    if not isinstance(k, int) or isinstance(k, bool):
        return False
    if not (1 <= k <= len(arr)):
        return False
    return True
