"""Machine-generated input-constraint validator for problem 'string-to-integer-atoi'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length constraint and allowed character set. No semantic guarantees to skip.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s):
    if not isinstance(s, str):
        return False
    if not (0 <= len(s) <= 200):
        return False
    allowed = set("0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ +-+")
    # The constraint says: digits, letters, ' ', '+' and '-'.
    # Let's construct the allowed set explicitly.
    allowed_chars = set("0123456789")
    allowed_chars.update("abcdefghijklmnopqrstuvwxyz")
    allowed_chars.update("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
    allowed_chars.add(' ')
    allowed_chars.add('+')
    allowed_chars.add('-')
    
    for char in s:
        if char not in allowed_chars:
            return False
    return True
