"""Machine-generated input-constraint validator for problem 'isomorphic-strings'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length constraints and type checks. The constraint 's and t consist of any ASCII character' is trivially true for Python strings in this context (or uncheckable without defining 'ASCII' strictly vs unicode), so no specific character set validation is added as Python strings can hold any unicode.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s, t):
    if not isinstance(s, str) or not isinstance(t, str):
        return False
    if not (1 <= len(s) <= 5 * 10**4):
        return False
    if len(t) != len(s):
        return False
    return True
