"""Machine-generated input-constraint validator for problem 'maximum-of-absolute-value-expression'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(arr1, arr2):
    if not isinstance(arr1, list) or not isinstance(arr2, list):
        return False
    if len(arr1) != len(arr2):
        return False
    n = len(arr1)
    if not (2 <= n <= 4 * 10**4):
        return False
    for x in arr1:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (-10**6 <= x <= 10**6):
            return False
    for x in arr2:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (-10**6 <= x <= 10**6):
            return False
    return True
