"""Machine-generated input-constraint validator for problem 'most-frequent-subtree-sum'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced node count constraint and integer value types. Skipped semantic guarantees about subtree sums.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root):
    if root is None:
        return False
    
    # Check if root is a TreeNode-like object (has value, left, right attributes)
    # We assume standard LeetCode TreeNode structure.
    # Since we cannot import TreeNode, we check for attributes.
    if not hasattr(root, 'val') and not hasattr(root, 'value'):
        return False
    
    # Determine which attribute holds the value
    val_attr = 'val' if hasattr(root, 'val') else 'value'
    
    # Collect all nodes via BFS to check structure and count nodes
    nodes = []
    queue = [root]
    
    while queue:
        current = queue.pop(0)
        if current is None:
            continue
        
        nodes.append(current)
        
        # Check if current node has left/right attributes
        if not hasattr(current, 'left') or not hasattr(current, 'right'):
            return False
            
        queue.append(current.left)
        queue.append(current.right)
        
    # Constraint: 1 <= number of nodes <= 10^4
    if not (1 <= len(nodes) <= 10**4):
        return False
        
    # Check values of all nodes are integers (not bools)
    for node in nodes:
        val = getattr(node, val_attr)
        if isinstance(val, bool) or not isinstance(val, int):
            return False
            
    return True
