"""Machine-generated input-constraint validator for problem 'tiling-a-rectangle-with-the-fewest-squares'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(n, m):
    if not isinstance(n, int) or isinstance(n, bool):
        return False
    if not isinstance(m, int) or isinstance(m, bool):
        return False
    if not (1 <= n <= 13):
        return False
    if not (1 <= m <= 13):
        return False
    return True
