"""Machine-generated input-constraint validator for problem 'skyline-key-points'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: list length, inner list structure, integer types (excluding bools), and value ranges for left, right, and height.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(buildings):
    if not isinstance(buildings, list):
        return False
    if not (0 <= len(buildings) <= 10**4):
        return False
    for b in buildings:
        if not isinstance(b, list):
            return False
        if len(b) != 3:
            return False
        left, right, height = b
        if not (isinstance(left, int) and not isinstance(left, bool)):
            return False
        if not (isinstance(right, int) and not isinstance(right, bool)):
            return False
        if not (isinstance(height, int) and not isinstance(height, bool)):
            return False
        if not (0 <= left < right <= 10**9):
            return False
        if not (1 <= height <= 10**9):
            return False
    return True
