"""Machine-generated input-constraint validator for problem 'self-crossing'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(x):
    if not isinstance(x, list):
        return False
    if not (1 <= len(x) <= 10**5):
        return False
    for val in x:
        if isinstance(val, bool) or not isinstance(val, int):
            return False
        if not (1 <= val <= 10**5):
            return False
    return True
