"""Machine-generated input-constraint validator for problem 'undirected-cycle'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced n range, edge structure, vertex ranges, no self-loops, and no duplicate edges. Did not enforce 'simple graph' semantic beyond duplicates/self-loops as those are the only checkable constraints provided.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(n, edges):
    # Check n type and range
    if not isinstance(n, int) or isinstance(n, bool):
        return False
    if not (1 <= n <= 2000):
        return False

    # Check edges type
    if not isinstance(edges, list):
        return False

    # Check each edge
    for edge in edges:
        if not isinstance(edge, list):
            return False
        if len(edge) != 2:
            return False
        u, v = edge
        # Check u and v are integers (not bools)
        if not isinstance(u, int) or isinstance(u, bool):
            return False
        if not isinstance(v, int) or isinstance(v, bool):
            return False
        # Check u != v (no self-loops)
        if u == v:
            return False
        # Check vertices are within valid range 0..n-1
        if not (0 <= u < n):
            return False
        if not (0 <= v < n):
            return False

    # Check for duplicate edges (undirected, so [u,v] is same as [v,u])
    seen = set()
    for edge in edges:
        u, v = edge
        # Normalize edge to sorted tuple to handle undirected nature
        normalized_edge = tuple(sorted((u, v)))
        if normalized_edge in seen:
            return False
        seen.add(normalized_edge)

    return True
