"""Machine-generated input-constraint validator for problem 'binary-tree-right-side-view'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced list type, element types (int or None), value ranges for nodes, and total node count. Did not enforce structural validity of the tree (e.g., whether nulls are placed correctly for a binary tree) as that is often considered part of the problem's semantic guarantee or implementation detail, but strictly speaking, a 'level-order array' implies a specific structure. However, standard LeetCode inputs are guaranteed to be valid trees. The constraint 'number of nodes' refers to actual nodes, not list length.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root):
    # The problem states the input is a binary tree encoded as a level-order list.
    # We must validate this list structure.
    
    # Check if root is a list
    if not isinstance(root, list):
        return False
    
    # Constraint: The number of nodes is in [0, 100].
    # Note: The list length includes nulls. The number of *nodes* is the count of non-null elements.
    # However, usually constraints on "number of nodes" refer to the actual nodes present.
    # Let's count non-null elements to be precise about "nodes".
    node_count = 0
    
    for item in root:
        # Each element must be either an integer or None
        if item is not None:
            if not isinstance(item, int) or isinstance(item, bool):
                return False
            # Constraint: -100 <= node value <= 100
            if not (-100 <= item <= 100):
                return False
            node_count += 1
        elif not isinstance(item, type(None)):
            # If it's not None, it must be an int (checked above). 
            # If it is None, it's valid. If it's anything else, invalid.
            return False
            
    # Check node count constraint
    if not (0 <= node_count <= 100):
        return False
        
    return True
