"""Machine-generated input-constraint validator for problem 'letter-tile-possibilities'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(tiles):
    if not isinstance(tiles, str):
        return False
    if not (1 <= len(tiles) <= 7):
        return False
    for ch in tiles:
        if not ('A' <= ch <= 'Z'):
            return False
    return True
