"""Machine-generated input-constraint validator for problem 'word-search'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: board dimensions (1-6), rectangular shape, single English letter cells, word length (1-15), and English letter characters. Skipped semantic guarantee about word existence.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(board, word):
    # Check board type
    if not isinstance(board, list):
        return False
    
    # Check board dimensions and rectangular shape
    m = len(board)
    if not (1 <= m <= 6):
        return False
    
    if m == 0:
        return False
        
    n = len(board[0])
    if not (1 <= n <= 6):
        return False
    
    # Check each row
    for row in board:
        if not isinstance(row, list):
            return False
        if len(row) != n:
            return False
        for cell in row:
            if not isinstance(cell, str):
                return False
            if len(cell) != 1:
                return False
            if not cell.isalpha():
                return False
    
    # Check word type and constraints
    if not isinstance(word, str):
        return False
    
    if not (1 <= len(word) <= 15):
        return False
    
    for char in word:
        if not char.isalpha():
            return False
            
    return True
