"""Machine-generated input-constraint validator for problem 'maximum-swap'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(num):
    if isinstance(num, bool) or not isinstance(num, int):
        return False
    if not (0 <= num <= 10**8):
        return False
    return True
