"""Machine-generated input-constraint validator for problem 'length-of-last-word'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'There will be at least one word in s' as it is a semantic guarantee about the content structure rather than a simple character set or length constraint, and verifying it requires parsing logic similar to solving the problem.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s):
    if not isinstance(s, str):
        return False
    if not (1 <= len(s) <= 10**4):
        return False
    for char in s:
        if not (char.isalpha() or char == ' '):
            return False
    return True
