"""Machine-generated input-constraint validator for problem 'max-dot-product-of-two-subsequences'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums1, nums2):
    if not isinstance(nums1, list) or not isinstance(nums2, list):
        return False
    if not (1 <= len(nums1) <= 500):
        return False
    if not (1 <= len(nums2) <= 500):
        return False
    for x in nums1:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (-1000 <= x <= 1000):
            return False
    for x in nums2:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (-1000 <= x <= 1000):
            return False
    return True
