"""Machine-generated input-constraint validator for problem 'text-justification'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(words, maxWidth):
    if not isinstance(words, list):
        return False
    if not isinstance(maxWidth, int) or isinstance(maxWidth, bool):
        return False
    if not (1 <= len(words)):
        return False
    if not (1 <= maxWidth):
        return False
    for word in words:
        if not isinstance(word, str):
            return False
        if len(word) > maxWidth:
            return False
    return True
