"""Machine-generated input-constraint validator for problem 'path-sum-exists'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Assumed 'root' is a list based on 'encoded as a level-order list' and examples, despite parameter type hint 'TreeNode'. Enforced node count and value ranges. Skipped structural validity of the tree (e.g. whether the list actually forms a valid binary tree) as it is a semantic guarantee/complex check not strictly a simple input bound, though typically implied. However, standard LeetCode inputs are valid. I will stick to simple bounds.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root, targetSum):
    # Validate targetSum type and range
    if not isinstance(targetSum, int) or isinstance(targetSum, bool):
        return False
    if not (-1000 <= targetSum <= 1000):
        return False

    # Validate root structure
    # The problem states root is a TreeNode object or None.
    # However, the examples show level-order arrays. 
    # The prompt says: "your function works with TreeNode objects... Trees are shown below in LeetCode level-order array form".
    # Usually, in these validation tasks, if the parameter type is declared as TreeNode, we expect a TreeNode object.
    # But often in LeetCode-style inputs provided as raw data for validation, the 'root' might be passed as the list representation 
    # if the wrapper hasn't converted it yet, OR the problem implies the input *is* the list.
    # Let's look at the parameter declaration: "root: TreeNode (a binary tree, encoded as a level-order list with null for absent children)".
    # This is contradictory. "TreeNode" usually means an object. "encoded as a level-order list" means a list.
    # Given the examples: Input: root = [5,4,8...], it is highly likely the input `root` is a list.
    # If `root` were a TreeNode object, the example would likely say `root = TreeNode(5, ...)`.
    # I will assume `root` is a list representing the tree, as per the "encoded as" description and examples.
    
    if not isinstance(root, list):
        return False

    # Count nodes and validate values
    node_count = 0
    for val in root:
        if val is None:
            continue
        # Check if value is an integer (and not bool)
        if not isinstance(val, int) or isinstance(val, bool):
            return False
        # Check value range
        if not (-1000 <= val <= 1000):
            return False
        node_count += 1

    # Check node count constraint
    if not (0 <= node_count <= 5000):
        return False

    return True
