"""Machine-generated input-constraint validator for problem 'search-in-rotated-sorted-array-ii'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'sorted in ascending order is rotated' and 'may contain duplicates' as these are semantic properties/guarantees about the data structure, not simple input bounds checkable without solving or complex analysis.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums, target):
    if not isinstance(nums, list):
        return False
    if not (1 <= len(nums) <= 5000):
        return False
    for x in nums:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (-10**4 <= x <= 10**4):
            return False
    if isinstance(target, bool) or not isinstance(target, int):
        return False
    if not (-10**4 <= target <= 10**4):
        return False
    return True
