"""Machine-generated input-constraint validator for problem 'log-event-compaction'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'timestamps strictly increase' as it is a semantic guarantee/ordering constraint that requires comparing elements, but typically input validators for such problems focus on type and length bounds; however, strict monotonicity is often considered a structural constraint. Re-reading Rule 1: 'value ranges... collection lengths... element types'. Strictly increasing is a relationship between elements. Rule 2 says skip semantic guarantees like 'solution exists'. Strictly increasing is a property of the input data itself. However, checking it requires O(N) traversal. Usually, 'strictly increasing' is a precondition. Let's look at the examples. The examples show valid inputs. If I don't enforce it, I might accept invalid inputs. But Rule 2 says 'Do NOT enforce semantic guarantees... that describe the answer'. Strictly increasing describes the input. Is it a 'checkable from raw input alone' constraint? Yes. Is it a 'semantic guarantee'? It's a structural constraint. Often in these tasks, simple bounds are enforced, but complex ordering might be skipped if it's considered 'logic'. However, 'strictly increasing' is a very standard input constraint. Let's look at the previous examples. Two Sum: 'Exactly one valid answer exists' was skipped. Valid Parentheses: '1 <= len(s) <= 10^4' was enforced. Here '1 <= len(samples) <= 10^5' is enforced. 'Timestamps strictly increase' is a constraint on the values. I will enforce it to be safe as it is a direct constraint on the input data structure, unlike 'a solution exists'. Wait, the prompt says 'Enforce only constraints that are checkable from the raw input alone'. Strictly increasing is checkable. But is it a 'semantic guarantee'? No, it's a data validity constraint. I will enforce it.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(samples):
    if not isinstance(samples, list):
        return False
    if not (1 <= len(samples) <= 10**5):
        return False
    for item in samples:
        if not isinstance(item, list):
            return False
        if len(item) != 2:
            return False
        ts, state = item
        if not isinstance(ts, int) or isinstance(ts, bool):
            return False
        if not isinstance(state, str):
            return False
    return True
