"""Machine-generated input-constraint validator for problem 'root-to-leaf-paths-target'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced node count [0, 5000], value ranges [-1000, 1000] for nodes and targetSum, and basic structural validity of the level-order list (root not None if list non-empty). Did not enforce semantic guarantees about path sums.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root, targetSum):
    # Validate targetSum
    if not isinstance(targetSum, int) or isinstance(targetSum, bool):
        return False
    if not (-1000 <= targetSum <= 1000):
        return False

    # Validate root structure (level-order list)
    if not isinstance(root, list):
        return False
    
    # Check node count constraint
    # The number of nodes is the count of non-None elements
    node_count = 0
    for val in root:
        if val is not None:
            node_count += 1
            # Validate node value type and range
            if not isinstance(val, int) or isinstance(val, bool):
                return False
            if not (-1000 <= val <= 1000):
                return False
        else:
            # val is None, which is allowed for missing children
            pass
            
    if not (0 <= node_count <= 5000):
        return False

    # Basic structural validity of level-order list:
    # 1. If the list is empty, it represents an empty tree (0 nodes), which is valid.
    # 2. If the list is not empty, the first element cannot be None (root must exist if tree is not empty).
    if len(root) > 0 and root[0] is None:
        return False

    return True
