"""Machine-generated input-constraint validator for problem 'cheapest-flight-with-k-stops'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(n, flights, src, dst, k):
    # Check n
    if not isinstance(n, int) or isinstance(n, bool):
        return False
    if not (1 <= n <= 100):
        return False

    # Check flights
    if not isinstance(flights, list):
        return False
    if not (0 <= len(flights) <= n * (n - 1)):
        return False
    for flight in flights:
        if not isinstance(flight, list):
            return False
        if len(flight) != 3:
            return False
        u, v, w = flight
        # Check u, v, w types and ranges
        if not isinstance(u, int) or isinstance(u, bool):
            return False
        if not isinstance(v, int) or isinstance(v, bool):
            return False
        if not isinstance(w, int) or isinstance(w, bool):
            return False
        if not (0 <= u < n):
            return False
        if not (0 <= v < n):
            return False
        if u == v:
            return False
        if not (1 <= w <= 10**4):
            return False

    # Check src
    if not isinstance(src, int) or isinstance(src, bool):
        return False
    if not (0 <= src < n):
        return False

    # Check dst
    if not isinstance(dst, int) or isinstance(dst, bool):
        return False
    if not (0 <= dst < n):
        return False

    # Check k
    if not isinstance(k, int) or isinstance(k, bool):
        return False
    if not (0 <= k < n):
        return False

    return True
