"""Machine-generated input-constraint validator for problem 'meeting-rooms'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length bounds, element structure (list of 2 ints), and value ranges for start/end. Did not enforce the semantic guarantee that a solution exists or specific overlap properties, as those are problem logic, not input constraints.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(intervals):
    if not isinstance(intervals, list):
        return False
    if not (0 <= len(intervals) <= 10**4):
        return False
    for interval in intervals:
        if not isinstance(interval, list):
            return False
        if len(interval) != 2:
            return False
        start, end = interval
        if not (isinstance(start, int) and not isinstance(start, bool)):
            return False
        if not (isinstance(end, int) and not isinstance(end, bool)):
            return False
        if not (0 <= start < end <= 10**9):
            return False
    return True
