"""Machine-generated input-constraint validator for problem 'stream-of-characters'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(words, queries):
    if not isinstance(words, list) or not isinstance(queries, list):
        return False
    if not (1 <= len(words) <= 2000):
        return False
    if not (1 <= len(queries) <= 4 * 10**4):
        return False
    for w in words:
        if not isinstance(w, str):
            return False
        if not w.islower() or not w.isalpha():
            return False
    for q in queries:
        if not isinstance(q, str):
            return False
        if len(q) != 1:
            return False
        if not q.islower() or not q.isalpha():
            return False
    return True
