"""Machine-generated input-constraint validator for problem 'median-from-data-stream'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length bounds, operation structure, value ranges, and the constraint that findMedian only occurs after at least one addNum.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(operations):
    if not isinstance(operations, list):
        return False
    if not (1 <= len(operations) <= 10**5):
        return False
    
    count_add = 0
    for op in operations:
        if not isinstance(op, list):
            return False
        if len(op) == 2:
            if op[0] != "addNum":
                return False
            x = op[1]
            if isinstance(x, bool) or not isinstance(x, int):
                return False
            if not (-10**6 <= x <= 10**6):
                return False
            count_add += 1
        elif len(op) == 1:
            if op[0] != "findMedian":
                return False
            if count_add == 0:
                return False
        else:
            return False
            
    return True
