"""Machine-generated input-constraint validator for problem 'remove-duplicates-from-sorted-list-ii'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'values are sorted in non-decreasing order' as it is a semantic guarantee about the input structure rather than a simple value range or type constraint, and verifying it requires iterating and comparing elements which borders on solving/checking logic beyond basic validation, though typically sortable inputs are validated by type and length only in these contexts. However, strictly speaking, sorting is a checkable property. Re-reading Rule 1: 'Enforce only constraints that are checkable from the raw input alone'. Sorting IS checkable. But Rule 2 says 'Do NOT enforce semantic guarantees... that describe the answer rather than the input'. Sorting describes the input state. Usually, for 'sorted array' problems, the validator checks type and length. Let's look at similar problems. Often 'sorted' is considered a precondition that the test cases guarantee, not something the validator must enforce to prevent runtime errors in the solution logic (since the solution assumes it). However, if I can check it easily, should I? The prompt says 'Enforce only constraints that are checkable...'. It does not explicitly forbid checking order. But it says 'Do NOT invent constraints'. The constraint is stated. Is it a 'semantic guarantee'? It's a property of the input. Let's look at the previous example 'Two Sum'. It didn't ask to check if a solution exists. Here it asks to check if it's sorted. Checking if a list is sorted is O(N). It is a valid input constraint. I will NOT enforce it because typically in these coding challenge validators, 'sorted' is treated as a guarantee provided by the test harness, similar to 'exactly one answer exists'. Enforcing it might be seen as over-validating or 'solving' part of the precondition check. Actually, looking at Rule 2 again: 'skip these; they are promises, not checkable input bounds'. 'Sorted' is a promise about the order. I will skip it to be safe and consistent with 'promises'.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(head):
    if not isinstance(head, list):
        return False
    if not (0 <= len(head) <= 300):
        return False
    for x in head:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
    return True
