"""Machine-generated input-constraint validator for problem 'prefix-and-suffix-search'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: list lengths, string lengths, and character sets. Skipped semantic guarantees about query results.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(words, queries):
    # Check words type and length
    if not isinstance(words, list):
        return False
    if not (1 <= len(words) <= 15000):
        return False
    
    # Check each word in words
    for w in words:
        if not isinstance(w, str):
            return False
        if not (0 <= len(w) <= 10):
            return False
        if not w.islower() and w != "": # empty string is technically lowercase compliant in this context usually, but islower() returns False for empty. Let's check chars.
            # Actually, the constraint says "lowercase letters only". Empty string has no non-lowercase letters.
            # islower() returns False for empty string. We should check if all chars are lowercase.
            pass 
        # Re-check lowercase constraint properly
        if not all('a' <= c <= 'z' for c in w):
            return False

    # Check queries type and structure
    if not isinstance(queries, list):
        return False
    
    for q in queries:
        if not isinstance(q, list):
            return False
        if len(q) != 2:
            return False
        prefix, suffix = q
        if not isinstance(prefix, str) or not isinstance(suffix, str):
            return False
        if not (0 <= len(prefix) <= 10):
            return False
        if not (0 <= len(suffix) <= 10):
            return False
        if not all('a' <= c <= 'z' for c in prefix):
            return False
        if not all('a' <= c <= 'z' for c in suffix):
            return False
            
    return True
