"""Machine-generated input-constraint validator for problem 'union-find-connectivity-queries'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(n, operations):
    # Check n is an integer (not bool) and within range
    if not isinstance(n, int) or isinstance(n, bool):
        return False
    if not (1 <= n <= 10**4):
        return False

    # Check operations is a list
    if not isinstance(operations, list):
        return False

    # Check length of operations
    if not (1 <= len(operations) <= 10**5):
        return False

    # Check each operation
    for op in operations:
        if not isinstance(op, list):
            return False
        if len(op) != 3:
            return False
        
        command, a, b = op
        
        # Check command is a string and valid
        if not isinstance(command, str):
            return False
        if command not in ("union", "connected"):
            return False
        
        # Check a and b are integers (not bools) and within range
        if not isinstance(a, int) or isinstance(a, bool):
            return False
        if not isinstance(b, int) or isinstance(b, bool):
            return False
        
        if not (0 <= a < n):
            return False
        if not (0 <= b < n):
            return False

    return True
