"""Machine-generated input-constraint validator for problem 'in-memory-key-value-store'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'Snapshot ids are assigned in increasing order starting from 0' as it describes the system's behavior/output generation, not a constraint on the input operations themselves.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(operations):
    if not isinstance(operations, list):
        return False
    if not (1 <= len(operations) <= 10**5):
        return False
    
    valid_commands = {"set", "get", "delete", "snapshot", "getAt"}
    
    for op in operations:
        if not isinstance(op, list):
            return False
        if len(op) == 0:
            return False
        
        cmd = op[0]
        if not isinstance(cmd, str):
            return False
        if cmd not in valid_commands:
            return False
        
        if cmd == "set":
            if len(op) != 3:
                return False
            key, value = op[1], op[2]
            if not isinstance(key, str):
                return False
            if not isinstance(value, int) or isinstance(value, bool):
                return False
        elif cmd == "get":
            if len(op) != 2:
                return False
            key = op[1]
            if not isinstance(key, str):
                return False
        elif cmd == "delete":
            if len(op) != 2:
                return False
            key = op[1]
            if not isinstance(key, str):
                return False
        elif cmd == "snapshot":
            if len(op) != 1:
                return False
        elif cmd == "getAt":
            if len(op) != 3:
                return False
            key, id_val = op[1], op[2]
            if not isinstance(key, str):
                return False
            if not isinstance(id_val, int) or isinstance(id_val, bool):
                return False
            if id_val < 0:
                return False
                
    return True
