"""Machine-generated input-constraint validator for problem 'tic-tac-toe-winner'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'moves are valid: distinct cells, players alternate' as these are semantic guarantees about the sequence of moves rather than simple input bounds checkable in isolation without solving/processing the sequence logic.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(n, moves):
    # Check n is an integer (not bool) and within range
    if not isinstance(n, int) or isinstance(n, bool):
        return False
    if not (1 <= n <= 100):
        return False

    # Check moves is a list
    if not isinstance(moves, list):
        return False

    # Check each move
    for move in moves:
        # Each move must be a list of length 3
        if not isinstance(move, list) or len(move) != 3:
            return False
        
        row, col, player = move
        
        # Check row and col are integers (not bools) and within board bounds
        if not isinstance(row, int) or isinstance(row, bool):
            return False
        if not isinstance(col, int) or isinstance(col, bool):
            return False
        if not (0 <= row < n) or not (0 <= col < n):
            return False
            
        # Check player is an integer (not bool) and is 1 or 2
        if not isinstance(player, int) or isinstance(player, bool):
            return False
        if player not in (1, 2):
            return False

    return True
