"""Machine-generated input-constraint validator for problem 'valid-parenthesis-string'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length constraint and allowed character set. Did not enforce semantic validity (whether it *can* be made valid) as that requires solving the problem.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s):
    if not isinstance(s, str):
        return False
    if not (1 <= len(s) <= 100):
        return False
    allowed = {'(', ')', '*'}
    for char in s:
        if char not in allowed:
            return False
    return True
