"""Machine-generated input-constraint validator for problem 'word-dictionary'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length of operations, structure of each operation, command types, and character sets for words and patterns. Did not enforce semantic validity of the dictionary state.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(operations):
    if not isinstance(operations, list):
        return False
    if not (1 <= len(operations) <= 10**4):
        return False
    
    allowed_chars_word = set("abcdefghijklmnopqrstuvwxyz")
    allowed_chars_pattern = set("abcdefghijklmnopqrstuvwxyz.")
    
    for op in operations:
        if not isinstance(op, list):
            return False
        if len(op) != 2:
            return False
        
        command, arg = op
        
        if not isinstance(command, str):
            return False
        if not isinstance(arg, str):
            return False
        
        if command == "addWord":
            if not arg: # Assuming non-empty words based on typical constraints, though not explicitly stated, empty string is usually valid in these problems unless specified. However, 'words' implies content. Let's stick to char set.
                pass 
            if not all(c in allowed_chars_word for c in arg):
                return False
        elif command == "search":
            if not all(c in allowed_chars_pattern for c in arg):
                return False
        else:
            return False
            
    return True
