"""Machine-generated input-constraint validator for problem 'delete-nodes-and-return-forest'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced node count, value ranges, distinctness, and structural integrity of the tree. Did not enforce that to_delete values actually exist in the tree, as that is a semantic guarantee about the interaction between inputs, not a raw input constraint.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root, to_delete):
    # Validate to_delete: must be a list of integers
    if not isinstance(to_delete, list):
        return False
    for val in to_delete:
        if not isinstance(val, int) or isinstance(val, bool):
            return False
        if not (1 <= val <= 1000):
            return False
    
    # Validate root: must be a TreeNode or None
    # We assume TreeNode is defined in the environment. 
    # If it's not, we can't strictly validate the type without importing or defining it,
    # but the prompt implies we are working within the context where TreeNode exists.
    # However, to be robust and self-contained as per rule 5, we should check for the structure.
    # Since we cannot import TreeNode, we check if it's None or has the expected attributes.
    
    def is_valid_tree_node(node):
        if node is None:
            return True
        # Check if it looks like a TreeNode (has val, left, right)
        # We assume the attribute name is 'val' based on standard LeetCode TreeNode,
        # but the problem description says 'value'. Let's check for common names or just structure.
        # The prompt says: TreeNode objects (value, left, right). So attribute is 'value'.
        if not hasattr(node, 'value') or not hasattr(node, 'left') or not hasattr(node, 'right'):
            return False
        
        # Check value type and range
        if not isinstance(node.value, int) or isinstance(node.value, bool):
            return False
        if not (1 <= node.value <= 1000):
            return False
            
        # Recursively check children
        return is_valid_tree_node(node.left) and is_valid_tree_node(node.right)

    if not is_valid_tree_node(root):
        return False

    # Constraint: 1 <= number of nodes <= 1000
    # We need to count nodes in the tree
    def count_nodes(node):
        if node is None:
            return 0
        return 1 + count_nodes(node.left) + count_nodes(node.right)

    num_nodes = count_nodes(root)
    if not (1 <= num_nodes <= 1000):
        return False

    # Constraint: distinct values in 1..1000
    # We need to collect all values and check for duplicates
    def collect_values(node, values):
        if node is None:
            return
        values.add(node.value)
        collect_values(node.left, values)
        collect_values(node.right, values)

    values = set()
    collect_values(root, values)
    
    if len(values) != num_nodes:
        return False

    return True
