"""Machine-generated input-constraint validator for problem 'maximum-profit-job-scheduling'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: list types, equal lengths, length bounds, integer types (excluding bools), and value ranges for start, end, and profit.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(start, end, profit):
    # Check types
    if not isinstance(start, list) or not isinstance(end, list) or not isinstance(profit, list):
        return False
    
    # Check lengths are equal and within bounds
    n = len(start)
    if not (1 <= n <= 5 * 10**4):
        return False
    if len(end) != n or len(profit) != n:
        return False
    
    # Check element types and values
    for i in range(n):
        s = start[i]
        e = end[i]
        p = profit[i]
        
        # Check start[i] is int (not bool)
        if not isinstance(s, int) or isinstance(s, bool):
            return False
        # Check end[i] is int (not bool)
        if not isinstance(e, int) or isinstance(e, bool):
            return False
        # Check profit[i] is int (not bool)
        if not isinstance(p, int) or isinstance(p, bool):
            return False
        
        # Check value ranges
        if not (0 <= s < e <= 10**9):
            return False
        if not (1 <= p <= 10**4):
            return False
            
    return True
