"""Machine-generated input-constraint validator for problem 'subarray-sums-divisible-by-k'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(A, K):
    if not isinstance(A, list):
        return False
    if not (1 <= len(A) <= 3 * 10**4):
        return False
    for x in A:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (-10**4 <= x <= 10**4):
            return False
    if not isinstance(K, int) or isinstance(K, bool):
        return False
    if not (2 <= K <= 10**4):
        return False
    return True
