"""Machine-generated input-constraint validator for problem 'object-store-multipart'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: types, ranges, and structure. Did not enforce semantic guarantees about part completeness or specific values beyond the stated bounds.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(parts, expected):
    # Check expected type and range
    if not isinstance(expected, int) or isinstance(expected, bool):
        return False
    if expected < 1:
        return False

    # Check parts type
    if not isinstance(parts, list):
        return False

    # Check parts length
    if not (0 <= len(parts) <= 2 * 10**5):
        return False

    # Check each part
    for part in parts:
        if not isinstance(part, list):
            return False
        if len(part) != 2:
            return False
        
        part_number, size = part

        # Check part_number type and value
        if not isinstance(part_number, int) or isinstance(part_number, bool):
            return False
        if part_number <= 0:
            return False

        # Check size type and value (signed 64-bit integer range)
        if not isinstance(size, int) or isinstance(size, bool):
            return False
        if not (-2**63 <= size <= 2**63 - 1):
            return False

    return True
