"""Machine-generated input-constraint validator for problem 'sum-of-two-integers'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(a, b):
    if not isinstance(a, int) or isinstance(a, bool):
        return False
    if not isinstance(b, int) or isinstance(b, bool):
        return False
    if not (-1000 <= a <= 1000):
        return False
    if not (-1000 <= b <= 1000):
        return False
    return True
