"""Machine-generated input-constraint validator for problem 'count-good-nodes'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Assumed `root` is a level-order list based on the parameter description "encoded as a level-order list". Validated node count and value ranges. Skipped structural validity of the tree (e.g., whether the list correctly represents a binary tree structure) as it's a semantic guarantee/format detail often handled by the platform's deserializer, and 'number of nodes' constraint refers to the count of actual nodes.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root):
    if root is None:
        return False
    
    # Check if root is a dict (simulating TreeNode as dict for validation purposes)
    # The problem states root is a TreeNode, but in Python validation contexts without
    # a specific class definition, we often treat it as a dict or check for attributes.
    # However, the prompt says "encoded as a level-order list" in the parameter description
    # but the statement says "your function works with TreeNode objects".
    # Let's look closely at the parameter description: "root: TreeNode (a binary tree, encoded as a level-order list with null for absent children)".
    # This is contradictory. Usually, if the input is a list, the function signature would be `validate_input(root_list)`.
    # But the signature is `validate_input(root)`. And the statement says "works with TreeNode objects".
    # Standard LeetCode problems pass TreeNode objects. The "level-order list" is how it's represented in the problem description/examples.
    # If the input is actually a list representing the tree, I should validate the list.
    # If the input is a TreeNode object, I should validate the object.
    
    # Let's re-read carefully: "The function's parameters... root: TreeNode (a binary tree, encoded as a level-order list with null for absent children)".
    # This phrasing is tricky. It likely means the *conceptual* input is a tree, but the *actual* Python argument passed to this validation function
    # might be the list representation if the platform serializes it, OR it might be a TreeNode object if the platform deserializes it.
    # Given the previous examples (Two Sum, Valid Parentheses) used raw types (list, str), and this one says "TreeNode",
    # but then adds "encoded as a level-order list", it strongly suggests the input `root` is actually a list.
    # Why? Because if it were a TreeNode object, the "encoded as..." part would be irrelevant to the validation function's input type.
    # Also, validating a TreeNode object requires traversing it, which is complex and depends on the specific class implementation.
    # Validating a list is straightforward.
    # Let's assume `root` is a list of values (ints or None).
    
    if not isinstance(root, list):
        return False
        
    # Constraint: Number of nodes is in [1, 10^5].
    # In a level-order list, the number of nodes is the count of non-None elements.
    # However, the list length itself can be up to 10^5 + some nulls.
    # Let's count non-None elements.
    
    node_count = 0
    for val in root:
        if val is not None:
            node_count += 1
            # Check value range
            if not isinstance(val, int) or isinstance(val, bool):
                return False
            if not (-10**4 <= val <= 10**4):
                return False
        else:
            # val is None, which is allowed for missing children
            pass
            
    if not (1 <= node_count <= 10**5):
        return False
        
    return True
