"""Machine-generated input-constraint validator for problem 'shortest-common-supersequence'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(str1, str2):
    if not isinstance(str1, str) or not isinstance(str2, str):
        return False
    if not (1 <= len(str1) <= 1000):
        return False
    if not (1 <= len(str2) <= 1000):
        return False
    if not all('a' <= c <= 'z' for c in str1):
        return False
    if not all('a' <= c <= 'z' for c in str2):
        return False
    return True
