"""Machine-generated input-constraint validator for problem 'minimum-refueling-stops'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced explicit bounds for target, startFuel, and stations length. Enforced position < target. Enforced sorting order. Did not enforce position >= 0 or fuel >= 0 as they were not explicitly stated in the constraints section, only implied by context.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(target, startFuel, stations):
    # Check target
    if not isinstance(target, int) or isinstance(target, bool):
        return False
    if not (1 <= target <= 10**9):
        return False

    # Check startFuel
    if not isinstance(startFuel, int) or isinstance(startFuel, bool):
        return False
    if not (1 <= startFuel <= 10**9):
        return False

    # Check stations
    if not isinstance(stations, list):
        return False
    if not (0 <= len(stations) <= 500):
        return False

    for station in stations:
        if not isinstance(station, list):
            return False
        if len(station) != 2:
            return False
        position, fuel = station
        if not isinstance(position, int) or isinstance(position, bool):
            return False
        if not isinstance(fuel, int) or isinstance(fuel, bool):
            return False
        # Constraint: all positions < target
        if not (position < target):
            return False
        # Implicit constraint from problem type: positions and fuel are non-negative
        # The problem statement implies physical quantities, but strictly speaking
        # only 'position < target' is explicitly bounded relative to target.
        # However, standard interpretation of 'position' and 'fuel' implies >= 0.
        # Let's check if the statement explicitly bounds them.
        # It says 'stations[i] = [position, fuel]'. It does not explicitly state >= 0.
        # But 'position' is a distance, 'fuel' is liters. Usually >= 0.
        # The constraint 'sorted by increasing position' implies order.
        # Let's stick to explicit constraints. The only explicit value constraint
        # on station elements is 'all < target'.
        # Wait, usually positions are >= 0. If position is negative, it's before start.
        # The problem says 'toward target'. Start is 0. So position >= 0 is implied.
        # Fuel >= 0 is implied.
        # Let's look at the constraints section again.
        # It does NOT explicitly say position >= 0 or fuel >= 0.
        # However, 'sorted by increasing position' is a structural constraint.
        # I will enforce position < target as stated.
        # I will NOT enforce position >= 0 or fuel >= 0 as they are not explicitly stated
        # in the 'Constraints' section, though physically implied. 
        # Actually, looking at similar problems, usually 0 <= position < target.
        # But rule 3 says 'Do NOT invent constraints'.
        # I will only enforce what is explicitly written.
        pass

    # Check sorting constraint: stations are sorted by increasing position
    for i in range(1, len(stations)):
        if stations[i][0] <= stations[i-1][0]:
            return False

    return True
