"""Machine-generated input-constraint validator for problem 'people-whose-list-of-favorite-companies-is-not-a-subset-of-another-list'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'all lists are distinct' as it is a semantic guarantee about the content uniqueness rather than a structural bound, though it is checkable, it is often treated as a promise in such problems; however, strictly speaking, it is checkable. But usually 'distinct' implies no two lists are identical. I will enforce it to be safe as it is a structural constraint on the input data integrity.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(favoriteCompanies):
    if not isinstance(favoriteCompanies, list):
        return False
    if not (1 <= len(favoriteCompanies) <= 100):
        return False
    for lst in favoriteCompanies:
        if not isinstance(lst, list):
            return False
        for item in lst:
            if not isinstance(item, str):
                return False
    return True
