"""Machine-generated input-constraint validator for problem 'number-of-islands'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced rectangular shape, dimensions 1-300, and cell values '0'/'1'. No semantic guarantees to skip.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(grid):
    if not isinstance(grid, list):
        return False
    m = len(grid)
    if not (1 <= m <= 300):
        return False
    if m == 0:
        return False
    n = len(grid[0])
    if not (1 <= n <= 300):
        return False
    for row in grid:
        if not isinstance(row, list):
            return False
        if len(row) != n:
            return False
        for cell in row:
            if not isinstance(cell, str):
                return False
            if cell not in ('0', '1'):
                return False
    return True
