"""Machine-generated input-constraint validator for problem 'product-except-self'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  The problem statement provides no explicit constraints on length or value ranges, so only the type constraint (list of integers) is enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums):
    if not isinstance(nums, list):
        return False
    for x in nums:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
    return True
