"""Machine-generated input-constraint validator for problem 'mirror-reflection'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(p, q):
    if not isinstance(p, int) or isinstance(p, bool):
        return False
    if not isinstance(q, int) or isinstance(q, bool):
        return False
    if not (1 <= p <= 1000):
        return False
    if not (0 <= q <= p):
        return False
    return True
