"""Machine-generated input-constraint validator for problem 'shortest-path-to-get-all-keys'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced grid dimensions (1-30), rectangular shape, and allowed character set. Did not enforce '1..6 keys' count or specific key/lock pairing logic as these are semantic guarantees or require solving.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(grid):
    if not isinstance(grid, list):
        return False
    
    if not grid:
        return False
        
    rows = len(grid)
    if not (1 <= rows <= 30):
        return False
        
    cols = len(grid[0])
    if not (1 <= cols <= 30):
        return False
        
    allowed_chars = set(". # @ abcdef ABCDEF")
    
    for row in grid:
        if not isinstance(row, str):
            return False
        if len(row) != cols:
            return False
        for char in row:
            if char not in allowed_chars:
                return False
                
    return True
