"""Machine-generated input-constraint validator for problem 'clone-graph'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'The Graph is connected' and 'Node.val is unique for each node' as these are semantic properties of the graph structure that require traversal or global consistency checks beyond simple input bounds, and 'no repeated edges' is partially enforced via set check but full graph symmetry is a semantic guarantee.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(adjList):
    if not isinstance(adjList, list):
        return False
    
    n = len(adjList)
    if not (0 <= n <= 100):
        return False
    
    for i, neighbors in enumerate(adjList):
        if not isinstance(neighbors, list):
            return False
        for val in neighbors:
            if not isinstance(val, int) or isinstance(val, bool):
                return False
            if not (1 <= val <= 100):
                return False
        # Check for duplicates in neighbor list
        if len(neighbors) != len(set(neighbors)):
            return False
        # Check for self-loops (node i+1 cannot have neighbor i+1)
        # The index in adjList is 0-based, representing node i+1.
        # So for adjList[i], the node value is i+1.
        # A self-loop would mean i+1 is in neighbors.
        if (i + 1) in neighbors:
            return False
            
    return True
