"""Machine-generated input-constraint validator for problem 'last-stone-weight-ii'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(stones):
    if not isinstance(stones, list):
        return False
    if not (1 <= len(stones) <= 30):
        return False
    for x in stones:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (1 <= x <= 100):
            return False
    return True
