"""Machine-generated input-constraint validator for problem 'number-of-ways-to-split-a-string'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s):
    if not isinstance(s, str):
        return False
    if not (3 <= len(s) <= 10**5):
        return False
    for ch in s:
        if ch not in ('0', '1'):
            return False
    return True
