"""Machine-generated input-constraint validator for problem 'lowest-common-ancestor-of-a-bst'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced node count, value ranges, uniqueness, p!=q, and existence of p/q. Skipped 'BST property' as it is a semantic guarantee about the tree structure relative to values, not a simple input bound, and verifying it requires traversing and comparing, which is close to solving, but more importantly, the problem asks for LCA in a BST, implying the input IS a BST. However, standard input validation usually checks structural integrity and value bounds. Verifying BST property is O(N) and distinct from simple bounds. Given the instruction 'Do NOT enforce semantic guarantees... that describe the answer', BST property is a guarantee about the input structure. But often 'BST' is a type constraint. I will NOT enforce BST property because it's a structural invariant, not a simple range/type check, and the prompt asks for 'checkable from raw input alone' like ranges and types. Verifying BST is complex. I will stick to structural and value bounds.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root, p, q):
    # Helper to check if a value is a valid integer (not bool)
    def is_valid_int(val):
        return isinstance(val, int) and not isinstance(val, bool)

    # Check p and q types and constraints
    if not is_valid_int(p) or not is_valid_int(q):
        return False
    if p == q:
        return False

    # Check root type
    if root is None:
        # A tree with 0 nodes violates 2 <= number of nodes
        return False
    
    # We need to traverse the tree to count nodes and check values.
    # The input 'root' is a TreeNode object.
    # We assume TreeNode has attributes: val, left, right.
    # Note: The problem statement says 'node.valueue' which is likely a typo for 'val' or 'value'.
    # Standard LeetCode TreeNode uses 'val'. We will check for 'val'.
    
    # Collect all nodes and their values
    nodes = []
    queue = [root]
    
    # We need to verify the tree structure is valid (no cycles, etc.) and count nodes.
    # Since it's a tree, simple BFS/DFS works. 
    # We also need to ensure all node values are valid integers within range.
    
    visited = set()
    
    while queue:
        node = queue.pop(0)
        if node is None:
            continue
        
        # Check for cycles (though unlikely in standard inputs, good for robustness)
        if id(node) in visited:
            return False
        visited.add(id(node))
        
        nodes.append(node)
        
        # Check if node has required attributes
        if not hasattr(node, 'val'):
            return False
            
        val = node.val
        if not is_valid_int(val):
            return False
            
        if not (-10**9 <= val <= 10**9):
            return False
            
        # Add children to queue
        # Check if left/right attributes exist
        if hasattr(node, 'left'):
            queue.append(node.left)
        else:
            return False # Structure violation
            
        if hasattr(node, 'right'):
            queue.append(node.right)
        else:
            return False # Structure violation

    # Check number of nodes
    if not (2 <= len(nodes) <= 10**5):
        return False

    # Check uniqueness of values
    values = [node.val for node in nodes]
    if len(set(values)) != len(values):
        return False

    # Check if p and q exist in the tree
    if p not in values or q not in values:
        return False

    return True
