"""Machine-generated input-constraint validator for problem 'parse-lisp-expression'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'expression is well-formed' and 'every value fits in a 32-bit signed integer' as these are semantic guarantees/promises about the input's validity and content, not checkable structural bounds on the raw string itself without parsing/evaluating.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(expression):
    if not isinstance(expression, str):
        return False
    if not (1 <= len(expression) <= 2000):
        return False
    return True
