"""Machine-generated input-constraint validator for problem 'minimum-deletion-cost-to-avoid-repeating-letters'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s, cost):
    if not isinstance(s, str):
        return False
    if not isinstance(cost, list):
        return False
    if not (1 <= len(s) <= 10**5):
        return False
    if len(s) != len(cost):
        return False
    if not all(c.islower() for c in s):
        return False
    for x in cost:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (1 <= x <= 10**4):
            return False
    return True
