"""Machine-generated input-constraint validator for problem 'surrounded-regions'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced dimensions and allowed characters; skipped semantic guarantees about connectivity or solvability.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(board):
    if not isinstance(board, list):
        return False
    if not (1 <= len(board) <= 200):
        return False
    for row in board:
        if not isinstance(row, list):
            return False
        if not (1 <= len(row) <= 200):
            return False
        for cell in row:
            if cell not in ("X", "O"):
                return False
    return True
