"""Machine-generated input-constraint validator for problem 'minimum-number-of-taps-to-open-to-water-a-garden'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(n, ranges):
    if not isinstance(n, int) or isinstance(n, bool):
        return False
    if not (1 <= n <= 10**4):
        return False
    if not isinstance(ranges, list):
        return False
    if len(ranges) != n + 1:
        return False
    for x in ranges:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (0 <= x <= 100):
            return False
    return True
