"""Machine-generated input-constraint validator for problem 'log-reordering'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length constraints and the structural constraint that each log's content is either all digits or all letters (ignoring spaces). Did not enforce sorting or reordering as those are output requirements.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(logs):
    if not isinstance(logs, list):
        return False
    if not (1 <= len(logs) <= 100):
        return False
    for log in logs:
        if not isinstance(log, str):
            return False
        if not log:
            return False
        parts = log.split(' ')
        if len(parts) < 2:
            return False
        content_parts = parts[1:]
        content = ' '.join(content_parts)
        if not content:
            return False
        is_digit_log = all(c.isdigit() or c == ' ' for c in content) and any(c.isdigit() for c in content)
        is_letter_log = all(c.isalpha() or c == ' ' for c in content) and any(c.isalpha() for c in content)
        if not (is_digit_log or is_letter_log):
            return False
    return True
