"""Machine-generated input-constraint validator for problem 'target-sum'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums, S):
    if not isinstance(nums, list):
        return False
    if not (1 <= len(nums) <= 20):
        return False
    for x in nums:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if x < 0:
            return False
    if isinstance(S, bool) or not isinstance(S, int):
        return False
    if sum(nums) > 1000:
        return False
    return True
