"""Machine-generated input-constraint validator for problem 'prime-palindrome'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'The answer exists and is less than 2*10^8' as it is a guarantee about the output, not a constraint on the input.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(N):
    if not isinstance(N, int) or isinstance(N, bool):
        return False
    if not (1 <= N <= 10**8):
        return False
    return True
