"""Machine-generated input-constraint validator for problem 'length-of-longest-fibonacci-subsequence'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length bounds, integer type (excluding bools), positivity, and strictly increasing order. No semantic guarantees about Fibonacci subsequences were enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(arr):
    if not isinstance(arr, list):
        return False
    if not (3 <= len(arr) <= 1000):
        return False
    for x in arr:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if x <= 0:
            return False
    # Check strictly increasing
    for i in range(1, len(arr)):
        if arr[i] <= arr[i - 1]:
            return False
    return True
