"""Machine-generated input-constraint validator for problem 'snakes-and-ladders'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'squares labeled 1 and n^2 are not the starting points of any snake or ladder' as it is a semantic guarantee about the board's configuration relative to the game logic, not a simple value range constraint on the raw input elements.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(board):
    if not isinstance(board, list):
        return False
    n = len(board)
    if not (2 <= n <= 20):
        return False
    for row in board:
        if not isinstance(row, list):
            return False
        if len(row) != n:
            return False
        for val in row:
            if not isinstance(val, int) or isinstance(val, bool):
                return False
            if val != -1 and not (1 <= val <= n * n):
                return False
    return True
