"""Machine-generated input-constraint validator for problem 'reverse-k-group'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length bounds for head, integer type for elements and k, and k >= 1. Did not enforce k <= len(head) as the problem statement explicitly allows k to exceed the list length.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(head, k):
    if not isinstance(head, list):
        return False
    if not (0 <= len(head) <= 5000):
        return False
    for x in head:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
    if not isinstance(k, int) or isinstance(k, bool):
        return False
    if not (1 <= k):
        return False
    return True
