"""Machine-generated input-constraint validator for problem 'vertical-order-traversal-of-a-binary-tree'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Treated root as a level-order list based on the parameter description 'encoded as a level-order list'. Enforced node count (non-None elements) and value ranges. Did not enforce tree structure validity (e.g., correct parent-child indexing) as it's not explicitly stated as a constraint, only the format.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root):
    # The problem states the input is a TreeNode object.
    # However, the examples and description mention "level-order array form".
    # The parameter declaration says: root: TreeNode (a binary tree, encoded as a level-order list with null for absent children)
    # This is contradictory. Usually, in these validation tasks, if the parameter type is declared as TreeNode,
    # we expect a TreeNode object. But the description explicitly says "encoded as a level-order list".
    # Let's look at the parameter declaration again: "root: TreeNode (a binary tree, encoded as a level-order list with null for absent children)"
    # This implies the input `root` is actually a list representing the tree, despite the name `TreeNode`.
    # Or it implies `root` is a TreeNode object, but the description is just explaining how trees are *shown*.
    # Given the explicit instruction "encoded as a level-order list", I will treat `root` as a list.
    # If `root` were a TreeNode object, the constraints on "number of nodes" would require traversal.
    # If `root` is a list, "number of nodes" is the count of non-null elements.
    
    # Let's re-read carefully: "The function's parameters (name and declared type) are: - root: TreeNode (a binary tree, encoded as a level-order list with null for absent children)"
    # This is a common pattern in LeetCode-style problems where the input is serialized.
    # I will validate `root` as a list.
    
    if not isinstance(root, list):
        return False
        
    # Constraint: 1 <= number of nodes <= 1000
    # Number of nodes is the count of non-None values in the list.
    node_count = 0
    for val in root:
        if val is not None:
            node_count += 1
            # Constraint: 0 <= node value <= 1000
            if not isinstance(val, int) or isinstance(val, bool):
                return False
            if not (0 <= val <= 1000):
                return False
        else:
            # val is None, which is allowed for missing children
            pass
            
    if not (1 <= node_count <= 1000):
        return False
        
    return True
