"""Machine-generated input-constraint validator for problem 'binary-tree-pruning'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Assumed input is a TreeNode object based on declared type, despite examples showing list representation. Validated node count (1-200) and values (0 or 1).
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root):
    # The problem states the input is a TreeNode object.
    # However, the examples and format description imply the input might be passed
    # as a level-order list representation in some contexts, but the signature says `root: TreeNode`.
    # The prompt explicitly says: "your function works with TreeNode objects".
    # But it also says: "Trees are shown below in LeetCode level-order array form".
    # And the examples show `root = [1,null,0,0,1]`.
    # This is a common ambiguity in LeetCode-style problems. Usually, the validator
    # receives the raw input format described in the examples if the problem statement
    # mixes them. However, the parameter declaration says `root: TreeNode`.
    # Let's look at the constraints: "1 <= number of nodes <= 200".
    # If `root` is a TreeNode object, we need to traverse it.
    # If `root` is a list (as per examples), we need to validate the list.
    
    # Given the explicit parameter type `TreeNode` in the prompt's parameter list,
    # I will assume the input is a TreeNode object. If it were a list, the type
    # would likely be `List[int]` or similar. The examples are just illustrative
    # of the tree structure.
    
    # However, looking at previous similar tasks, often the "raw input" for tree problems
    # in these automated validators is the list representation because constructing
    # TreeNode objects is part of the test harness, not the user input.
    # BUT, the prompt says: "The function's parameters (name and declared type) are: root: TreeNode".
    # And Rule 3: "When it is silent on element type, infer it from the declared parameter types".
    # So I must validate a TreeNode object.
    
    # Let's define a helper to validate a TreeNode structure.
    # A valid TreeNode has `val`, `left`, `right`.
    # `val` must be 0 or 1.
    # `left` and `right` must be None or valid TreeNodes.
    # The total number of nodes must be between 1 and 200.
    
    if root is None:
        # Constraint: 1 <= number of nodes. So empty tree is invalid.
        return False
        
    # Check if root is an instance of a class that looks like TreeNode
    # Since we don't have the TreeNode class definition, we check for attributes.
    # Or, more robustly, we can just check if it's not None and has the required attributes.
    # But wait, if the input is actually a list (as per examples), isinstance(root, list) would be true.
    # The prompt is contradictory: "works with TreeNode objects" vs examples showing lists.
    # Standard LeetCode input for these problems is often the list.
    # Let's re-read carefully: "your function works with TreeNode objects... Trees are shown below in LeetCode level-order array form".
    # This usually means the *problem description* shows arrays, but the *function argument* is a TreeNode.
    # I will stick to the declared type: TreeNode.
    
    # To be safe against the ambiguity, I'll check if it's a list first? No, Rule 3 says infer from declared type.
    # Declared type: TreeNode. I will assume it's an object with val, left, right.
    
    # We need to count nodes and check values.
    nodes = []
    queue = [root]
    
    while queue:
        node = queue.pop(0)
        if node is None:
            continue
        
        # Check if node has necessary attributes
        if not hasattr(node, 'val') or not hasattr(node, 'left') or not hasattr(node, 'right'):
            return False
            
        nodes.append(node)
        
        # Check value constraint: 0 or 1
        val = node.val
        if not isinstance(val, int) or isinstance(val, bool):
            return False
        if val not in (0, 1):
            return False
            
        queue.append(node.left)
        queue.append(node.right)
        
    # Check node count constraint: 1 <= number of nodes <= 200
    if not (1 <= len(nodes) <= 200):
        return False
        
    return True
