"""Machine-generated input-constraint validator for problem 'valid-number'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length and ASCII constraints. Did not enforce 'valid number' semantics as that is the problem to solve, not an input constraint.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s):
    if not isinstance(s, str):
        return False
    if not (1 <= len(s) <= 20):
        return False
    for char in s:
        if not (32 <= ord(char) <= 126):
            return False
    return True
