"""Machine-generated input-constraint validator for problem 'string-compression'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(chars):
    if not isinstance(chars, str):
        return False
    if not (0 <= len(chars) <= 10**5):
        return False
    for ch in chars:
        if not (ch.isalpha() or ch.isdigit()):
            return False
    return True
