"""Machine-generated input-constraint validator for problem 'magnetic-force-between-two-balls'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: types, ranges, length bounds, m bounds, and distinctness of position elements.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(position, m):
    if not isinstance(position, list):
        return False
    if not isinstance(m, int) or isinstance(m, bool):
        return False
    if not (2 <= len(position) <= 10**5):
        return False
    if not (2 <= m <= len(position)):
        return False
    for x in position:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (1 <= x <= 10**9):
            return False
    if len(set(position)) != len(position):
        return False
    return True
