"""Machine-generated input-constraint validator for problem 'longest-happy-prefix'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length bounds and lowercase letter constraint. 'Non-empty proper prefix' is part of the problem definition/answer logic, not an input constraint on s itself.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s):
    if not isinstance(s, str):
        return False
    if not (1 <= len(s) <= 10**5):
        return False
    if not s.islower():
        return False
    return True
