"""Machine-generated input-constraint validator for problem 'rectangle-area-ii'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(rectangles):
    if not isinstance(rectangles, list):
        return False
    if not (1 <= len(rectangles) <= 200):
        return False
    for rect in rectangles:
        if not isinstance(rect, list):
            return False
        if len(rect) != 4:
            return False
        for val in rect:
            if not isinstance(val, int) or isinstance(val, bool):
                return False
            if not (0 <= val <= 10**9):
                return False
    return True
