"""Machine-generated input-constraint validator for problem 'spiral-matrix'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced rectangular shape, dimensions 1-10, and element range -100 to 100. No semantic guarantees to skip.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(matrix):
    if not isinstance(matrix, list):
        return False
    m = len(matrix)
    if not (1 <= m <= 10):
        return False
    n = None
    for row in matrix:
        if not isinstance(row, list):
            return False
        if n is None:
            n = len(row)
            if not (1 <= n <= 10):
                return False
        elif len(row) != n:
            return False
        for val in row:
            if isinstance(val, bool) or not isinstance(val, int):
                return False
            if not (-100 <= val <= 100):
                return False
    if n is None:
        return False
    return True
