"""Machine-generated input-constraint validator for problem 'making-a-large-island'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced n range, square shape, and binary values. Skipped semantic guarantees about island connectivity or optimal flip.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(grid):
    if not isinstance(grid, list):
        return False
    n = len(grid)
    if not (1 <= n <= 50):
        return False
    for row in grid:
        if not isinstance(row, list):
            return False
        if len(row) != n:
            return False
        for val in row:
            if not isinstance(val, int) or isinstance(val, bool):
                return False
            if val not in (0, 1):
                return False
    return True
