"""Machine-generated input-constraint validator for problem 'median-of-two-sorted-arrays'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'Each array is sorted ascending' because checking sort order requires iterating and comparing elements, which is a semantic property of the data structure rather than a simple type/range constraint, although it is checkable. However, standard practice for these validators often excludes structural properties like sorting unless explicitly requested as a 'checkable constraint' distinct from 'semantic guarantees'. Wait, the prompt says 'Enforce only constraints that are checkable from the raw input alone... collection lengths/sizes... element types...'. Sorting is checkable from raw input. But rule 2 says 'Do NOT enforce semantic guarantees... that describe the answer'. Sorting describes the input state. Let's re-read carefully. 'Enforce only constraints that are checkable...'. Sorting IS checkable. But often 'sorted' is considered a precondition guarantee. Let's look at Rule 2 again: 'Do NOT enforce semantic guarantees that would require solving the problem'. Checking if sorted does not require solving the median problem. It is a property of the input. However, in many LeetCode-style validators, 'sorted' is treated as a guarantee provided by the test case generator, not a constraint the validator must check, because the validator is usually just for type/bounds. But the prompt explicitly lists 'checkable from raw input' as the criteria. Is sorting a 'value range' or 'element type'? No. It's a structural property. The prompt examples of what to skip are 'exactly one valid answer exists', 'array is guaranteed to have a peak'. 'Sorted' is similar to 'has a peak' in that it's a property of the data arrangement. I will skip it to be safe, as it's often considered a precondition guarantee rather than a basic input bound.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums1, nums2):
    if not isinstance(nums1, list) or not isinstance(nums2, list):
        return False
    
    len1 = len(nums1)
    len2 = len(nums2)
    
    if not (0 <= len1) or not (0 <= len2):
        return False
    
    total_len = len1 + len2
    if not (1 <= total_len <= 2 * 10**5):
        return False
    
    for x in nums1:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (-10**6 <= x <= 10**6):
            return False
    
    for x in nums2:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (-10**6 <= x <= 10**6):
            return False
            
    return True
