"""Machine-generated input-constraint validator for problem 'preimage-size-of-factorial-zeroes-function'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(K):
    if not isinstance(K, int) or isinstance(K, bool):
        return False
    if not (0 <= K <= 10**9):
        return False
    return True
