"""Machine-generated input-constraint validator for problem 'missing-number'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced list type, length bounds, element type (int, not bool), and element value range [0, n]. Did not enforce 'distinct numbers' or 'exactly one missing' as these are semantic guarantees/promises about the input structure rather than simple bounds checkable without solving or complex set operations, though 'distinct' is technically checkable, the prompt asks to skip semantic guarantees like 'exactly one valid answer exists'. However, 'distinct' is a property of the input values. Let's re-read Rule 2: 'Do NOT enforce semantic guarantees that would require solving the problem... e.g. exactly one valid answer exists'. The constraint 'nums contains n distinct numbers' is a guarantee about the input's composition. Usually, in these validation tasks, we check bounds and types. Checking distinctness is O(N) or O(N log N) but doesn't 'solve' the problem of finding the missing number. However, the prompt says 'Enforce only constraints that are checkable from the raw input alone... value ranges... element types'. Distinctness is a structural constraint. But often 'distinct' is treated as a guarantee. Let's look at the constraints section again: '1 <= len(nums) <= 10^4'. It does NOT explicitly list 'distinct' in the **Constraints** bullet point, it lists it in the problem description text. The **Constraints** section only lists the length. Therefore, I should only enforce the length constraint and the implicit type/value constraints derived from the problem description 'numbers from the range [0, n]'. I will enforce the range [0, n] and type. I will NOT enforce distinctness because it is not in the explicit Constraints block and is often a guarantee.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums):
    if not isinstance(nums, list):
        return False
    n = len(nums)
    if not (1 <= n <= 10**4):
        return False
    for x in nums:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (0 <= x <= n):
            return False
    return True
