"""Machine-generated input-constraint validator for problem 'shortest-alternating-path'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced n range, edge structure (list of lists of 2 ints), and node index bounds (0 to n-1). Did not enforce semantic guarantees about path existence or alternation.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(n, redEdges, blueEdges):
    # Check n
    if not isinstance(n, int) or isinstance(n, bool):
        return False
    if not (1 <= n <= 100):
        return False

    # Helper to validate edge list
    def validate_edges(edges):
        if not isinstance(edges, list):
            return False
        for edge in edges:
            if not isinstance(edge, list):
                return False
            if len(edge) != 2:
                return False
            for node in edge:
                if not isinstance(node, int) or isinstance(node, bool):
                    return False
                if not (0 <= node < n):
                    return False
        return True

    if not validate_edges(redEdges):
        return False
    if not validate_edges(blueEdges):
        return False

    return True
