"""Machine-generated input-constraint validator for problem 'largest-1-bordered-square'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced rectangular shape, dimensions 1-100, and element values 0 or 1. No semantic guarantees to skip.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(grid):
    if not isinstance(grid, list):
        return False
    if len(grid) < 1 or len(grid) > 100:
        return False
    cols = len(grid[0])
    if cols < 1 or cols > 100:
        return False
    for row in grid:
        if not isinstance(row, list):
            return False
        if len(row) != cols:
            return False
        for val in row:
            if isinstance(val, bool):
                return False
            if not isinstance(val, int):
                return False
            if val not in (0, 1):
                return False
    return True
