"""Machine-generated input-constraint validator for problem 'maximum-difference-between-node-and-ancestor'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced node count (2..5000) and value range (0..10^5) by traversing the TreeNode structure; no semantic guarantees to skip.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root):
    # `root` is a binary tree given as a TreeNode (value, left, right); None marks
    # an absent child / empty tree. Constraints:
    #   2 <= number of nodes <= 5000
    #   0 <= node value <= 10**5
    # The self-verify harness may hand this validator the tree either as a decoded
    # TreeNode (with .value / .val, .left, .right) or as its raw level-order list
    # (null for absent children); accept whichever legal form arrives.
    def _node_value(node):
        # The decoded node exposes .value (harness) and/or .val (LeetCode-style).
        if hasattr(node, "value"):
            return node.value
        if hasattr(node, "val"):
            return node.val
        raise AttributeError

    def _valid_value(v):
        if isinstance(v, bool) or not isinstance(v, int):
            return False
        return 0 <= v <= 10**5

    try:
        # --- Raw level-order-list encoding ---------------------------------
        if isinstance(root, list):
            count = 0
            for v in root:
                if v is None:
                    continue
                if not _valid_value(v):
                    return False
                count += 1
            return 2 <= count <= 5000

        # --- Decoded TreeNode encoding -------------------------------------
        if root is None:
            # 2 <= number of nodes, so the tree cannot be empty.
            return False
        queue = [root]
        count = 0
        while queue:
            node = queue.pop(0)
            if node is None:
                continue
            if not (hasattr(node, "left") and hasattr(node, "right")):
                return False
            if not _valid_value(_node_value(node)):
                return False
            count += 1
            if node.left is not None:
                queue.append(node.left)
            if node.right is not None:
                queue.append(node.right)
        return 2 <= count <= 5000
    except Exception:
        return False
