"""Machine-generated input-constraint validator for problem 'number-of-good-ways-to-split-a-string'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length bounds and lowercase letter constraint. Did not enforce 'non-empty parts' as that is a condition on the split operation, not the input string itself (though len >= 1 is required for any split to exist, the constraint is on the input s).
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s):
    if not isinstance(s, str):
        return False
    if not (1 <= len(s) <= 10**5):
        return False
    for char in s:
        if not ('a' <= char <= 'z'):
            return False
    return True
