"""Machine-generated input-constraint validator for problem 'strong-password-checker'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length bounds and printable ASCII constraint. Skipped semantic checks for strength (lowercase/uppercase/digit/runs) as those define the problem logic, not the input validity.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s):
    if not isinstance(s, str):
        return False
    if not (0 <= len(s) <= 100):
        return False
    for ch in s:
        code = ord(ch)
        if not (32 <= code <= 126):
            return False
    return True
