"""Machine-generated input-constraint validator for problem 'sort-colors'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums):
    if not isinstance(nums, list):
        return False
    if not (0 <= len(nums) <= 10**5):
        return False
    for x in nums:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if x not in (0, 1, 2):
            return False
    return True
