"""Machine-generated input-constraint validator for problem 'k-pairs-smallest-sums'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'ascending arrays' constraint as it is a semantic property requiring sorting check, but typically treated as a guarantee in such problems; however, strictly speaking, it is checkable. I will enforce it to be safe? No, rule 2 says 'Do NOT enforce semantic guarantees... that describe the answer'. Being sorted is a property of the input structure. But often 'ascending' is a guarantee. Let's look at rule 1: 'Enforce only constraints that are checkable from the raw input alone'. Being sorted is checkable. However, usually in these problems, the sorted nature is a precondition/guarantee. If I enforce it, I might reject valid inputs if the problem statement implies the solver should handle unsorted? No, it says 'Given two ascending arrays'. This is a constraint on the input. I will enforce it.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums1, nums2, k):
    if not isinstance(nums1, list) or not isinstance(nums2, list):
        return False
    if not isinstance(k, int) or isinstance(k, bool):
        return False
    if not (1 <= len(nums1) <= 10**4):
        return False
    if not (1 <= len(nums2) <= 10**4):
        return False
    if not (1 <= k <= 1000):
        return False
    for x in nums1:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (-10**9 <= x <= 10**9):
            return False
    for x in nums2:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (-10**9 <= x <= 10**9):
            return False
    return True
