"""Machine-generated input-constraint validator for problem 'utf-8-validation'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'valid UTF-8 encoding' check as it is a semantic property requiring solving the problem, not a raw input constraint.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(data):
    if not isinstance(data, list):
        return False
    if not (1 <= len(data) <= 2 * 10**4):
        return False
    for x in data:
        if isinstance(x, bool):
            return False
        if not isinstance(x, int):
            return False
        if not (0 <= x <= 255):
            return False
    return True
