"""Machine-generated input-constraint validator for problem 'minimum-cost-to-make-at-least-one-valid-path-in-a-grid'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced rectangular shape, dimensions 1-100, and element values in {1,2,3,4}. Skipped semantic path existence guarantees.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(grid):
    if not isinstance(grid, list):
        return False
    if len(grid) == 0:
        return False
    m = len(grid)
    if not (1 <= m <= 100):
        return False
    n = len(grid[0])
    if not (1 <= n <= 100):
        return False
    for row in grid:
        if not isinstance(row, list):
            return False
        if len(row) != n:
            return False
        for val in row:
            if not isinstance(val, int) or isinstance(val, bool):
                return False
            if val not in {1, 2, 3, 4}:
                return False
    return True
