"""Machine-generated input-constraint validator for problem 'robot-bounded-in-circle'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length bounds and allowed character set. Skipped semantic guarantee about bounded circle as it describes the answer, not the input.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(instructions):
    if not isinstance(instructions, str):
        return False
    if not (1 <= len(instructions) <= 100):
        return False
    allowed = {'G', 'L', 'R'}
    for char in instructions:
        if char not in allowed:
            return False
    return True
