"""Machine-generated input-constraint validator for problem 'flatten-binary-tree'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced node count [0, 2000] and value range [-100, 100]. Did not enforce structural validity of the level-order list (e.g., no child of a null node) as it was not explicitly stated as a constraint, only implied by the encoding format.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root):
    # The problem statement implies the input is a TreeNode object or None.
    # However, the examples show level-order lists. 
    # Rule 3 says: "When it is silent on element type, infer it from the declared parameter types shown below."
    # The declared parameter type is "TreeNode (a binary tree, encoded as a level-order list with null for absent children)".
    # This is ambiguous. Usually, in these validation tasks, if the parameter is named 'root' and type 'TreeNode',
    # we expect a TreeNode object. But the description explicitly says "encoded as a level-order list".
    # Let's look at the examples: Input: root = [1,2,5,3,4,null,6]. This is a list.
    # So the input 'root' is actually a list representing the tree, not a TreeNode object.
    # We must validate this list structure.
    
    if not isinstance(root, list):
        return False
    
    # Constraint: The number of nodes is in [0, 2000].
    # This refers to the number of actual nodes in the tree, not necessarily the length of the list
    # if the list contains trailing nulls? The problem says "trailing nulls dropped".
    # So len(root) is the number of nodes if we consider nulls as placeholders for missing children
    # but the list itself represents the structure.
    # Actually, in LeetCode level-order representation, the length of the list corresponds to the number of 
    # positions in the complete binary tree up to the last non-null node.
    # The constraint "number of nodes" usually means the count of non-null values.
    
    # Let's count non-null nodes.
    node_count = 0
    for val in root:
        if val is not None:
            node_count += 1
            # Constraint: -100 <= node value <= 100
            if not isinstance(val, int) or isinstance(val, bool):
                return False
            if not (-100 <= val <= 100):
                return False
        else:
            # val is None, which is allowed for missing children
            pass
            
    if not (0 <= node_count <= 2000):
        return False
        
    # Additional structural validation for level-order list:
    # A valid level-order list for a binary tree must not have a non-null value
    # at an index if its parent (at index (i-1)//2) is null, unless it's the root.
    # However, the problem statement says "trailing nulls dropped". 
    # It doesn't explicitly forbid internal nulls that would make the tree invalid structurally
    # in a strict sense, but typically LeetCode inputs are valid trees.
    # Given Rule 1: "Enforce only constraints that are checkable..." and Rule 3: "Do NOT invent constraints".
    # The constraints listed are only on node count and value range.
    # The structural validity is often assumed in such problems unless specified.
    # But wait, if I pass [1, null, 2], is that valid? Yes.
    # If I pass [1, null, null, 2], is that valid? No, because index 3's parent is index 1 (null).
    # Should I enforce this? The prompt says "encoded as a level-order list". 
    # If the input is malformed structurally, it's not a valid tree encoding.
    # However, the explicit constraints are only count and value.
    # Let's stick to the explicit constraints to avoid inventing ones.
    # But wait, if the input is [1, null, 2, 3], is it a valid tree? 
    # Index 0: 1. Index 1: null. Index 2: 2. Index 3: 3.
    # Parent of 3 is index 1 (null). So 3 cannot exist.
    # Most online judges guarantee valid tree structures. 
    # The prompt asks to enforce constraints stated in the statement.
    # The statement does NOT state "the list represents a valid binary tree structure".
    # It just says "encoded as a level-order list".
    # I will only enforce the explicit constraints: node count and value range.
    
    return True
