"""Machine-generated input-constraint validator for problem 'validate-ip-address'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced the explicit constraint that IP contains no spaces. Did not enforce IPv4/IPv6 structural rules as they are semantic guarantees/validity checks rather than raw input bounds.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(IP):
    if not isinstance(IP, str):
        return False
    # The constraint "IP has no spaces or special characters" is vague regarding
    # what constitutes a "special character" in the context of IP addresses (which
    # contain dots and colons). However, it explicitly forbids spaces.
    # We enforce the explicit prohibition of spaces.
    if ' ' in IP:
        return False
    # The problem statement implies IP is a string. No length bounds are given.
    # We do not enforce semantic validity (IPv4/IPv6 rules) as per Rule 2.
    return True
