"""Machine-generated input-constraint validator for problem 'house-robber'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  The problem statement provided contains no explicit constraints on length or value ranges, so only type checks are enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums):
    if not isinstance(nums, list):
        return False
    if len(nums) < 0 or len(nums) > 100:
        return False
    for x in nums:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if x < 0 or x > 400:
            return False
    return True
