"""Machine-generated input-constraint validator for problem 'reconstruct-itinerary'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'A valid itinerary is guaranteed to exist' and 'answer is unique' as they are semantic guarantees about the solution space, not checkable input bounds.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(tickets):
    if not isinstance(tickets, list):
        return False
    if not (1 <= len(tickets) <= 300):
        return False
    for ticket in tickets:
        if not isinstance(ticket, list):
            return False
        if len(ticket) != 2:
            return False
        for code in ticket:
            if not isinstance(code, str):
                return False
            if len(code) != 3:
                return False
            if not code.isupper():
                return False
            if not code.isalpha():
                return False
    return True
