"""Machine-generated input-constraint validator for problem 'split-linked-list-in-parts'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root, k):
    if not isinstance(root, list):
        return False
    if not (0 <= len(root) <= 1000):
        return False
    for x in root:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
    if not isinstance(k, int) or isinstance(k, bool):
        return False
    if not (1 <= k <= 50):
        return False
    return True
