"""Machine-generated input-constraint validator for problem 'queue-reconstruction-by-height'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'the input is always reconstructable' as it is a semantic guarantee about the existence of a solution, not a checkable constraint on the raw input values.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(people):
    if not isinstance(people, list):
        return False
    if not (1 <= len(people) <= 2000):
        return False
    for pair in people:
        if not isinstance(pair, list):
            return False
        if len(pair) != 2:
            return False
        h, k = pair
        if not (isinstance(h, int) and not isinstance(h, bool)):
            return False
        if not (isinstance(k, int) and not isinstance(k, bool)):
            return False
    return True
