"""Machine-generated input-constraint validator for problem 'remove-element'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums, val):
    if not isinstance(nums, list):
        return False
    if not (0 <= len(nums) <= 100):
        return False
    for x in nums:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (0 <= x <= 50):
            return False
    if not isinstance(val, int) or isinstance(val, bool):
        return False
    if not (0 <= val <= 100):
        return False
    return True
