"""Machine-generated input-constraint validator for problem 'longest-arithmetic-subsequence-of-given-difference'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(arr, difference):
    if not isinstance(arr, list):
        return False
    if not (1 <= len(arr) <= 10**5):
        return False
    for x in arr:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (-10**4 <= x <= 10**4):
            return False
    if isinstance(difference, bool) or not isinstance(difference, int):
        return False
    if not (-10**4 <= difference <= 10**4):
        return False
    return True
