"""Machine-generated input-constraint validator for problem 'maximum-candies-you-can-get-from-boxes'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: n range, array lengths matching n, element types (excluding bools), value ranges for status and candies, and index validity for keys, containedBoxes, and initialBoxes.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(status, candies, keys, containedBoxes, initialBoxes):
    # Check basic types for all inputs
    if not isinstance(status, list):
        return False
    if not isinstance(candies, list):
        return False
    if not isinstance(keys, list):
        return False
    if not isinstance(containedBoxes, list):
        return False
    if not isinstance(initialBoxes, list):
        return False

    # Determine n from status length
    n = len(status)
    
    # Constraint: 1 <= n <= 1000
    if not (1 <= n <= 1000):
        return False

    # Check that all arrays have length n
    if len(candies) != n:
        return False
    if len(keys) != n:
        return False
    if len(containedBoxes) != n:
        return False

    # Validate status elements: must be int (not bool) and in {0, 1}
    for x in status:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if x not in (0, 1):
            return False

    # Validate candies elements: must be int (not bool) and 1 <= x <= 1000
    for x in candies:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (1 <= x <= 1000):
            return False

    # Validate keys: list of lists of ints, indices valid (0 <= idx < n)
    for i in range(n):
        if not isinstance(keys[i], list):
            return False
        for k in keys[i]:
            if isinstance(k, bool) or not isinstance(k, int):
                return False
            if not (0 <= k < n):
                return False

    # Validate containedBoxes: list of lists of ints, indices valid (0 <= idx < n)
    for i in range(n):
        if not isinstance(containedBoxes[i], list):
            return False
        for b in containedBoxes[i]:
            if isinstance(b, bool) or not isinstance(b, int):
                return False
            if not (0 <= b < n):
                return False

    # Validate initialBoxes: list of ints, indices valid (0 <= idx < n)
    for b in initialBoxes:
        if isinstance(b, bool) or not isinstance(b, int):
            return False
        if not (0 <= b < n):
            return False

    return True
