"""Machine-generated input-constraint validator for problem 'race-car'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(target):
    if not isinstance(target, int) or isinstance(target, bool):
        return False
    if not (1 <= target <= 10000):
        return False
    return True
