"""Machine-generated input-constraint validator for problem 'stack-via-queues'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'pop/top are only called on a non-empty stack' as it is a semantic guarantee about the sequence of operations, not a static property of the input list.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(operations):
    if not isinstance(operations, list):
        return False
    if not (1 <= len(operations) <= 1000):
        return False
    for op in operations:
        if not isinstance(op, list):
            return False
        if len(op) == 0:
            return False
        if not isinstance(op[0], str):
            return False
        if op[0] == "push":
            if len(op) != 2:
                return False
            val = op[1]
            if isinstance(val, bool) or not isinstance(val, int):
                return False
        elif op[0] in ["pop", "top", "empty"]:
            if len(op) != 1:
                return False
        else:
            return False
    return True
