"""Machine-generated input-constraint validator for problem 'subarray-sum-equals-k'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums, k):
    if not isinstance(nums, list):
        return False
    if not (1 <= len(nums) <= 2 * 10**4):
        return False
    for x in nums:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (-1000 <= x <= 1000):
            return False
    if isinstance(k, bool) or not isinstance(k, int):
        return False
    if not (-10**7 <= k <= 10**7):
        return False
    return True
