"""Machine-generated input-constraint validator for problem 'pizza-with-3n-slices'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(slices):
    if not isinstance(slices, list):
        return False
    if not (1 <= len(slices) <= 500):
        return False
    if len(slices) % 3 != 0:
        return False
    for x in slices:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (1 <= x <= 1000):
            return False
    return True
