"""Machine-generated input-constraint validator for problem 'partition-list'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(head, x):
    if not isinstance(head, list):
        return False
    if not (0 <= len(head) <= 200):
        return False
    for val in head:
        if isinstance(val, bool) or not isinstance(val, int):
            return False
        if not (-100 <= val <= 100):
            return False
    if isinstance(x, bool) or not isinstance(x, int):
        return False
    if not (-200 <= x <= 200):
        return False
    return True
