"""Machine-generated input-constraint validator for problem 'knapsack-01'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(values, weights, capacity):
    # Check types for lists
    if not isinstance(values, list) or not isinstance(weights, list):
        return False
    
    # Check type for capacity (int, not bool)
    if not isinstance(capacity, int) or isinstance(capacity, bool):
        return False
    
    # Check lengths match and are within bounds
    if len(values) != len(weights):
        return False
    
    n = len(values)
    if not (0 <= n <= 1000):
        return False
    
    # Check capacity range
    if not (0 <= capacity <= 10**4):
        return False
    
    # Check elements in values
    for v in values:
        if not isinstance(v, int) or isinstance(v, bool):
            return False
        if not (0 <= v <= 10**4):
            return False
            
    # Check elements in weights
    for w in weights:
        if not isinstance(w, int) or isinstance(w, bool):
            return False
        if not (0 <= w <= 10**4):
            return False
            
    return True
