"""Machine-generated input-constraint validator for problem 'reducing-dishes'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(satisfaction):
    if not isinstance(satisfaction, list):
        return False
    if not (1 <= len(satisfaction) <= 500):
        return False
    for x in satisfaction:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (-10**3 <= x <= 10**3):
            return False
    return True
