"""Machine-generated input-constraint validator for problem 'restore-the-array'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length, digit-only content, no leading zero for s, and range for k. Skipped semantic guarantees about valid arrays.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s, k):
    if not isinstance(s, str):
        return False
    if not (1 <= len(s) <= 10**5):
        return False
    if not s.isdigit():
        return False
    if s[0] == '0':
        return False
    if not isinstance(k, int) or isinstance(k, bool):
        return False
    if not (1 <= k <= 10**9):
        return False
    return True
