"""Machine-generated input-constraint validator for problem 'max-points-on-a-line'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'All the points are unique' as it is a semantic guarantee about the data content rather than a structural or range constraint checkable without processing the whole set for duplicates (though technically checkable, it's often treated as a guarantee in these problems; however, strictly speaking, uniqueness is checkable. I will include it to be precise about 'checkable from raw input' but usually 'unique' constraints are guarantees. Re-reading rule 2: 'Do NOT enforce semantic guarantees... Skip these'. Uniqueness is a property of the input set. Is it a guarantee? Yes. Is it checkable? Yes. Rule 2 says skip guarantees. I will skip it to be safe as per 'promises, not checkable input bounds' interpretation often used in these prompts, although uniqueness is a bound on the set cardinality vs distinct elements. Actually, uniqueness is a constraint on the input values. But often 'All points are unique' is a promise to simplify the problem (no duplicate points handling). I will skip it.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(points):
    if not isinstance(points, list):
        return False
    if not (1 <= len(points) <= 300):
        return False
    for p in points:
        if not isinstance(p, list):
            return False
        if len(p) != 2:
            return False
        for coord in p:
            if not isinstance(coord, int) or isinstance(coord, bool):
                return False
            if not (-10**4 <= coord <= 10**4):
                return False
    return True
