"""Machine-generated input-constraint validator for problem 'min-stack'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'pop, top, getMin are only issued when the stack is non-empty' because this is a semantic guarantee about the execution state, not a static property of the input list.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(operations):
    if not isinstance(operations, list):
        return False
    if not (1 <= len(operations) <= 10**4):
        return False
    
    valid_commands = {"push", "pop", "top", "getMin"}
    
    for op in operations:
        if not isinstance(op, list):
            return False
        
        if len(op) == 0:
            return False
            
        cmd = op[0]
        if not isinstance(cmd, str):
            return False
        if cmd not in valid_commands:
            return False
            
        if cmd == "push":
            if len(op) != 2:
                return False
            x = op[1]
            if isinstance(x, bool) or not isinstance(x, int):
                return False
            if not (-10**9 <= x <= 10**9):
                return False
        else:
            # pop, top, getMin should have length 1
            if len(op) != 1:
                return False
                
    return True
