"""Machine-generated input-constraint validator for problem 'range-sum-of-sorted-subarray-sums'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable from the raw input and have been enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums, n, left, right):
    # Check nums is a list
    if not isinstance(nums, list):
        return False
    
    # Check n, left, right are integers (and not bools)
    for val in [n, left, right]:
        if not isinstance(val, int) or isinstance(val, bool):
            return False
    
    # Check n matches len(nums)
    if len(nums) != n:
        return False
    
    # Check n range: 1 <= n <= 10^3
    if not (1 <= n <= 10**3):
        return False
    
    # Check nums elements: 1 <= nums[i] <= 100
    for x in nums:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (1 <= x <= 100):
            return False
    
    # Check left and right range: 1 <= left <= right <= n*(n+1)/2
    max_subarrays = n * (n + 1) // 2
    if not (1 <= left <= right <= max_subarrays):
        return False
        
    return True
