"""Machine-generated input-constraint validator for design problem 'trie-prefix-search'.

Generated by scripts/generate_class_validators.py (deterministic, from the class
block in meta.json — no LLM). `validate_input(operations, args)` returns True iff
the method-call sequence is well-formed for the `Trie` class: aligned
operations/args lists, the constructor exactly once at the front, every later op a
declared method, and each arg list matching its op's arity and per-arg type.
Structure + type, plus the value bounds from the statement's Constraints
(hand-added at the bottom of `validate_input`; re-running the generator with
--force regenerates the structural part and drops them).
"""
import re


# op-name -> list of (base_type, list_dims) for each positional argument.
_SIG = {
    'Trie': [],
    'insert': [('string', 0)],
    'search': [('string', 0)],
    'startsWith': [('string', 0)],
}
_CTOR = 'Trie'


def _scalar_ok(v, base):
    if base == "int":
        return isinstance(v, int) and not isinstance(v, bool)
    if base in ("float", "num"):
        return isinstance(v, (int, float)) and not isinstance(v, bool)
    if base == "bool":
        return isinstance(v, bool)
    if base in ("string", "str", "char"):
        return isinstance(v, str)
    if base in ("TreeNode", "ListNode", "DoublyLinkedList"):
        # Wire form: a level-order / flat value list of ints (None marks a hole),
        # or None / [] for an empty structure.
        if v is None:
            return True
        if not isinstance(v, list):
            return False
        return all(x is None or (isinstance(x, int) and not isinstance(x, bool)) for x in v)
    # Iterator / NestedInteger / object / any / unknown: opaque — don't reject.
    return True


def _type_ok(v, base, dims):
    if dims == 0:
        return _scalar_ok(v, base)
    if not isinstance(v, list):
        return False
    return all(_type_ok(e, base, dims - 1) for e in v)


def validate_input(operations, args):
    if not isinstance(operations, list) or not isinstance(args, list):
        return False
    if len(operations) != len(args):
        return False
    if not operations:
        return False
    if operations[0] != _CTOR:
        return False
    for op in operations[1:]:
        if op == _CTOR or op not in _SIG:
            return False
    for op, a in zip(operations, args):
        sig = _SIG.get(op)
        if sig is None:
            return False
        if not isinstance(a, list) or len(a) != len(sig):
            return False
        for val, (base, dims) in zip(a, sig):
            if not _type_ok(val, base, dims):
                return False
    # --- value bounds from the statement's Constraints ---
    # At most 10**4 calls (excludes constructor); words/prefixes are 1..2000
    # lowercase English letters.
    if len(operations) - 1 > 10**4:
        return False
    for _op, a in zip(operations[1:], args[1:]):
        if not re.fullmatch(r'[a-z]{1,2000}', a[0]):
            return False
    return True
