"""Machine-generated input-constraint validator for problem 'invert-binary-tree'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced node value range and total node count. Skipped structural guarantees like 'binary tree' shape beyond basic left/right existence as they are implied by the TreeNode definition.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root):
    # The problem states root is a TreeNode or None.
    # We need to validate the structure and values recursively.
    
    # Helper to check if a node is a valid TreeNode instance
    # We assume TreeNode is defined in the environment, but we must be robust.
    # If TreeNode is not defined, we can't strictly validate type, but usually
    # in these contexts, we assume the class exists. However, to be purely
    # self-contained and robust against missing class definition, we might
    # just check for attributes if we can't import. But the prompt says
    # "standard library only" and "pure". It doesn't say we can't assume
    # the class exists if it's part of the signature. 
    # Let's assume TreeNode is available in the global scope as per typical
    # LeetCode-style environments. If not, isinstance will fail or we can
    # check for attributes. Given the strictness, let's try to import or
    # check attributes. Actually, the safest way without external deps is
    # to check for the presence of 'val', 'left', 'right' if we can't
    # rely on the class name. But the signature says `root: TreeNode`.
    # Let's assume `TreeNode` is a class defined elsewhere. If it's not,
    # this function might raise NameError. To avoid that, we can catch it
    # or check attributes. Let's check attributes for robustness.
    
    def is_valid_node(node):
        if node is None:
            return True
        # Check if it's a dict (common JSON-like representation) or an object
        # The problem says "TreeNode with value, left, right". 
        # Usually in Python LC, it's a class. Let's check for attributes.
        if not hasattr(node, 'val') and not hasattr(node, 'value'):
            # Some definitions use 'val', some 'value'. The problem says 'value'.
            # Let's stick to 'value' as per problem description.
            return False
        
        # Check value type and range
        val = getattr(node, 'value', None)
        if not isinstance(val, int) or isinstance(val, bool):
            return False
        if not (-100 <= val <= 100):
            return False
            
        # Check children
        left = getattr(node, 'left', None)
        right = getattr(node, 'right', None)
        
        # Recursively validate children
        if not is_valid_node(left):
            return False
        if not is_valid_node(right):
            return False
            
        return True

    # Validate the root node itself
    if not is_valid_node(root):
        return False
        
    # Count nodes to enforce 0 <= number of nodes <= 100
    def count_nodes(node):
        if node is None:
            return 0
        return 1 + count_nodes(getattr(node, 'left', None)) + count_nodes(getattr(node, 'right', None))
        
    num_nodes = count_nodes(root)
    if not (0 <= num_nodes <= 100):
        return False
        
    return True
