"""Machine-generated input-constraint validator for problem 'nth-magical-number'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(n, a, b):
    if not isinstance(n, int) or isinstance(n, bool):
        return False
    if not isinstance(a, int) or isinstance(a, bool):
        return False
    if not isinstance(b, int) or isinstance(b, bool):
        return False
    if not (1 <= n <= 10**9):
        return False
    if not (2 <= a <= 4 * 10**4):
        return False
    if not (2 <= b <= 4 * 10**4):
        return False
    return True
