"""Machine-generated input-constraint validator for problem 'rotate-image'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced n == len(matrix) == len(matrix[i]), 1 <= n <= 20, and -1000 <= matrix[i][j] <= 1000. Checked types strictly (excluding bools).
Do not edit by hand; re-run the generator instead.
"""

def validate_input(matrix):
    if not isinstance(matrix, list):
        return False
    n = len(matrix)
    if not (1 <= n <= 20):
        return False
    for row in matrix:
        if not isinstance(row, list):
            return False
        if len(row) != n:
            return False
        for val in row:
            if isinstance(val, bool) or not isinstance(val, int):
                return False
            if not (-1000 <= val <= 1000):
                return False
    return True
