"""Machine-generated input-constraint validator for problem 'valid-sudoku'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced board dimensions (9x9) and allowed character set ('1'-'9' or '.'). Did not enforce validity of Sudoku rules (no repetitions) as that is the problem to solve, not an input constraint.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(board):
    if not isinstance(board, list):
        return False
    if len(board) != 9:
        return False
    for row in board:
        if not isinstance(row, list):
            return False
        if len(row) != 9:
            return False
        for cell in row:
            if not isinstance(cell, str):
                return False
            if len(cell) != 1:
                return False
            if cell not in '123456789.':
                return False
    return True
