"""Machine-generated input-constraint validator for problem 'sort-characters-by-frequency'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length bounds and printable ASCII constraint (codes 32-126). No semantic guarantees to skip.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s):
    if not isinstance(s, str):
        return False
    if not (1 <= len(s) <= 5 * 10**5):
        return False
    for char in s:
        code = ord(char)
        if not (32 <= code <= 126):
            return False
    return True
