"""Machine-generated input-constraint validator for problem 'roman-to-integer'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 's is a valid roman numeral in the range [1, 3999]' as it is a semantic guarantee about the input's validity/meaning, not a simple syntactic constraint checkable without solving the problem.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s):
    if not isinstance(s, str):
        return False
    if not (1 <= len(s) <= 15):
        return False
    allowed = set('IVXLCDM')
    if not all(c in allowed for c in s):
        return False
    return True
