"""Machine-generated input-constraint validator for problem 'min-cost-to-connect-all-points'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'points distinct' as it is a semantic guarantee about the data content rather than a simple type/range constraint, and checking uniqueness is O(N^2) or requires hashing which might be considered solving-related or expensive for validation, though primarily it's a guarantee of the input state.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(points):
    if not isinstance(points, list):
        return False
    if not (1 <= len(points) <= 1000):
        return False
    for point in points:
        if not isinstance(point, list):
            return False
        if len(point) != 2:
            return False
        for coord in point:
            if not isinstance(coord, int) or isinstance(coord, bool):
                return False
            if not (-10**6 <= coord <= 10**6):
                return False
    return True
