"""Machine-generated input-constraint validator for problem 'single-number-ii'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'every value but one occurs three times' as it is a semantic guarantee about the input's structure rather than a simple bound checkable without solving/counting, and typically treated as a promise in such problems.
Do not edit by hand; re-run the generator instead.

Manual update (2026-07-08): Added structural constraint enforcement to ensure
test-strengthening engine only generates valid problem instances.
"""
from collections import Counter

def validate_input(nums):
    if not isinstance(nums, list):
        return False
    if len(nums) < 1:
        return False
    for x in nums:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
    # Structural constraint: exactly one element appears once, all others appear three times.
    counts = Counter(nums)
    freqs = list(counts.values())
    if freqs.count(1) != 1:
        return False
    if not all(f == 3 for f in freqs if f != 1):
        return False
    return True
