"""Machine-generated input-constraint validator for problem 'count-complete-tree-nodes'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced list type, length bounds, element types (int/None), and the structural constraint of a complete binary tree (no non-None values after the first None). Skipped semantic guarantees about node values.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root):
    # The problem statement says the function works with TreeNode objects,
    # but the examples and constraints describe a level-order array representation.
    # The parameter type hint says 'TreeNode', but the examples show lists.
    # However, the prompt explicitly states: "The function's parameters (name and declared type) are: root: TreeNode (a binary tree, encoded as a level-order list with null for absent children)".
    # This is a contradiction in the prompt's description vs standard LeetCode.
    # Usually, if the input is described as a level-order list in the examples, the validation should check the list.
    # But the parameter type says TreeNode. Let's look closer at the prompt's instruction:
    # "root: TreeNode (a binary tree, encoded as a level-order list with null for absent children)"
    # This implies the *input* to the function is the list representation, despite the name 'root' and type hint 'TreeNode'.
    # Wait, looking at previous examples, if the type is 'TreeNode', it usually means an object.
    # But the text in parentheses says "encoded as a level-order list".
    # Let's assume the input `root` is actually the list, as per the examples `root = [1,2,3,4,5,6]`.
    # If `root` were a TreeNode object, the examples would likely show object construction or the type hint would be clearer.
    # Given the ambiguity, I will validate based on the list representation because the examples use lists and the constraint "The tree is complete" is a property of the list structure.
    
    if not isinstance(root, list):
        return False
    
    n = len(root)
    
    # Constraint: The number of nodes is in [0, 5*10^4]
    if not (0 <= n <= 5 * 10**4):
        return False
        
    # Validate elements: integers or None
    for val in root:
        if val is not None:
            if not isinstance(val, int) or isinstance(val, bool):
                return False
                
    # Constraint: The tree is complete.
    # A complete binary tree in level-order representation means:
    # 1. All levels are fully filled except possibly the last.
    # 2. The last level has all keys as left as possible.
    # In a list representation, this implies that if there is a None, all subsequent elements must also be None.
    # Actually, LeetCode's level-order serialization for complete trees usually doesn't include trailing Nones.
    # However, if Nones are present in the middle, it violates completeness unless they are at the end.
    # More strictly, for a complete tree, if we index nodes 0 to n-1, the children of node i are 2i+1 and 2i+2.
    # If the list contains None, it represents a missing node. 
    # For a complete tree, missing nodes can only occur at the end of the last level.
    # Therefore, once we encounter a None, all following elements must be None.
    
    found_none = False
    for val in root:
        if val is None:
            found_none = True
        else:
            if found_none:
                # A non-None value appeared after a None, which violates the "left-filled" property of complete trees
                return False
                
    return True
