"""Machine-generated input-constraint validator for problem 'lowest-common-ancestor-of-a-binary-tree'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced node count, value ranges, uniqueness, p!=q, and existence of p/q. Did not enforce 'lowest common ancestor' logic as that is the problem to solve, not an input constraint.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root, p, q):
    # Validate p and q are integers (not bools)
    if not isinstance(p, int) or isinstance(p, bool):
        return False
    if not isinstance(q, int) or isinstance(q, bool):
        return False
    
    # Constraint: p != q
    if p == q:
        return False
    
    # Validate root is a TreeNode or None
    # We assume TreeNode is defined in the environment. 
    # If root is None, it's an empty tree (0 nodes), which violates 2 <= nodes.
    # However, we need to count nodes to check the constraint.
    
    # Helper to check if an object is a TreeNode
    # Since we can't import TreeNode, we check for attributes 'val', 'left', 'right'
    # or rely on the type name if possible. But standard practice in these validators
    # is to check structure. Let's assume standard TreeNode structure.
    
    def is_tn(node):
        if node is None:
            return True
        if not hasattr(node, 'val') or not hasattr(node, 'left') or not hasattr(node, 'right'):
            return False
        # Check val is int
        if not isinstance(node.val, int) or isinstance(node.val, bool):
            return False
        # Check val range
        if not (-10**9 <= node.val <= 10**9):
            return False
        return True

    # Count nodes and validate structure
    nodes = []
    if root is not None:
        queue = [root]
        while queue:
            curr = queue.pop(0)
            if curr is None:
                continue
            if not is_tn(curr):
                return False
            nodes.append(curr.val)
            queue.append(curr.left)
            queue.append(curr.right)
    
    # Constraint: 2 <= number of nodes <= 10^5
    if not (2 <= len(nodes) <= 10**5):
        return False
        
    # Constraint: all values unique
    if len(nodes) != len(set(nodes)):
        return False
        
    # Constraint: p and q exist in the tree
    if p not in nodes or q not in nodes:
        return False
        
    return True
