"""Machine-generated input-constraint validator for problem 'binary-tree-coloring-game'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Assumed root is a list based on the example, despite the type hint saying TreeNode. Enforced that non-None elements are a permutation of 1..n and count is n.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root, n, x):
    # Validate n
    if not isinstance(n, int) or isinstance(n, bool):
        return False
    if not (1 <= n <= 100):
        return False

    # Validate x
    if not isinstance(x, int) or isinstance(x, bool):
        return False
    if not (1 <= x <= n):
        return False

    # Validate root structure
    # The problem states root is a TreeNode object or None.
    # However, the example shows root as a list [1,2,3...].
    # The prompt says: "your function works with TreeNode objects... Trees are shown below in LeetCode level-order array form".
    # Usually, in these validation tasks, if the parameter type is declared as TreeNode, we expect a TreeNode object.
    # But the example input `root = [1,2,3,4,5,6,7,8,9,10,11]` suggests the input might be the list representation.
    # Let's look at the parameter declaration: "root: TreeNode (a binary tree, encoded as a level-order list with null for absent children)".
    # This is contradictory. "TreeNode" usually implies an object. "encoded as a level-order list" implies a list.
    # Given the explicit example `root = [1,2,3...]`, I will assume the input `root` is a list representing the tree.
    # If it were a TreeNode object, the example would likely be `TreeNode(1, ...)`.
    # Let's check the constraints: "node values are a permutation of 1..n".
    
    if not isinstance(root, list):
        return False
        
    # Check if the list represents a valid tree with n nodes
    # The list contains integers and None (for null).
    # We need to verify that the non-None values are a permutation of 1..n.
    
    values = []
    for val in root:
        if val is None:
            continue
        if not isinstance(val, int) or isinstance(val, bool):
            return False
        values.append(val)
        
    # The number of non-None nodes must be exactly n
    if len(values) != n:
        return False
        
    # The values must be a permutation of 1..n
    if sorted(values) != list(range(1, n + 1)):
        return False
        
    return True
