"""Machine-generated input-constraint validator for problem 'number-of-longest-increasing-subsequence'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'the answer fits in a 32-bit integer' as it is a guarantee about the output, not a checkable constraint on the raw input.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums):
    if not isinstance(nums, list):
        return False
    if not (1 <= len(nums) <= 2000):
        return False
    for x in nums:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
    return True
