"""Machine-generated input-constraint validator for problem 'ones-and-zeroes'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced binary string content ('0'/'1') based on problem description 'binary strings', as this is a type/value set constraint checkable from input.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(strs, m, n):
    # Check m and n types and ranges
    if not isinstance(m, int) or isinstance(m, bool):
        return False
    if not isinstance(n, int) or isinstance(n, bool):
        return False
    if not (0 <= m <= 100):
        return False
    if not (0 <= n <= 100):
        return False

    # Check strs type and length
    if not isinstance(strs, list):
        return False
    if not (1 <= len(strs) <= 600):
        return False

    # Check each element in strs
    for s in strs:
        if not isinstance(s, str):
            return False
        if not (1 <= len(s) <= 100):
            return False
        # The problem states "binary strings", implying they contain only '0' and '1'.
        # While not explicitly listed as a constraint line, "binary strings" is a type constraint.
        # However, rule 3 says "Do NOT invent constraints... When it is silent on element type, infer it from the declared parameter types".
        # The declared type is string[]. The text says "binary strings". 
        # Usually, in these problems, "binary string" implies content constraint.
        # Let's look at the constraints section again: "1 <= len(strs[i]) <= 100". It doesn't explicitly restrict chars.
        # But the problem description says "Given binary strings strs". This is a definition of the input.
        # If I pass ["2"], is it a valid input for the problem? No, it's not a binary string.
        # So I should enforce that characters are '0' or '1'.
        for char in s:
            if char not in ('0', '1'):
                return False

    return True
