"""Machine-generated input-constraint validator for problem 'soup-servings'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced type (int, not bool) and range [0, 10^9]. Skipped answer precision constraint as it describes the output, not the input.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(n):
    if isinstance(n, bool):
        return False
    if not isinstance(n, int):
        return False
    if not (0 <= n <= 10**9):
        return False
    return True
