"""Machine-generated input-constraint validator for problem 'smallest-range-covering-lists'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced k range, non-empty lists, integer types (excluding bools), value ranges, and sorted ascending order. Did not enforce semantic guarantees about the existence of a unique smallest range.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(lists):
    if not isinstance(lists, list):
        return False
    k = len(lists)
    if not (1 <= k <= 3000):
        return False
    for lst in lists:
        if not isinstance(lst, list):
            return False
        if len(lst) == 0:
            return False
        for x in lst:
            if isinstance(x, bool) or not isinstance(x, int):
                return False
            if not (-10**5 <= x <= 10**5):
                return False
        # Check if sorted ascending
        for i in range(len(lst) - 1):
            if lst[i] > lst[i+1]:
                return False
    return True
