"""Machine-generated input-constraint validator for problem 'subsets'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'values are distinct' as it is a semantic guarantee about the content rather than a strict type/range bound, though it is checkable; however, standard practice for these validators often treats distinctness as a problem guarantee unless explicitly bounded by range. Actually, distinctness IS checkable from raw input. I will enforce it to be safe and precise, as it is a constraint on the input data structure.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums):
    if not isinstance(nums, list):
        return False
    if not (0 <= len(nums) <= 12):
        return False
    for x in nums:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
    return True
