"""Machine-generated input-constraint validator for problem 'swap-for-longest-repeated-character-substring'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(text):
    if not isinstance(text, str):
        return False
    if not (1 <= len(text) <= 2 * 10**4):
        return False
    if not all('a' <= c <= 'z' for c in text):
        return False
    return True
