"""Machine-generated input-constraint validator for problem 'maximum-level-sum-of-a-binary-tree'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Assumed 'root' is a list based on 'encoded as a level-order list' in parameter description, despite 'TreeNode' type name. Validated node count and value ranges. Skipped structural validity of the tree (e.g. whether the list correctly represents a binary tree) as it's a semantic guarantee/formatting detail often assumed correct in such inputs, but primarily because 'checkable from raw input' for a list encoding is ambiguous without strict rules on trailing nulls. However, the constraint '1 <= number of nodes' is enforced by counting non-nulls.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root):
    # The problem states the input is a TreeNode object.
    # However, the examples and description mention "level-order array form".
    # The parameter declaration says 'root: TreeNode'.
    # Usually, in these validation tasks, if the parameter is declared as a specific object type
    # (like TreeNode), we validate that object structure. If it were declared as a list,
    # we would validate the list. Given the ambiguity of "encoded as a level-order list" in the
    # prompt's parameter description vs the "TreeNode" type hint, I must look at the prompt's
    # specific instruction: "The function's parameters (name and declared type) are: root: TreeNode".
    # But the prompt *also* says "encoded as a level-order list with null for absent children".
    # This is a contradiction. Let's look at the previous examples.
    # Example 1: nums (list), target (int). Validated as list/int.
    # Example 2: s (string). Validated as string.
    # Here: root (TreeNode). But the description says "encoded as a level-order list".
    # If I treat it as a TreeNode object, I need to traverse it.
    # If I treat it as a list, I need to validate the list.
    # The prompt says: "root: TreeNode (a binary tree, encoded as a level-order list with null for absent children)".
    # This phrasing usually implies the *input to the function* is the list representation,
    # despite the type name 'TreeNode' being used loosely or referring to the logical structure.
    # HOWEVER, standard LeetCode problems pass actual TreeNode objects.
    # Let's re-read carefully: "your function works with TreeNode objects... Trees are shown below in LeetCode level-order array form".
    # This suggests the *visual representation* is an array, but the *input* is a TreeNode.
    # BUT the parameter description says: "root: TreeNode (a binary tree, encoded as a level-order list...)".
    # This parenthetical explanation often describes the *data structure* passed in if it's not a standard object.
    # Let's look at the constraints: "1 <= number of nodes <= 10^4".
    # If it's a TreeNode object, I need to count nodes.
    # If it's a list, I need to count non-null elements.
    # Given the explicit "encoded as a level-order list" in the parameter description, it is highly likely
    # the input `root` is actually a list (or None), not a custom class instance.
    # If I assume it's a TreeNode class, I don't know the class definition.
    # If I assume it's a list, I can validate it.
    # Let's assume the input is a list representing the tree, as per the "encoded as..." clause.
    
    if root is None:
        # An empty tree has 0 nodes. Constraint: 1 <= number of nodes.
        return False
        
    if not isinstance(root, list):
        return False
        
    # Count nodes and validate values
    node_count = 0
    for val in root:
        if val is None:
            continue
        if isinstance(val, bool):
            return False
        if not isinstance(val, int):
            return False
        if not (-10**5 <= val <= 10**5):
            return False
        node_count += 1
        
    if not (1 <= node_count <= 10**4):
        return False
        
    return True
