"""Machine-generated input-constraint validator for problem 'max-score-multiplication'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all explicit length and value range constraints; no semantic guarantees to skip.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums, multipliers):
    if not isinstance(nums, list):
        return False
    if not isinstance(multipliers, list):
        return False
    
    m_len = len(multipliers)
    n_len = len(nums)
    
    if not (1 <= m_len <= 300):
        return False
    if not (m_len <= n_len <= 10**5):
        return False
        
    for x in nums:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (-1000 <= x <= 1000):
            return False
            
    for x in multipliers:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (-1000 <= x <= 1000):
            return False
            
    return True
