"""Machine-generated input-constraint validator for problem 'redundant-directed-connection'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length bounds, structure (list of pairs), integer types (excluding bools), and node label range 1..n derived from n=len(edges). Did not enforce semantic tree properties.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(edges):
    if not isinstance(edges, list):
        return False
    n = len(edges)
    if not (3 <= n <= 1000):
        return False
    for edge in edges:
        if not isinstance(edge, list):
            return False
        if len(edge) != 2:
            return False
        u, v = edge
        if not (isinstance(u, int) and not isinstance(u, bool)):
            return False
        if not (isinstance(v, int) and not isinstance(v, bool)):
            return False
        if not (1 <= u <= n) or not (1 <= v <= n):
            return False
    return True
