"""Machine-generated input-constraint validator for problem 'profitable-schemes'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced. No semantic guarantees were skipped as none were present in the constraints section.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(n, minProfit, group, profit):
    # Check n
    if not isinstance(n, int) or isinstance(n, bool):
        return False
    if not (1 <= n <= 100):
        return False

    # Check minProfit
    if not isinstance(minProfit, int) or isinstance(minProfit, bool):
        return False
    if not (0 <= minProfit <= 100):
        return False

    # Check group
    if not isinstance(group, list):
        return False
    if not (1 <= len(group) <= 100):
        return False
    for x in group:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (1 <= x <= 100):
            return False

    # Check profit
    if not isinstance(profit, list):
        return False
    if not (1 <= len(profit) <= 100):
        return False
    for x in profit:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (0 <= x <= 100):
            return False

    # Check lengths match
    if len(group) != len(profit):
        return False

    return True
