"""Machine-generated input-constraint validator for problem 'maximal-rectangle'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: matrix dimensions, element types, and allowed values (0 or 1). Did not enforce semantic guarantees about the existence of rectangles.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(matrix):
    if not isinstance(matrix, list):
        return False
    if not (1 <= len(matrix) <= 200):
        return False
    for row in matrix:
        if not isinstance(row, list):
            return False
        if not (1 <= len(row) <= 200):
            return False
        for val in row:
            if not isinstance(val, int) or isinstance(val, bool):
                return False
            if val not in (0, 1):
                return False
    return True
