"""Machine-generated input-constraint validator for problem 'palindrome-partition-min-cuts'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s):
    if not isinstance(s, str):
        return False
    if not (1 <= len(s) <= 2000):
        return False
    if not all('a' <= c <= 'z' for c in s):
        return False
    return True
