"""Machine-generated input-constraint validator for problem 'super-pow'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: types, ranges, list length, digit values, and no leading zeros. Skipped semantic guarantees about the result.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(a, b):
    # Check type of a
    if not isinstance(a, int) or isinstance(a, bool):
        return False
    # Check range of a
    if not (1 <= a <= 2**31 - 1):
        return False
    
    # Check type of b
    if not isinstance(b, list):
        return False
    # Check length of b
    if not (1 <= len(b) <= 2000):
        return False
    
    # Check elements of b
    for digit in b:
        if not isinstance(digit, int) or isinstance(digit, bool):
            return False
        if not (0 <= digit <= 9):
            return False
    
    # Check no leading zero (unless the number is just 0, but constraint says len >= 1 and digits 0-9)
    # The problem states "no leading zero". Since len(b) >= 1, if len(b) > 1, b[0] cannot be 0.
    # If len(b) == 1, b[0] can be 0? The constraint says "positive integer" for b.
    # A positive integer cannot be 0. So b cannot represent 0.
    # If b = [0], it represents 0, which is not positive. So b[0] cannot be 0 if len(b) == 1 either?
    # Wait, "positive integer" usually means > 0. 
    # If b = [0], value is 0. Not positive.
    # If b = [1, 0], value is 10. Positive.
    # If b = [0, 1], leading zero. Invalid.
    # So b[0] must not be 0.
    if b[0] == 0:
        return False
        
    return True
