"""Machine-generated input-constraint validator for problem 'maximum-side-length-of-a-square-with-sum-less-than-or-equal-to-threshold'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: matrix dimensions, element ranges, threshold range, and types. No semantic guarantees were skipped as none were present in the constraints section.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(mat, threshold):
    # Check mat is a list
    if not isinstance(mat, list):
        return False
    
    # Check threshold is an integer (not bool)
    if not isinstance(threshold, int) or isinstance(threshold, bool):
        return False
    
    # Check threshold range
    if not (0 <= threshold <= 10**5):
        return False
    
    # Check mat dimensions and content
    m = len(mat)
    if not (1 <= m <= 300):
        return False
    
    n = None
    for row in mat:
        if not isinstance(row, list):
            return False
        if n is None:
            n = len(row)
            if not (1 <= n <= 300):
                return False
        else:
            if len(row) != n:
                return False
        
        for val in row:
            if not isinstance(val, int) or isinstance(val, bool):
                return False
            if not (0 <= val <= 10**4):
                return False
    
    return True
