"""Machine-generated input-constraint validator for problem 'rabbits-in-forest'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(answers):
    if not isinstance(answers, list):
        return False
    if not (0 <= len(answers) <= 1000):
        return False
    for x in answers:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (0 <= x <= 999):
            return False
    return True
