"""Machine-generated input-constraint validator for problem 'sentence-similarity'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length constraints and type constraints. Did not enforce semantic guarantees like transitivity or similarity, as those are problem logic, not input bounds.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(sentence1, sentence2, pairs):
    # Check sentence1
    if not isinstance(sentence1, list):
        return False
    if not (0 <= len(sentence1) <= 1000):
        return False
    for word in sentence1:
        if not isinstance(word, str):
            return False

    # Check sentence2
    if not isinstance(sentence2, list):
        return False
    if not (0 <= len(sentence2) <= 1000):
        return False
    for word in sentence2:
        if not isinstance(word, str):
            return False

    # Check pairs
    if not isinstance(pairs, list):
        return False
    if not (0 <= len(pairs) <= 2000):
        return False
    for pair in pairs:
        if not isinstance(pair, list):
            return False
        if len(pair) != 2:
            return False
        for word in pair:
            if not isinstance(word, str):
                return False

    return True
