"""Machine-generated input-constraint validator for problem 'numbers-with-same-consecutive-differences'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(n, k):
    if not isinstance(n, int) or isinstance(n, bool):
        return False
    if not isinstance(k, int) or isinstance(k, bool):
        return False
    if not (2 <= n <= 9):
        return False
    if not (0 <= k <= 9):
        return False
    return True
