"""Machine-generated input-constraint validator for problem 'powx-n'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced type checks for float/int excluding bools, range for x, and 32-bit signed integer range for n.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(x, n):
    # Check x is a float (and not a bool)
    if isinstance(x, bool) or not isinstance(x, float):
        return False
    # Check n is an int (and not a bool)
    if isinstance(n, bool) or not isinstance(n, int):
        return False
    
    # Check constraint: -100 < x < 100
    if not (-100 < x < 100):
        return False
    
    # Check constraint: n is a 32-bit signed integer
    # Range: -2^31 to 2^31 - 1
    if not (-2**31 <= n <= 2**31 - 1):
        return False
        
    return True
