"""Machine-generated input-constraint validator for problem 'recover-bst'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Interpreted 'root' as a level-order list based on the description 'encoded as a level-order list', despite the type hint saying TreeNode. Enforced node count [2, 1000] and distinct integer values. Did not enforce BST property or 'exactly two swapped' as these are semantic guarantees.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root):
    # The problem states the input is a TreeNode, but the examples and format description
    # imply the input might be provided as a level-order list (LeetCode style).
    # However, the parameter declaration says 'root: TreeNode'.
    # Usually, in these validation tasks, if the parameter is declared as a specific object type
    # like TreeNode, we assume the input is that object. But the prompt says "encoded as a level-order list".
    # Let's look closely at the parameter declaration: "root: TreeNode (a binary tree, encoded as a level-order list with null for absent children)".
    # This is contradictory. A TreeNode is an object. A level-order list is a list.
    # Given the previous examples (nums, s), the input is usually the raw data structure.
    # If the input is a list, we validate the list. If it's a TreeNode object, we validate the object.
    # The prompt says "encoded as a level-order list". This strongly suggests the input `root` is actually a list.
    # Let's assume `root` is a list representing the tree.
    
    if not isinstance(root, list):
        return False
    
    # Count nodes (non-null values)
    nodes = [x for x in root if x is not None]
    n = len(nodes)
    
    # Constraint: Number of nodes is in [2, 1000]
    if not (2 <= n <= 1000):
        return False
        
    # Constraint: All node values are distinct integers
    # We need to check that all non-null values are integers and distinct.
    # Also, bools are not allowed as integers.
    seen = set()
    for x in nodes:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if x in seen:
            return False
        seen.add(x)
        
    return True
