"""Machine-generated input-constraint validator for problem 'xor-queries-of-a-subarray'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: arr length, positive integers, queries structure, and L/R bounds relative to arr length.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(arr, queries):
    # Validate arr
    if not isinstance(arr, list):
        return False
    if not (1 <= len(arr) <= 3 * 10**4):
        return False
    for x in arr:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if x <= 0:  # "positive integers"
            return False

    # Validate queries
    if not isinstance(queries, list):
        return False
    for q in queries:
        if not isinstance(q, list):
            return False
        if len(q) != 2:
            return False
        L, R = q
        if not isinstance(L, int) or isinstance(L, bool):
            return False
        if not isinstance(R, int) or isinstance(R, bool):
            return False
        if not (0 <= L <= R < len(arr)):
            return False

    return True
