"""Machine-generated input-constraint validator for problem 'maximum-length-of-a-concatenated-string-with-unique-characters'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(arr):
    if not isinstance(arr, list):
        return False
    if not (1 <= len(arr) <= 16):
        return False
    for s in arr:
        if not isinstance(s, str):
            return False
        if not (1 <= len(s) <= 26):
            return False
        if not all('a' <= c <= 'z' for c in s):
            return False
    return True
