"""Machine-generated input-constraint validator for problem 'min-cost-climbing-stairs'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(cost):
    if not isinstance(cost, list):
        return False
    if not (2 <= len(cost) <= 1000):
        return False
    for x in cost:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (0 <= x <= 999):
            return False
    return True
