"""Machine-generated input-constraint validator for problem 'max-stack'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'pop/top/peekMax/popMax are only called on a non-empty stack' as it is a semantic guarantee about the sequence of operations relative to state, not a static constraint on the input structure.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(operations):
    if not isinstance(operations, list):
        return False
    if not (1 <= len(operations) <= 10**4):
        return False
    
    valid_commands = {"push", "pop", "top", "peekMax", "popMax"}
    
    for op in operations:
        if not isinstance(op, list):
            return False
        if len(op) == 0:
            return False
        
        cmd = op[0]
        if not isinstance(cmd, str):
            return False
        if cmd not in valid_commands:
            return False
            
        if cmd == "push":
            if len(op) != 2:
                return False
            val = op[1]
            if isinstance(val, bool) or not isinstance(val, int):
                return False
        else:
            # pop, top, peekMax, popMax take no arguments
            if len(op) != 1:
                return False
                
    return True
