"""Machine-generated input-constraint validator for problem 'longest-zigzag-path-in-a-binary-tree'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Assumed 'root' is a TreeNode object based on the declared type, despite the confusing 'encoded as list' description which likely refers to the example format. Validated node count via traversal and integer types for values.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root):
    # The problem statement implies the input is a TreeNode object.
    # However, the examples show level-order lists. The prompt says:
    # "root: TreeNode (a binary tree, encoded as a level-order list with null for absent children)"
    # This is contradictory. Usually, in these validation tasks, if the parameter type is declared as TreeNode,
    # we expect a TreeNode object. But the description says "encoded as a level-order list".
    # Let's look at the parameter declaration again: "root: TreeNode".
    # And the description: "your function works with TreeNode objects... Trees are shown below in LeetCode level-order array form".
    # This usually means the *input to the problem* is a TreeNode object, but the *examples* are shown as arrays for readability.
    # However, the prompt explicitly says: "root: TreeNode (a binary tree, encoded as a level-order list with null for absent children)".
    # This phrasing suggests the variable `root` might actually be the list representation, OR it's a TreeNode object.
    # Given the standard LeetCode format, `root` is a TreeNode object.
    # BUT, looking at previous examples in this dataset style, if it says "encoded as...", it often means the raw input IS that encoding.
    # Let's re-read carefully: "The function's parameters (name and declared type) are: - root: TreeNode (a binary tree, encoded as a level-order list with null for absent children)".
    # This is a very specific instruction. It says the parameter `root` is a TreeNode, but then describes it as an encoded list.
    # This is likely a mistake in the prompt's description of the type vs the encoding.
    # If I assume `root` is a TreeNode object, I need to define TreeNode or check for it.
    # If I assume `root` is a list, I check for list.
    # Let's look at the constraint: "1 <= number of nodes <= 5*10^4".
    # If `root` is a TreeNode, counting nodes requires traversal.
    # If `root` is a list, counting nodes is len(root) (minus nulls? or just len?).
    # The constraint says "number of nodes". In a level-order list, nulls are placeholders.
    # Usually, "number of nodes" refers to the actual TreeNode instances.
    # Let's assume the standard interpretation for these coding problems: The input `root` is a TreeNode object.
    # The text "encoded as a level-order list" is likely describing how the tree is *represented in the problem description/examples*, not the runtime type.
    # HOWEVER, the prompt says "encoded as a level-order list" in the parameter definition.
    # Let's look at the previous example with `s`. It was a string.
    # Let's look at the `nums` example. It was a list.
    # If the prompt meant `root` is a list, it would likely say `root: List[int]`.
    # It says `root: TreeNode`.
    # I will validate that `root` is a TreeNode-like object (has val, left, right) or is None.
    # But wait, if I don't have the TreeNode class defined, I can't check `isinstance(root, TreeNode)`.
    # I can check for attributes.
    # Also, I need to count the nodes to check the constraint 1 <= nodes <= 5*10^4.
    # Counting nodes in a tree requires traversal.
    # Is traversal allowed? "Enforce only constraints that are checkable from the raw input alone".
    # Traversing the tree to count nodes is checkable from the raw input.
    # So I will:
    # 1. Check if root is None. If so, node count is 0. Constraint 1 <= nodes fails. Return False.
    # 2. Check if root has attributes 'val', 'left', 'right'.
    # 3. Traverse the tree to count nodes.
    # 4. Check if count is within [1, 50000].
    # 5. Check if node values are integers (and not bools).
    
    # Helper to count nodes and validate structure
    def check_node(node):
        if node is None:
            return 0
        # Check if it looks like a TreeNode
        if not hasattr(node, 'val') or not hasattr(node, 'left') or not hasattr(node, 'right'):
            return -1 # Invalid structure
        
        # Check value type
        val = node.val
        if isinstance(val, bool) or not isinstance(val, int):
            return -1 # Invalid value type
            
        left_count = check_node(node.left)
        if left_count == -1:
            return -1
        right_count = check_node(node.right)
        if right_count == -1:
            return -1
            
        return 1 + left_count + right_count

    if root is None:
        return False # Constraint: 1 <= number of nodes
        
    count = check_node(root)
    if count == -1:
        return False
        
    if not (1 <= count <= 5 * 10**4):
        return False
        
    return True
