"""Machine-generated input-constraint validator for problem 'super-egg-drop'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(K, N):
    if not isinstance(K, int) or isinstance(K, bool):
        return False
    if not isinstance(N, int) or isinstance(N, bool):
        return False
    if not (1 <= K <= 100):
        return False
    if not (1 <= N <= 10**4):
        return False
    return True
