"""Machine-generated input-constraint validator for problem 'zuma-game'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(board, hand):
    if not isinstance(board, str) or not isinstance(hand, str):
        return False
    if not (1 <= len(board) <= 16):
        return False
    if not (1 <= len(hand) <= 5):
        return False
    allowed_colors = set("RYBGW")
    if not all(c in allowed_colors for c in board):
        return False
    if not all(c in allowed_colors for c in hand):
        return False
    return True
