"""Machine-generated input-constraint validator for problem 'jump-game-iii'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(arr, start):
    if not isinstance(arr, list):
        return False
    if not (1 <= len(arr) <= 5 * 10**4):
        return False
    for x in arr:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (0 <= x < len(arr)):
            return False
    if not isinstance(start, int) or isinstance(start, bool):
        return False
    if not (0 <= start < len(arr)):
        return False
    return True
