"""Machine-generated input-constraint validator for problem 'single-element-in-a-sorted-array'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'array is sorted' and 'every value appears exactly twice except one' as these are semantic guarantees/structural properties that require solving or deep inspection, not simple input bounds.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums):
    if not isinstance(nums, list):
        return False
    if not (1 <= len(nums) <= 10**5):
        return False
    if len(nums) % 2 == 0:
        return False
    for x in nums:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (0 <= x <= 10**5):
            return False
    return True
