"""Machine-generated input-constraint validator for problem 'reverse-substrings-between-each-pair-of-parentheses'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length bounds, allowed character set, and balanced parentheses structure. The requirement that the output contains no brackets is a property of the solution, not the input.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s):
    if not isinstance(s, str):
        return False
    if not (0 <= len(s) <= 2000):
        return False
    allowed = set("abcdefghijklmnopqrstuvwxyz()")
    if not all(c in allowed for c in s):
        return False
    # Check balanced parentheses
    balance = 0
    for c in s:
        if c == '(':
            balance += 1
        elif c == ')':
            balance -= 1
        if balance < 0:
            return False
    if balance != 0:
        return False
    return True
