"""Machine-generated input-constraint validator for problem 'find-elements-in-a-contaminated-binary-tree'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced list types, element values (-1/None for root, int range for queries), node count, and tree height derived from level-order indices. Did not enforce semantic tree structure validity (e.g. parent-child consistency) as it's implied by the 'level-order array' format and 'shape' description, but height and node count are explicit constraints.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root, queries):
    # Validate root: must be a list
    if not isinstance(root, list):
        return False
    
    # Validate queries: must be a list
    if not isinstance(queries, list):
        return False
    
    # Validate root elements: must be -1 or None
    for item in root:
        if item is not None and item != -1:
            return False
    
    # Validate queries elements: must be integers (not bools) in range [0, 10^6]
    for q in queries:
        if isinstance(q, bool) or not isinstance(q, int):
            return False
        if not (0 <= q <= 10**6):
            return False
            
    # Validate tree constraints:
    # 1. Number of nodes (non-None items) between 1 and 10^4
    num_nodes = sum(1 for x in root if x is not None)
    if not (1 <= num_nodes <= 10**4):
        return False
        
    # 2. Tree height <= 20
    # Calculate height based on the level-order structure
    # The height of a tree represented in level-order array can be derived from
    # the index of the last non-None element.
    # Index i corresponds to depth floor(log2(i+1)).
    # Max depth is height - 1. So height <= 20 means max depth <= 19.
    # Max index for depth 19 is 2^20 - 2 = 1048574.
    # However, we must ensure the structure is valid for a binary tree.
    # A simple check: if the last non-None element is at index i,
    # the height is floor(log2(i+1)) + 1.
    
    if num_nodes == 0:
        return False # Already handled by 1 <= num_nodes
        
    last_idx = -1
    for i, item in enumerate(root):
        if item is not None:
            last_idx = i
            
    if last_idx == -1:
        return False # Should be caught by num_nodes >= 1
        
    import math
    height = math.floor(math.log2(last_idx + 1)) + 1
    if height > 20:
        return False
        
    return True
