"""Machine-generated input-constraint validator for problem 'reachable-nodes-in-subdivided-graph'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced. No semantic guarantees were skipped as none were present in the constraints section.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(edges, maxMoves, n):
    # Validate n
    if not isinstance(n, int) or isinstance(n, bool):
        return False
    if not (1 <= n <= 3000):
        return False

    # Validate maxMoves
    if not isinstance(maxMoves, int) or isinstance(maxMoves, bool):
        return False
    if not (0 <= maxMoves <= 10**9):
        return False

    # Validate edges
    if not isinstance(edges, list):
        return False
    if not (0 <= len(edges) <= 10**4):
        return False

    for edge in edges:
        if not isinstance(edge, list):
            return False
        if len(edge) != 3:
            return False
        u, v, cnt = edge
        # Validate u, v, cnt are integers (not bools)
        for val in [u, v, cnt]:
            if not isinstance(val, int) or isinstance(val, bool):
                return False
        # Validate ranges for u, v
        if not (0 <= u < n):
            return False
        if not (0 <= v < n):
            return False
        # Validate range for cnt
        if not (0 <= cnt <= 10**4):
            return False

    return True
