"""Machine-generated input-constraint validator for problem 'number-of-ways-where-square-of-number-is-equal-to-product-of-two-numbers'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums1, nums2):
    if not isinstance(nums1, list) or not isinstance(nums2, list):
        return False
    if not (1 <= len(nums1) <= 1000) or not (1 <= len(nums2) <= 1000):
        return False
    for x in nums1:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (1 <= x <= 10**5):
            return False
    for x in nums2:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (1 <= x <= 10**5):
            return False
    return True
