"""Machine-generated input-constraint validator for problem 'unique-paths-ii'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: dimensions 1-100, rectangular shape, elements are 0 or 1. Skipped 'answer <= 2*10^9' as it is a guarantee about the output, not a constraint on the input.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(obstacleGrid):
    if not isinstance(obstacleGrid, list):
        return False
    
    m = len(obstacleGrid)
    if not (1 <= m <= 100):
        return False
    
    if m == 0:
        return False
        
    n = len(obstacleGrid[0])
    if not (1 <= n <= 100):
        return False
    
    for row in obstacleGrid:
        if not isinstance(row, list):
            return False
        if len(row) != n:
            return False
        for val in row:
            if not isinstance(val, int) or isinstance(val, bool):
                return False
            if val not in (0, 1):
                return False
                
    return True
