"""Machine-generated input-constraint validator for problem 'replace-the-substring-for-balanced-string'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s):
    if not isinstance(s, str):
        return False
    if not (1 <= len(s) <= 10**5):
        return False
    if len(s) % 4 != 0:
        return False
    allowed = set('QWER')
    if not all(c in allowed for c in s):
        return False
    return True
