"""Machine-generated input-constraint validator for problem 'minimum-path-sum-in-grid'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced rectangular shape, dimensions 1-200, and element range 0-1000. No semantic guarantees to skip.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(grid):
    if not isinstance(grid, list):
        return False
    if len(grid) < 1:
        return False
    m = len(grid)
    if not (1 <= m <= 200):
        return False
    n = len(grid[0])
    if not (1 <= n <= 200):
        return False
    for row in grid:
        if not isinstance(row, list):
            return False
        if len(row) != n:
            return False
        for val in row:
            if isinstance(val, bool) or not isinstance(val, int):
                return False
            if not (0 <= val <= 1000):
                return False
    return True
