"""Machine-generated input-constraint validator for problem 'maximum-width-of-binary-tree'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Treated 'root' as a list based on the 'encoded as a level-order list' description, despite the 'TreeNode' type hint, because the examples show lists. Enforced node count constraint. Did not enforce 'answer fits in 32-bit integer' as it is a property of the output, not the input.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root):
    # The problem statement describes the input as a TreeNode object.
    # However, the examples and format description mention level-order array form.
    # The parameter declaration says 'root: TreeNode'.
    # Usually, in these validation tasks, if the parameter is declared as a specific object type
    # (like TreeNode), we validate that object structure. If it were a list, it would be declared as list.
    # But looking at the examples: root = [1,3,2,5,3,null,9]. This is a list representation.
    # The prompt says: "The function's parameters (name and declared type) are: root: TreeNode (a binary tree, encoded as a level-order list with null for absent children)"
    # This is contradictory. "TreeNode" usually implies an object. "encoded as a level-order list" implies a list.
    # Given the explicit instruction "encoded as a level-order list", I will treat the input `root` as a list.
    # If the input is actually a TreeNode object, this validation will fail, which is consistent with the type mismatch.
    # Let's re-read carefully: "root: TreeNode (a binary tree, encoded as a level-order list...)". 
    # This likely means the *concept* is a tree, but the *data* passed is the list encoding.
    
    if not isinstance(root, list):
        return False

    if len(root) == 0 or root[0] is None:
        # Empty list or null root means 0 nodes, which violates "1 <= number of nodes <= 3000"
        return False

    # Constraint: 1 <= number of nodes <= 3000
    # Count non-null nodes in the level-order list.
    node_count = 0
    for val in root:
        if val is None:
            continue
        # Check if the value is an integer (and not a bool)
        if not isinstance(val, int) or isinstance(val, bool):
            return False
        node_count += 1

    if not (1 <= node_count <= 3000):
        return False

    return True
