"""Machine-generated input-constraint validator for problem 'binary-tree-cameras'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced node count range [1, 1000] and value constraint (all 0). Did not enforce structural guarantees like 'binary tree' beyond basic traversal validity.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root):
    if root is None:
        return False
    
    # Check if root is a TreeNode-like object (has value, left, right attributes)
    # We assume a standard TreeNode class or dict-like structure.
    # Based on typical LeetCode inputs, it's an object with .val, .left, .right
    # or similar. The prompt says "TreeNode objects (value, left, right)".
    # Let's assume standard attributes: val, left, right.
    
    # Helper to check if a node is valid
    def is_valid_node(node):
        if node is None:
            return True
        # Check if it's a dict or object with expected attributes
        if isinstance(node, dict):
            if 'val' not in node or 'left' not in node or 'right' not in node:
                return False
            if not (isinstance(node['val'], int) and not isinstance(node['val'], bool)):
                return False
            if node['val'] != 0:
                return False
            return is_valid_node(node['left']) and is_valid_node(node['right'])
        else:
            # Assume object with attributes
            if not hasattr(node, 'val') or not hasattr(node, 'left') or not hasattr(node, 'right'):
                return False
            if not (isinstance(node.val, int) and not isinstance(node.val, bool)):
                return False
            if node.val != 0:
                return False
            return is_valid_node(node.left) and is_valid_node(node.right)

    if not is_valid_node(root):
        return False

    # Count nodes
    def count_nodes(node):
        if node is None:
            return 0
        if isinstance(node, dict):
            return 1 + count_nodes(node['left']) + count_nodes(node['right'])
        else:
            return 1 + count_nodes(node.left) + count_nodes(node.right)

    num_nodes = count_nodes(root)
    if not (1 <= num_nodes <= 1000):
        return False

    return True
