"""Machine-generated input-constraint validator for problem 'maximum-profit-of-operating-a-centennial-wheel'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(customers, boardingCost, runningCost):
    if not isinstance(customers, list):
        return False
    if not (1 <= len(customers) <= 10**5):
        return False
    for x in customers:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (0 <= x <= 50):
            return False
    if not isinstance(boardingCost, int) or isinstance(boardingCost, bool):
        return False
    if not (1 <= boardingCost <= 100):
        return False
    if not isinstance(runningCost, int) or isinstance(runningCost, bool):
        return False
    if not (1 <= runningCost <= 100):
        return False
    return True
