"""Machine-generated input-constraint validator for problem 'number-of-atoms'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length bounds and allowed character set. Did not enforce semantic validity of the formula structure (e.g., balanced parentheses, correct element syntax) as that requires parsing/solving logic beyond raw input constraints.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(formula):
    if not isinstance(formula, str):
        return False
    if not (1 <= len(formula) <= 1000):
        return False
    allowed = set("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz()0123456789")
    if not all(c in allowed for c in formula):
        return False
    return True
