"""Machine-generated input-constraint validator for problem 'tag-validator'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced the explicit constraint on allowed characters. Skipped structural validity checks (matching tags, CDATA parsing) as they are semantic guarantees/solution logic rather than raw input bounds.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(code):
    if not isinstance(code, str):
        return False
    allowed = set("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789<>/![] ")
    if not all(c in allowed for c in code):
        return False
    return True
