"""Machine-generated input-constraint validator for problem 'making-file-names-unique'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(names):
    if not isinstance(names, list):
        return False
    if not (1 <= len(names) <= 5 * 10**4):
        return False
    for name in names:
        if not isinstance(name, str):
            return False
        if not (1 <= len(name) <= 20):
            return False
        for char in name:
            if not (char.islower() or char.isdigit() or char in '()'):
                return False
    return True
