"""Machine-generated input-constraint validator for problem 'two-sum'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'Exactly one valid answer exists' as it is a semantic guarantee about the solution space, not a checkable property of the raw input bounds.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums, target):
    if not isinstance(nums, list):
        return False
    if not (2 <= len(nums) <= 10**4):
        return False
    for x in nums:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (-10**9 <= x <= 10**9):
            return False
    if isinstance(target, bool) or not isinstance(target, int):
        return False
    if not (-10**9 <= target <= 10**9):
        return False
    return True
