"""Machine-generated input-constraint validator for problem 'sum-root-to-leaf-numbers'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'depth of the tree will not exceed 10' as it requires parsing the tree structure, which is a semantic property rather than a simple raw input bound check on the list elements themselves.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root):
    if not isinstance(root, list):
        return False
    if not (1 <= len(root) <= 1000):
        return False
    for x in root:
        if x is None:
            continue
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (0 <= x <= 9):
            return False
    return True
