"""Machine-generated input-constraint validator for problem 'number-of-music-playlists'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable bounds on the input parameters.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(n, goal, k):
    # Check types: must be int, not bool
    for val in (n, goal, k):
        if not isinstance(val, int) or isinstance(val, bool):
            return False
    
    # Check constraints: 0 <= k < n <= goal <= 100
    if not (0 <= k < n <= goal <= 100):
        return False
    
    return True
