"""Machine-generated input-constraint validator for problem 'binary-tree-maximum-path-sum'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced node count and value range constraints by traversing the TreeNode structure. Skipped semantic guarantees about path sums.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root):
    # The problem statement says the function works with TreeNode objects.
    # However, the examples and constraints imply a structure that can be validated.
    # Since the input parameter is named 'root' and described as a TreeNode,
    # we must handle the case where the input is actually a TreeNode object
    # or potentially a list representation if the testing harness converts it.
    # But the prompt says: "The function's parameters (name and declared type) are: root: TreeNode".
    # And "Format: your function works with TreeNode objects".
    # So we assume the input is a TreeNode object or None.
    
    # We need to define a basic check for TreeNode structure.
    # Since we cannot import TreeNode, we assume it's a custom object with 'val', 'left', 'right' attributes.
    # Or, more likely in these validation contexts, the input might be passed as a list if the harness
    # hasn't converted it, but the signature says TreeNode. Let's look at the constraints.
    # Constraints: 1 <= number of nodes <= 3 * 10^4. -1000 <= node.value <= 1000.
    
    # If root is None, it's an empty tree. But constraint says 1 <= number of nodes.
    # So root cannot be None.
    
    if root is None:
        return False
        
    # We need to traverse the tree to count nodes and check values.
    # We assume TreeNode has attributes: val, left, right.
    # We must be robust: check if attributes exist.
    
    try:
        # Check if root has the expected attributes
        if not hasattr(root, 'val') or not hasattr(root, 'left') or not hasattr(root, 'right'):
            return False
            
        # BFS to traverse and validate
        queue = [root]
        count = 0
        
        while queue:
            node = queue.pop(0)
            
            # Check if node is None (should not happen if we only add non-None nodes, 
            # but children can be None)
            if node is None:
                continue
                
            count += 1
            
            # Check value type and range
            val = node.val
            if isinstance(val, bool) or not isinstance(val, int):
                return False
            if not (-1000 <= val <= 1000):
                return False
                
            # Add children to queue if they are not None
            # We need to check if left/right are TreeNode objects or None
            left = node.left
            right = node.right
            
            if left is not None:
                if not hasattr(left, 'val') or not hasattr(left, 'left') or not hasattr(left, 'right'):
                    return False
                queue.append(left)
                
            if right is not None:
                if not hasattr(right, 'val') or not hasattr(right, 'left') or not hasattr(right, 'right'):
                    return False
                queue.append(right)
                
        # Check node count constraint
        if not (1 <= count <= 3 * 10**4):
            return False
            
        return True
        
    except Exception:
        return False
