"""Machine-generated input-constraint validator for problem 'subset-sum-feasibility'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums, target):
    if not isinstance(nums, list):
        return False
    if not isinstance(target, int) or isinstance(target, bool):
        return False
    if not (0 <= len(nums) <= 200):
        return False
    if not (0 <= target <= 2 * 10**4):
        return False
    for x in nums:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (0 <= x <= 1000):
            return False
    return True
