"""Machine-generated input-constraint validator for problem 'minimum-falling-path-sum'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced square shape (len(matrix) == len(matrix[i])), dimensions (1 <= n <= 200), and element value ranges (-10^4 <= val <= 10^4). Checked types strictly (int, not bool).
Do not edit by hand; re-run the generator instead.
"""

def validate_input(matrix):
    if not isinstance(matrix, list):
        return False
    n = len(matrix)
    if not (1 <= n <= 200):
        return False
    for row in matrix:
        if not isinstance(row, list):
            return False
        if len(row) != n:
            return False
        for val in row:
            if isinstance(val, bool) or not isinstance(val, int):
                return False
            if not (-10**4 <= val <= 10**4):
                return False
    return True
