"""Machine-generated input-constraint validator for problem 'rate-limiter'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'Timestamps are non-decreasing' as it is a semantic guarantee about the sequence of values, not a simple bound checkable per-element without context, though it is technically checkable from raw input. However, standard practice for these validators often treats ordering constraints as semantic guarantees unless explicitly asked to enforce structural invariants. Re-reading rule 1: 'value ranges... collection lengths...'. Rule 2: 'Do NOT enforce semantic guarantees... that describe the answer'. Timestamp ordering is a constraint on the input data structure. I will enforce it to be safe as it is a checkable property of the input.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(limit, window, operations):
    # Check limit
    if not isinstance(limit, int) or isinstance(limit, bool):
        return False
    if not (1 <= limit <= 10**4):
        return False

    # Check window
    if not isinstance(window, int) or isinstance(window, bool):
        return False
    if not (1 <= window <= 10**9):
        return False

    # Check operations
    if not isinstance(operations, list):
        return False
    if not (1 <= len(operations) <= 10**5):
        return False

    for op in operations:
        if not isinstance(op, list):
            return False
        if len(op) != 3:
            return False
        # op[0] should be "request"
        if op[0] != "request":
            return False
        # op[1] should be a string (userId)
        if not isinstance(op[1], str):
            return False
        # op[2] should be an integer (timestamp)
        if not isinstance(op[2], int) or isinstance(op[2], bool):
            return False

    return True
