"""Machine-generated input-constraint validator for design problem 'rate-limiter'.

Generated by scripts/generate_class_validators.py (deterministic, from the class
block in meta.json — no LLM). `validate_input(operations, args)` returns True iff
the method-call sequence is well-formed for the `RateLimiter` class: aligned
operations/args lists, the constructor exactly once at the front, every later op a
declared method, and each arg list matching its op's arity and per-arg type.
Structure + type, plus the value bounds from the statement's Constraints
(hand-added at the bottom of `validate_input`; re-running the generator with
--force regenerates the structural part and drops them).
"""


# op-name -> list of (base_type, list_dims) for each positional argument.
_SIG = {
    'RateLimiter': [('int', 0), ('int', 0)],
    'request': [('string', 0), ('int', 0)],
}
_CTOR = 'RateLimiter'


def _scalar_ok(v, base):
    if base == "int":
        return isinstance(v, int) and not isinstance(v, bool)
    if base in ("float", "num"):
        return isinstance(v, (int, float)) and not isinstance(v, bool)
    if base == "bool":
        return isinstance(v, bool)
    if base in ("string", "str", "char"):
        return isinstance(v, str)
    if base in ("TreeNode", "ListNode", "DoublyLinkedList"):
        # Wire form: a level-order / flat value list of ints (None marks a hole),
        # or None / [] for an empty structure.
        if v is None:
            return True
        if not isinstance(v, list):
            return False
        return all(x is None or (isinstance(x, int) and not isinstance(x, bool)) for x in v)
    # Iterator / NestedInteger / object / any / unknown: opaque — don't reject.
    return True


def _type_ok(v, base, dims):
    if dims == 0:
        return _scalar_ok(v, base)
    if not isinstance(v, list):
        return False
    return all(_type_ok(e, base, dims - 1) for e in v)


def validate_input(operations, args):
    if not isinstance(operations, list) or not isinstance(args, list):
        return False
    if len(operations) != len(args):
        return False
    if not operations:
        return False
    if operations[0] != _CTOR:
        return False
    for op in operations[1:]:
        if op == _CTOR or op not in _SIG:
            return False
    for op, a in zip(operations, args):
        sig = _SIG.get(op)
        if sig is None:
            return False
        if not isinstance(a, list) or len(a) != len(sig):
            return False
        for val, (base, dims) in zip(a, sig):
            if not _type_ok(val, base, dims):
                return False
    # --- value bounds from the statement's Constraints ---
    # 1 <= limit <= 10**4, 1 <= window <= 10**9; at most 10**5 calls to request;
    # 0 <= timestamp <= 10**9, non-decreasing across calls.
    limit, window = args[0]
    if not (1 <= limit <= 10**4) or not (1 <= window <= 10**9):
        return False
    if len(operations) - 1 > 10**5:
        return False
    last = -1
    for _op, a in zip(operations[1:], args[1:]):
        if not a[0]:  # userId
            return False
        if not (0 <= a[1] <= 10**9) or a[1] < last:
            return False
        last = a[1]
    return True
