"""Machine-generated input-constraint validator for problem 'longest-word-in-dictionary-through-deleting'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length bounds and lowercase letter constraints for both s and elements of d. No semantic guarantees to skip.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s, d):
    if not isinstance(s, str):
        return False
    if not (1 <= len(s) <= 1000):
        return False
    if not all(c.islower() for c in s):
        return False
    
    if not isinstance(d, list):
        return False
    if not (1 <= len(d) <= 1000):
        return False
    for word in d:
        if not isinstance(word, str):
            return False
        if not all(c.islower() for c in word):
            return False
    
    return True
