"""Machine-generated input-constraint validator for problem 'number-of-dice-rolls-with-target-sum'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(d, f, target):
    if not isinstance(d, int) or isinstance(d, bool):
        return False
    if not isinstance(f, int) or isinstance(f, bool):
        return False
    if not isinstance(target, int) or isinstance(target, bool):
        return False
    if not (1 <= d <= 30):
        return False
    if not (1 <= f <= 30):
        return False
    if not (1 <= target <= 1000):
        return False
    return True
