"""Machine-generated input-constraint validator for problem 'minimum-spanning-tree-cost'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'the graph is connected' as it is a semantic guarantee about the graph structure, not a simple checkable bound on individual input values.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(n, edges):
    # Check n type and range
    if not isinstance(n, int) or isinstance(n, bool):
        return False
    if not (1 <= n <= 1000):
        return False
    
    # Check edges type
    if not isinstance(edges, list):
        return False
    
    # Check each edge
    for edge in edges:
        if not isinstance(edge, list):
            return False
        if len(edge) != 3:
            return False
        u, v, w = edge
        
        # Check u, v, w types (int, not bool)
        if not isinstance(u, int) or isinstance(u, bool):
            return False
        if not isinstance(v, int) or isinstance(v, bool):
            return False
        if not isinstance(w, int) or isinstance(w, bool):
            return False
            
        # Check u, v range
        if not (0 <= u < n):
            return False
        if not (0 <= v < n):
            return False
            
        # Check w range
        if not (1 <= w <= 10**6):
            return False
            
    return True
