"""Machine-generated input-constraint validator for problem 'pour-water'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(heights, V, K):
    if not isinstance(heights, list):
        return False
    if not (1 <= len(heights) <= 100):
        return False
    for h in heights:
        if not isinstance(h, int) or isinstance(h, bool):
            return False
        if not (0 <= h <= 99):
            return False
    if not isinstance(V, int) or isinstance(V, bool):
        return False
    if not (0 <= V <= 2000):
        return False
    if not isinstance(K, int) or isinstance(K, bool):
        return False
    if not (0 <= K < len(heights)):
        return False
    return True
