"""Machine-generated input-constraint validator for problem 'min-window-subsequence'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s, t):
    if not isinstance(s, str) or isinstance(s, bool):
        return False
    if not isinstance(t, str) or isinstance(t, bool):
        return False
    if not (1 <= len(s) <= 2 * 10**4):
        return False
    if not (1 <= len(t) <= 100):
        return False
    return True
