"""Machine-generated input-constraint validator for problem 'maximum-probability-path'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: n range, edges structure and node ranges, succProb length match and value ranges, start/end ranges. Did not enforce semantic guarantees like reachability or unique paths.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(n, edges, succProb, start, end):
    # Check n
    if not isinstance(n, int) or isinstance(n, bool):
        return False
    if not (2 <= n <= 10**4):
        return False

    # Check edges
    if not isinstance(edges, list):
        return False
    for edge in edges:
        if not isinstance(edge, list):
            return False
        if len(edge) != 2:
            return False
        for node in edge:
            if not isinstance(node, int) or isinstance(node, bool):
                return False
            if not (0 <= node < n):
                return False

    # Check succProb
    if not isinstance(succProb, list):
        return False
    if len(succProb) != len(edges):
        return False
    for p in succProb:
        if not isinstance(p, (int, float)) or isinstance(p, bool):
            return False
        if not (0 <= p <= 1):
            return False

    # Check start
    if not isinstance(start, int) or isinstance(start, bool):
        return False
    if not (0 <= start < n):
        return False

    # Check end
    if not isinstance(end, int) or isinstance(end, bool):
        return False
    if not (0 <= end < n):
        return False

    return True
