"""Machine-generated input-constraint validator for problem 'recover-a-tree-from-preorder-traversal'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: string type, non-empty, valid format, node count 1-1000, node values 1-10^9. Did not enforce semantic tree validity as that requires solving the problem.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(traversal):
    if not isinstance(traversal, str):
        return False
    if len(traversal) == 0:
        return False
    
    # Parse the string to extract node values and check constraints
    # The format is: value-dashes-value-dashes...
    # We need to verify:
    # 1. The string is well-formed (starts with a digit, dashes separate levels)
    # 2. Number of nodes is between 1 and 1000
    # 3. Each node value is between 1 and 10^9
    
    import re
    
    # Split by '-' but be careful: dashes are separators for depth, not part of values
    # Actually, the format is: value + (depth * '-') + value + ...
    # Let's parse it manually to be safe and robust
    
    nodes = []
    i = 0
    n = len(traversal)
    
    while i < n:
        # Parse the number
        if not traversal[i].isdigit():
            return False
        
        j = i
        while j < n and traversal[j].isdigit():
            j += 1
        
        if j == i:  # No digits found
            return False
            
        val_str = traversal[i:j]
        val = int(val_str)
        
        # Check value constraint
        if not (1 <= val <= 10**9):
            return False
        
        nodes.append(val)
        i = j
        
        # Parse the dashes (if any)
        if i < n:
            if traversal[i] != '-':
                return False
            while i < n and traversal[i] == '-':
                i += 1
    
    # Check number of nodes constraint
    if not (1 <= len(nodes) <= 1000):
        return False
        
    return True
