"""Machine-generated input-constraint validator for problem 'unique-paths'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'The answer is guaranteed to be at most 2 * 10^9' as it is a guarantee about the output, not a checkable constraint on the raw input.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(m, n):
    if not isinstance(m, int) or isinstance(m, bool):
        return False
    if not isinstance(n, int) or isinstance(n, bool):
        return False
    if not (1 <= m <= 100):
        return False
    if not (1 <= n <= 100):
        return False
    return True
