"""Machine-generated input-constraint validator for problem 'minimum-number-of-days-to-make-m-bouquets'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(bloomDay, m, k):
    if not isinstance(bloomDay, list):
        return False
    if not (1 <= len(bloomDay) <= 10**5):
        return False
    for x in bloomDay:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (1 <= x <= 10**9):
            return False
    if not isinstance(m, int) or isinstance(m, bool):
        return False
    if not (1 <= m <= 10**6):
        return False
    if not isinstance(k, int) or isinstance(k, bool):
        return False
    if not (1 <= k <= len(bloomDay)):
        return False
    return True
