"""Machine-generated input-constraint validator for problem 'payment-ledger-balance'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(transactions):
    if not isinstance(transactions, list):
        return False
    if not (0 <= len(transactions) <= 2 * 10**5):
        return False
    
    for txn in transactions:
        if not isinstance(txn, list):
            return False
        if len(txn) != 3:
            return False
        
        from_acc, to_acc, amount = txn
        
        # Check identifiers are non-empty strings
        if not isinstance(from_acc, str) or len(from_acc) == 0:
            return False
        if not isinstance(to_acc, str) or len(to_acc) == 0:
            return False
            
        # Check amount is an integer (not bool) and fits in signed 64-bit
        if isinstance(amount, bool) or not isinstance(amount, int):
            return False
        if not (-2**63 <= amount <= 2**63 - 1):
            return False
            
    return True
