"""Machine-generated input-constraint validator for problem 'add-one-row-to-tree'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced node count >= 1, d >= 1, and d <= tree_depth + 1. Checked structural integrity of TreeNode objects.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root, v, d):
    # Validate v: must be an integer (not bool)
    if not isinstance(v, int) or isinstance(v, bool):
        return False
    
    # Validate d: must be an integer (not bool) and >= 1
    if not isinstance(d, int) or isinstance(d, bool):
        return False
    if d < 1:
        return False
    
    # Validate root: must be None or a TreeNode-like object
    # We assume TreeNode is a class with 'val', 'left', 'right' attributes.
    # Since we cannot import TreeNode, we check for the presence of these attributes
    # or if it is None. The problem statement says "TreeNode objects".
    # We will perform a structural validation to ensure it's a valid tree structure
    # and count nodes/depth to check constraints.
    
    if root is not None:
        if not hasattr(root, 'val') or not hasattr(root, 'left') or not hasattr(root, 'right'):
            return False
        
        # Traverse the tree to count nodes and find max depth
        # We use a queue for BFS to avoid recursion depth issues and to easily track depth
        queue = [(root, 1)] # (node, current_depth)
        node_count = 0
        max_depth = 0
        visited = set() # To handle potential cycles, though trees shouldn't have them
        
        # Use id() to track visited nodes to prevent infinite loops if malformed
        while queue:
            node, depth = queue.pop(0)
            
            if node is None:
                continue
                
            node_id = id(node)
            if node_id in visited:
                # Cycle detected or malformed structure
                return False
            visited.add(node_id)
            
            node_count += 1
            if depth > max_depth:
                max_depth = depth
            
            # Check if children are valid (None or TreeNode-like)
            left = node.left
            right = node.right
            
            if left is not None:
                if not hasattr(left, 'val') or not hasattr(left, 'left') or not hasattr(left, 'right'):
                    return False
                queue.append((left, depth + 1))
                
            if right is not None:
                if not hasattr(right, 'val') or not hasattr(right, 'left') or not hasattr(right, 'right'):
                    return False
                queue.append((right, depth + 1))
        
        # Constraint: 1 <= number of nodes
        if node_count < 1:
            return False
            
        # Constraint: 1 <= d <= (tree depth) + 1
        if d > max_depth + 1:
            return False
    else:
        # If root is None, number of nodes is 0. Constraint says 1 <= number of nodes.
        return False
        
    return True
