"""Machine-generated input-constraint validator for problem 'summary-ranges'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length, element type/range, uniqueness (via strict ascending sort check), and sorted order. 'Unique' and 'sorted' are checkable structural constraints on the input array.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums):
    if not isinstance(nums, list):
        return False
    if not (0 <= len(nums) <= 20):
        return False
    for x in nums:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (-2**31 <= x <= 2**31 - 1):
            return False
    # Check if sorted in ascending order
    for i in range(len(nums) - 1):
        if nums[i] >= nums[i+1]:
            return False
    return True
