"""Machine-generated input-constraint validator for problem 'regions-cut-by-slashes'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(grid):
    if not isinstance(grid, list):
        return False
    n = len(grid)
    if not (1 <= n <= 30):
        return False
    for row in grid:
        if not isinstance(row, str):
            return False
        if len(row) != n:
            return False
        for char in row:
            if char not in ('/', '\\', ' '):
                return False
    return True
