"""Machine-generated input-constraint validator for problem 'minimum-number-of-steps-to-make-two-strings-anagram'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s, t):
    if not isinstance(s, str) or not isinstance(t, str):
        return False
    if not (1 <= len(s) <= 5 * 10**4):
        return False
    if len(s) != len(t):
        return False
    if not all('a' <= c <= 'z' for c in s):
        return False
    if not all('a' <= c <= 'z' for c in t):
        return False
    return True
