"""Machine-generated input-constraint validator for problem 'search-a-2d-matrix'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem.
Manual addition (2026-07-08): structural constraints for row sorting and
inter-row ordering are now enforced to ensure test-strengthening generates
valid inputs for the binary-search property.
"""

def validate_input(matrix, target):
    if not isinstance(matrix, list):
        return False
    if len(matrix) == 0:
        return False
    m = len(matrix)
    if not (1 <= m <= 100):
        return False
    n = len(matrix[0])
    if not (1 <= n <= 100):
        return False
    for row in matrix:
        if not isinstance(row, list):
            return False
        if len(row) != n:
            return False
        for val in row:
            if isinstance(val, bool) or not isinstance(val, int):
                return False
            if not (-10**4 <= val <= 10**4):
                return False
    if isinstance(target, bool) or not isinstance(target, int):
        return False
    if not (-10**4 <= target <= 10**4):
        return False
    # Structural constraints: rows must be sorted and inter-row ordering must hold.
    for i in range(m):
        for j in range(1, n):
            if matrix[i][j] < matrix[i][j - 1]:
                return False
        if i > 0 and matrix[i][0] <= matrix[i - 1][-1]:
            return False
    return True
