"""Machine-generated input-constraint validator for problem 'subtree-of-another-tree'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced node count ranges and value ranges. Did not enforce semantic tree validity (e.g., if the level-order list represents a valid binary tree structure) as that is often implicit or complex to define strictly without more context, but basic type/value checks are done.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root, subRoot):
    # Helper to validate a single tree structure and values
    def validate_tree(tree_list):
        if not isinstance(tree_list, list):
            return False
        # Check node count constraints based on which tree it is? 
        # The function signature doesn't distinguish, but the problem statement gives 
        # different bounds for root and subRoot. We need to know which is which.
        # However, the validation function receives 'root' and 'subRoot' as args.
        # We can validate them separately.
        
        # Check element types: integers or None
        for item in tree_list:
            if item is not None:
                if isinstance(item, bool) or not isinstance(item, int):
                    return False
                if not (-10**4 <= item <= 10**4):
                    return False
        return True

    # Validate root structure and values
    if not validate_tree(root):
        return False
    
    # Validate subRoot structure and values
    if not validate_tree(subRoot):
        return False

    # Check length constraints
    # "The number of nodes in root is in [1, 2000]"
    # "in subRoot, [1, 1000]"
    # Note: The input is a level-order list. The number of nodes is the count of non-None elements.
    
    root_nodes = sum(1 for x in root if x is not None)
    if not (1 <= root_nodes <= 2000):
        return False
        
    subRoot_nodes = sum(1 for x in subRoot if x is not None)
    if not (1 <= subRoot_nodes <= 1000):
        return False

    return True
