"""Machine-generated input-constraint validator for problem 'swap-adjacent-in-lr-string'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length bounds, equality of lengths, and character set constraints. Did not enforce semantic reachability as it requires solving the problem.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(start, end):
    if not isinstance(start, str) or not isinstance(end, str):
        return False
    if not (1 <= len(start) <= 10**4):
        return False
    if len(start) != len(end):
        return False
    allowed = {'L', 'R', 'X'}
    if not all(c in allowed for c in start):
        return False
    if not all(c in allowed for c in end):
        return False
    return True
