"""Machine-generated input-constraint validator for problem 'pacific-atlantic-water-flow'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced list structure, dimensions 1 <= m, n <= 200, and element range 0 <= h <= 10^5. Did not enforce rectangular shape explicitly beyond checking each row's length is within bounds, as the problem implies a grid but standard constraints usually allow jagged arrays unless specified otherwise; however, typical grid problems imply rectangularity. Given the constraint 'm x n grid', I should check if all rows have the same length. The constraint says '1 <= m, n <= 200', implying a fixed n. I will add a check for rectangularity to be safe as 'm x n grid' implies a rectangle.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(heights):
    if not isinstance(heights, list):
        return False
    m = len(heights)
    if not (1 <= m <= 200):
        return False
    if not isinstance(heights[0], list):
        return False
    n = len(heights[0])
    if not (1 <= n <= 200):
        return False
    for row in heights:
        if not isinstance(row, list):
            return False
        if len(row) != n:
            return False
        for h in row:
            if isinstance(h, bool) or not isinstance(h, int):
                return False
            if not (0 <= h <= 10**5):
                return False
    return True
