"""Machine-generated input-constraint validator for problem 'unique-paths-iii'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced rectangular shape, element types/values (0, 1, 2, -1), and the size constraint rows*cols <= 20. Did not enforce semantic guarantees about existence of start/end or walkability.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(grid):
    if not isinstance(grid, list):
        return False
    if len(grid) == 0:
        return False
    
    rows = len(grid)
    cols = len(grid[0])
    
    # Check rectangular shape and element types
    for row in grid:
        if not isinstance(row, list):
            return False
        if len(row) != cols:
            return False
        for cell in row:
            if not isinstance(cell, int) or isinstance(cell, bool):
                return False
            if cell not in (0, 1, 2, -1):
                return False
    
    # Check constraint: 1 <= rows * cols <= 20
    if not (1 <= rows * cols <= 20):
        return False
        
    return True
