"""Machine-generated input-constraint validator for problem 'number-of-restricted-paths'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'the graph is connected' as it is a semantic property requiring graph traversal to verify, not a simple input bound.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(n, edges):
    # Check n is an integer (not bool) and within range
    if not isinstance(n, int) or isinstance(n, bool):
        return False
    if not (1 <= n <= 2 * 10**4):
        return False

    # Check edges is a list
    if not isinstance(edges, list):
        return False

    # Check each edge
    for edge in edges:
        # Each edge must be a list/tuple of length 3
        if not isinstance(edge, (list, tuple)):
            return False
        if len(edge) != 3:
            return False
        
        u, v, w = edge
        
        # Check u, v, w are integers (not bools)
        if not isinstance(u, int) or isinstance(u, bool):
            return False
        if not isinstance(v, int) or isinstance(v, bool):
            return False
        if not isinstance(w, int) or isinstance(w, bool):
            return False
            
        # Check node indices are within 1..n
        if not (1 <= u <= n):
            return False
        if not (1 <= v <= n):
            return False
            
        # Check weight is positive
        if w <= 0:
            return False
            
    return True
