"""Machine-generated input-constraint validator for problem 'maximum-number-of-coins-you-can-get'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(piles):
    if not isinstance(piles, list):
        return False
    if not (3 <= len(piles) <= 10**5):
        return False
    if len(piles) % 3 != 0:
        return False
    for x in piles:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (1 <= x <= 10**4):
            return False
    return True
