"""Machine-generated input-constraint validator for problem 'longest-common-subsequence'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(text1, text2):
    if not isinstance(text1, str) or not isinstance(text2, str):
        return False
    if not (1 <= len(text1) <= 1000):
        return False
    if not (1 <= len(text2) <= 1000):
        return False
    if not all('a' <= c <= 'z' for c in text1):
        return False
    if not all('a' <= c <= 'z' for c in text2):
        return False
    return True
