"""Machine-generated input-constraint validator for problem 'network-delay-time'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: types, ranges for n, k, u, v, w, length of times, and structure of edges. Did not enforce semantic guarantees like connectivity or unique paths.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(times, n, k):
    # Check n
    if not isinstance(n, int) or isinstance(n, bool):
        return False
    if not (1 <= n <= 100):
        return False

    # Check k
    if not isinstance(k, int) or isinstance(k, bool):
        return False
    if not (1 <= k <= n):
        return False

    # Check times
    if not isinstance(times, list):
        return False
    
    max_len = n * (n - 1)
    if not (0 <= len(times) <= max_len):
        return False

    for edge in times:
        if not isinstance(edge, list):
            return False
        if len(edge) != 3:
            return False
        
        u, v, w = edge
        
        # Check u, v, w are integers (not bools)
        if not isinstance(u, int) or isinstance(u, bool):
            return False
        if not isinstance(v, int) or isinstance(v, bool):
            return False
        if not isinstance(w, int) or isinstance(w, bool):
            return False
        
        # Check ranges
        if not (1 <= u <= n):
            return False
        if not (1 <= v <= n):
            return False
        if u == v:
            return False
        if not (1 <= w <= 100):
            return False

    return True
