"""Machine-generated input-constraint validator for problem 'minimum-number-of-flips-to-convert-binary-matrix-to-zero-matrix'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced dimensions 1<=m,n<=3, rectangular shape, and element values in {0,1}. Skipped semantic guarantee about solvability.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(mat):
    if not isinstance(mat, list):
        return False
    m = len(mat)
    if not (1 <= m <= 3):
        return False
    if m == 0:
        return False
    n = len(mat[0])
    if not (1 <= n <= 3):
        return False
    for row in mat:
        if not isinstance(row, list):
            return False
        if len(row) != n:
            return False
        for val in row:
            if not isinstance(val, int) or isinstance(val, bool):
                return False
            if val not in (0, 1):
                return False
    return True
