"""Machine-generated input-constraint validator for problem 'super-washing-machines'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(machines):
    if not isinstance(machines, list):
        return False
    if not (1 <= len(machines) <= 10**4):
        return False
    for x in machines:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (0 <= x <= 10**5):
            return False
    return True
