"""Machine-generated input-constraint validator for problem 'ugly-number-ii'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(n):
    if isinstance(n, bool):
        return False
    if not isinstance(n, int):
        return False
    if not (1 <= n <= 1690):
        return False
    return True
