"""Machine-generated input-constraint validator for problem 'maximum-non-negative-product-in-a-matrix'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced grid dimensions (1-15), rectangular shape, element type (int, not bool), and value range (-4 to 4). Skipped semantic guarantees about path products.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(grid):
    if not isinstance(grid, list):
        return False
    if len(grid) == 0:
        return False
    rows = len(grid)
    if not (1 <= rows <= 15):
        return False
    cols = len(grid[0])
    if not (1 <= cols <= 15):
        return False
    for row in grid:
        if not isinstance(row, list):
            return False
        if len(row) != cols:
            return False
        for val in row:
            if isinstance(val, bool) or not isinstance(val, int):
                return False
            if not (-4 <= val <= 4):
                return False
    return True
