"""Machine-generated input-constraint validator for problem 'largest-divisible-subset'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums):
    if not isinstance(nums, list):
        return False
    if not (1 <= len(nums) <= 1000):
        return False
    for x in nums:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if x <= 0:
            return False
    if len(nums) != len(set(nums)):
        return False
    return True
