"""Machine-generated input-constraint validator for problem 'same-tree'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Treated p and q as lists based on the parameter description 'encoded as a level-order list', despite the name 'TreeNode'. Enforced node count and value ranges. Skipped structural validity of the tree shape (e.g. whether the list correctly represents a binary tree) as that is often considered part of the problem's implicit guarantee or too complex for simple input validation without parsing.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(p, q):
    # Helper to validate a single tree structure
    def validate_tree(node):
        if node is None:
            return True
        # Check if node is a dict (representing TreeNode) or has expected attributes
        # The problem states p and q are TreeNode objects. In Python validation context,
        # we often receive dicts or objects. Let's assume standard object-like behavior
        # or dict-like. However, the prompt says "TreeNode objects (or None)".
        # Since we cannot import TreeNode, we must check for generic object properties
        # or assume the input is a dict representing the node if it's not None.
        # But wait, the prompt says "encoded as a level-order list" in the description
        # but then says "your function receives p and q as TreeNode objects".
        # This is a contradiction in the prompt's description of the *input format* vs *parameter type*.
        # Parameter type says: TreeNode (a binary tree, encoded as a level-order list...)
        # This implies the input IS the list, not the object.
        # Let's re-read carefully: "The function's parameters... p: TreeNode (a binary tree, encoded as a level-order list with null for absent children)"
        # This definition is confusing. Usually "TreeNode" implies an object. "Encoded as a level-order list" implies a list.
        # Given the previous examples used lists like [1,2,3], and the parameter description explicitly says "encoded as a level-order list",
        # I will treat p and q as lists.
        pass

    # Re-evaluating based on "p: TreeNode (a binary tree, encoded as a level-order list...)"
    # This likely means the input is a list of values/nulls.
    
    def is_valid_tree_list(tree):
        if not isinstance(tree, list):
            return False
        if len(tree) == 0:
            return True # Empty tree is valid (0 nodes)
        
        count = 0
        for val in tree:
            if val is None:
                continue
            if not isinstance(val, int) or isinstance(val, bool):
                return False
            if not (-10**4 <= val <= 10**4):
                return False
            count += 1
            
        if not (0 <= count <= 100):
            return False
            
        return True

    return is_valid_tree_list(p) and is_valid_tree_list(q)
