"""Machine-generated input-constraint validator for problem 'combination-sum-iv'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'distinct' constraint as it is a semantic property of the set of values, but enforced positive integers and ranges.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums, target):
    if not isinstance(nums, list):
        return False
    if not (1 <= len(nums) <= 200):
        return False
    for x in nums:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if x <= 0:
            return False
    if not isinstance(target, int) or isinstance(target, bool):
        return False
    if not (1 <= target <= 1000):
        return False
    return True
