"""Machine-generated input-constraint validator for problem 'solve-the-equation'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced type, non-empty, exactly one '=', and allowed character set. Skipped semantic validity of the equation structure (e.g. valid parsing) as it is not a simple input bound.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(equation):
    if not isinstance(equation, str):
        return False
    if len(equation) == 0:
        return False
    if equation.count('=') != 1:
        return False
    allowed_chars = set('0123456789x+-=')
    if not all(c in allowed_chars for c in equation):
        return False
    return True
