"""Machine-generated input-constraint validator for problem 'shortest-bridge'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'exactly two islands are present' as it is a semantic guarantee requiring traversal to verify, not a raw input bound.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(grid):
    if not isinstance(grid, list):
        return False
    if len(grid) < 2 or len(grid) > 100:
        return False
    row_len = len(grid[0])
    if row_len < 2 or row_len > 100:
        return False
    for row in grid:
        if not isinstance(row, list):
            return False
        if len(row) != row_len:
            return False
        for cell in row:
            if not isinstance(cell, int) or isinstance(cell, bool):
                return False
            if cell not in (0, 1):
                return False
    return True
