"""Machine-generated input-constraint validator for problem 'maximal-square'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced rectangular shape, dimensions 1-300, and element values '0'/'1'. Skipped semantic guarantees about maximal square existence.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(matrix):
    if not isinstance(matrix, list):
        return False
    m = len(matrix)
    if not (1 <= m <= 300):
        return False
    n = None
    for row in matrix:
        if not isinstance(row, list):
            return False
        if n is None:
            n = len(row)
        else:
            if len(row) != n:
                return False
        if not (1 <= n <= 300):
            return False
        for val in row:
            if not isinstance(val, str) or val not in ('0', '1'):
                return False
    if n is None:
        return False
    return True
