"""Machine-generated input-constraint validator for problem 'number-of-valid-words-for-each-puzzle'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: list types, lengths of lists, lengths of strings, lowercase requirement, and distinct letters in puzzles. Did not enforce semantic validity of words/puzzles relationship as that is part of the problem logic, not input constraints.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(words, puzzles):
    if not isinstance(words, list):
        return False
    if not isinstance(puzzles, list):
        return False
    
    if not (1 <= len(words) <= 10**5):
        return False
    if not (1 <= len(puzzles) <= 10**4):
        return False
    
    for w in words:
        if not isinstance(w, str):
            return False
        if not (4 <= len(w) <= 50):
            return False
        if not w.islower():
            return False
    
    for p in puzzles:
        if not isinstance(p, str):
            return False
        if len(p) != 7:
            return False
        if not p.islower():
            return False
        if len(set(p)) != 7:
            return False
            
    return True
