"""Machine-generated input-constraint validator for problem 'as-far-from-land-as-possible'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced rectangular shape, dimensions, and cell values (0/1). Skipped semantic guarantees about existence of land/water.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(grid):
    if not isinstance(grid, list):
        return False
    if not (1 <= len(grid) <= 100):
        return False
    row_len = len(grid[0])
    if not (1 <= row_len <= 100):
        return False
    for row in grid:
        if not isinstance(row, list):
            return False
        if len(row) != row_len:
            return False
        for cell in row:
            if not isinstance(cell, int) or isinstance(cell, bool):
                return False
            if cell not in (0, 1):
                return False
    return True
