"""Machine-generated input-constraint validator for problem 'reconstruct-original-digits-from-english'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'input is guaranteed valid' as it is a semantic guarantee about the content structure, not a checkable input bound.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s):
    if not isinstance(s, str):
        return False
    if not (1 <= len(s) < 50000):
        return False
    if not all(c.islower() and c.isalpha() for c in s):
        return False
    return True
