"""Machine-generated input-constraint validator for problem 'minimum-area-rectangle'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'points are distinct' as it is a semantic guarantee about the content, not a structural or range constraint checkable without processing the whole set for uniqueness (though uniqueness is checkable, it is often treated as a guarantee in these problems; however, strictly speaking, it is checkable. But usually 'distinct' is a promise. I will stick to the rule: 'Do NOT enforce semantic guarantees... Skip these'. Distinctness is a property of the set, not the raw format. Wait, distinctness IS checkable from raw input. But the prompt says 'Do NOT enforce semantic guarantees... e.g. exactly one valid answer exists'. Distinctness is a constraint on the input data validity. Let's look at rule 2 again. 'Do NOT enforce semantic guarantees that would require solving the problem...'. Checking distinctness does not require solving the rectangle problem. It is a simple O(N^2) or O(N log N) check. However, often in these LeetCode-style validators, 'distinct' is considered a guarantee. I will follow the strict interpretation of Rule 2: if it's a guarantee about the input state rather than a type/range bound, skip it. The prompt explicitly lists 'exactly one valid answer exists' as something to skip. 'Points are distinct' is similar in nature to 'array is sorted' or 'tree is balanced' - it's a property of the data. I will skip it to be safe and consistent with 'promises, not checkable input bounds' in the spirit of the prompt, although technically it is checkable. Actually, re-reading Rule 1: 'Enforce only constraints that are checkable from the raw input alone... value ranges... element types'. Distinctness is not a value range or type. It is a relational constraint. I will skip it.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(points):
    if not isinstance(points, list):
        return False
    if not (1 <= len(points) <= 500):
        return False
    for point in points:
        if not isinstance(point, list):
            return False
        if len(point) != 2:
            return False
        for coord in point:
            if not isinstance(coord, int) or isinstance(coord, bool):
                return False
            if not (0 <= coord <= 4 * 10**4):
                return False
    return True
