"""Machine-generated input-constraint validator for problem 'remove-duplicates-sorted-array'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length, element type/range, and sorted order. All are checkable from raw input.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums):
    if not isinstance(nums, list):
        return False
    if not (0 <= len(nums) <= 10**5):
        return False
    for x in nums:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (-10**9 <= x <= 10**9):
            return False
    # Check if sorted in non-decreasing order
    for i in range(len(nums) - 1):
        if nums[i] > nums[i + 1]:
            return False
    return True
