"""Machine-generated input-constraint validator for problem 'best-time-buy-sell-stock'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(prices):
    if not isinstance(prices, list):
        return False
    if not (0 <= len(prices) <= 10**5):
        return False
    for x in prices:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (0 <= x <= 10**5):
            return False
    return True
