"""Machine-generated input-constraint validator for problem 'best-time-buy-sell-stock'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  The problem statement provides no explicit constraints on length or value ranges, so only type checks are enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(prices):
    if not isinstance(prices, list):
        return False
    for x in prices:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
    return True
