"""Machine-generated input-constraint validator for problem 'maximum-binary-tree-ii'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced node count (len(A) <= 99 derived from resulting list length <= 100) and uniqueness of values in A + [val]. Skipped structural guarantees about it being a 'maximum tree' as that is a semantic property of the input generation, not a simple input bound checkable without solving/reconstructing.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root, val):
    # Check val type and range
    if not isinstance(val, int) or isinstance(val, bool):
        return False
    
    # We need to traverse the tree to check constraints on nodes.
    # The constraint says "the resulting list has length in [1, 100] with unique values".
    # The resulting list is A + [val]. So len(A) + 1 <= 100 => len(A) <= 99.
    # Also len(A) + 1 >= 1 => len(A) >= 0.
    # And all values in A + [val] must be unique.
    
    # First, validate that root is a valid tree structure (TreeNode or None)
    # We assume TreeNode is a class with 'val', 'left', 'right' attributes.
    # Since we can't import TreeNode, we check for duck-typing or None.
    
    nodes = []
    if root is not None:
        if not hasattr(root, 'val') or not hasattr(root, 'left') or not hasattr(root, 'right'):
            return False
        queue = [root]
        while queue:
            node = queue.pop(0)
            nodes.append(node)
            if node.left is not None:
                if not hasattr(node.left, 'val') or not hasattr(node.left, 'left') or not hasattr(node.left, 'right'):
                    return False
                queue.append(node.left)
            if node.right is not None:
                if not hasattr(node.right, 'val') or not hasattr(node.right, 'left') or not hasattr(node.right, 'right'):
                    return False
                queue.append(node.right)
    
    # Check node count constraint: len(A) <= 99
    if len(nodes) > 99:
        return False
    
    # Collect values from the tree
    tree_values = []
    for node in nodes:
        v = node.val
        if not isinstance(v, int) or isinstance(v, bool):
            return False
        tree_values.append(v)
    
    # Check uniqueness of all values in A + [val]
    all_values = tree_values + [val]
    if len(all_values) != len(set(all_values)):
        return False
        
    return True
