"""Machine-generated input-constraint validator for problem 'pow-function'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints including the conditional constraint on x when n is negative.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(x, n):
    # Check x is a number (int or float) but not bool
    if isinstance(x, bool) or not isinstance(x, (int, float)):
        return False
    # Check n is an integer but not bool
    if isinstance(n, bool) or not isinstance(n, int):
        return False
    
    # Check ranges
    if not (-30.0 <= x <= 30.0):
        return False
    if not (-30 <= n <= 30):
        return False
        
    # Check semantic constraint: x != 0 when n < 0
    if n < 0 and x == 0:
        return False
        
    return True
