"""Machine-generated input-constraint validator for problem 'binary-tree-zigzag-level-order-traversal'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Validated that root is None or a TreeNode-like object with val, left, right attributes, and that the total number of nodes is between 0 and 2000. Did not enforce semantic tree properties like 'binary' structure beyond existence of left/right, as 'TreeNode' implies this. Assumed TreeNode is an object with attributes rather than a list, based on parameter type declaration.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root):
    # The problem states the input is a TreeNode object.
    # However, the example and format description mention level-order arrays.
    # The parameter declaration says 'root: TreeNode'.
    # Usually, in these validation tasks, if the parameter is declared as a specific object type
    # (like TreeNode), we validate that object structure. If it were declared as a list,
    # we would validate the list. Given the ambiguity of 'TreeNode' not being a built-in,
    # and the prompt asking to validate based on constraints, we must assume 'root' is an instance
    # of a class with 'val', 'left', 'right' attributes, or None.
    # BUT, looking at previous examples, if the type is not a primitive, we often check for None
    # or the specific structure. Since 'TreeNode' is not defined in the global scope,
    # we cannot do `isinstance(root, TreeNode)`. 
    # However, standard LeetCode-style inputs for 'TreeNode' problems often pass the root node.
    # Let's assume the input is either None or an object with 'val', 'left', 'right'.
    # We need to count nodes to check the constraint 0 <= nodes <= 2000.
    
    if root is None:
        return True
        
    # Check if root is a dict or an object. LeetCode often uses objects.
    # If it's a custom class, it might not be importable. 
    # Let's check for attributes.
    if not hasattr(root, 'val'):
        return False
        
    # Count nodes
    count = 0
    stack = [root]
    visited = set()
    
    # To handle potential cycles or malformed trees, we track visited nodes by id
    # Although a tree shouldn't have cycles, robust validation helps.
    
    while stack:
        node = stack.pop()
        if node is None:
            continue
            
        # Check if we've seen this node before (cycle detection)
        if id(node) in visited:
            return False
        visited.add(id(node))
        
        count += 1
        
        # Check if node has left and right attributes
        if not hasattr(node, 'left') or not hasattr(node, 'right'):
            return False
            
        stack.append(node.left)
        stack.append(node.right)
        
        if count > 2000:
            return False
            
    return 0 <= count <= 2000
