"""Machine-generated input-constraint validator for problem 'trapping-rain-water'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(height):
    if not isinstance(height, list):
        return False
    n = len(height)
    if not (0 <= n <= 2 * 10**4):
        return False
    for x in height:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (0 <= x <= 10**5):
            return False
    return True
