"""Machine-generated input-constraint validator for problem 'search-in-rotated-sorted-array'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'values distinct' and 'rotated sorted array' constraints as they are semantic properties requiring solving/analysis, not simple input bounds.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums, target):
    if not isinstance(nums, list):
        return False
    if not (1 <= len(nums) <= 5000):
        return False
    for x in nums:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (-10**4 <= x <= 10**4):
            return False
    if not isinstance(target, int) or isinstance(target, bool):
        return False
    return True
