"""Machine-generated input-constraint validator for problem 'strictly-increasing-rows'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: matrix dimensions, element types (int, not bool), and value ranges. Did not enforce 'strictly increasing' property as that is part of the problem logic, not an input constraint.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(matrix):
    if not isinstance(matrix, list):
        return False
    if not (1 <= len(matrix) <= 1000):
        return False
    for row in matrix:
        if not isinstance(row, list):
            return False
        if not (1 <= len(row) <= 1000):
            return False
        for val in row:
            if isinstance(val, bool) or not isinstance(val, int):
                return False
            if not (-10**9 <= val <= 10**9):
                return False
    return True
