"""Machine-generated input-constraint validator for problem 'water-and-jug-problem'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(x, y, z):
    if not isinstance(x, int) or isinstance(x, bool):
        return False
    if not isinstance(y, int) or isinstance(y, bool):
        return False
    if not isinstance(z, int) or isinstance(z, bool):
        return False
    if not (0 <= x <= 10**6):
        return False
    if not (0 <= y <= 10**6):
        return False
    if not (0 <= z <= 10**6):
        return False
    return True
