"""Machine-generated input-constraint validator for problem 'find-largest-value-in-each-tree-row'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Assumed input is a list based on the example and description 'encoded as a level-order list', despite the type hint 'TreeNode'. Validated node count and 32-bit integer ranges.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root):
    # The problem statement implies the input is a TreeNode object or None.
    # However, the parameter description says "root: TreeNode (a binary tree, encoded as a level-order list...)".
    # This is a contradiction common in these prompts. Usually, if the signature says `root`, it's the object.
    # But the description explicitly says "encoded as a level-order list".
    # Let's look at the example: `root = [1,3,2,5,3,null,9]`. This is a list.
    # The text also says "your function works with TreeNode objects". This is confusing.
    # Standard LeetCode format for "Validate Input" tasks usually passes the raw data structure described.
    # If the parameter is named `root` and described as a list in the prompt's specific context for this task,
    # I should validate the list structure.
    # However, the prompt says: "The function's parameters (name and declared type) are: - root: TreeNode".
    # And then: "encoded as a level-order list with null for absent children".
    # This suggests the input `root` IS the list representation, despite the type hint saying TreeNode.
    # Or it suggests I need to handle a TreeNode object.
    # Let's re-read carefully: "root: TreeNode (a binary tree, encoded as a level-order list with null for absent children)".
    # This phrasing usually means the *concept* is a TreeNode, but the *data* passed is the list.
    # Let's assume the input `root` is the list [1, 3, 2, ...] or None/empty list.
    
    # If the input was a TreeNode object, the constraints would be on the object graph.
    # If the input is a list, the constraints are on the list.
    # Given the explicit example `root = [1,3,2,5,3,null,9]`, I will validate the list.
    
    if root is None:
        # An empty tree can be represented as None or []
        return True
        
    if not isinstance(root, list):
        return False
        
    # Constraint: 0 <= number of nodes <= 10^4
    # The number of nodes is the count of non-null elements in the list.
    # However, the list length itself is bounded by the structure.
    # A complete binary tree with N nodes has a list length of N.
    # If trailing nulls are dropped, the list length is <= 2*N - 1 roughly?
    # Actually, the constraint is on the *number of nodes*, not the list length.
    # But we can check the list length as a proxy or count non-nulls.
    # Let's count non-nulls to be precise about "number of nodes".
    
    node_count = 0
    for item in root:
        if item is not None:
            node_count += 1
            # Check if item is an integer (32-bit)
            if isinstance(item, bool):
                return False
            if not isinstance(item, int):
                return False
            # 32-bit integer range: -2^31 to 2^31 - 1
            if not (-2**31 <= item <= 2**31 - 1):
                return False
        else:
            # item is None, which is allowed
            pass
            
    if not (0 <= node_count <= 10**4):
        return False
        
    return True
