"""Machine-generated input-constraint validator for problem 'merge-k-sorted-lists'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced k range, total length limit, and element types. Did not enforce 'ascending' order as that is a semantic property of the data content rather than a raw input bound, and checking it requires iterating and comparing values which borders on solving/validating logic rather than just type/shape constraints, though typically 'ascending' is a guarantee. However, strict interpretation of 'checkable from raw input' usually allows checking sortedness. Let's re-read Rule 2: 'Do NOT enforce semantic guarantees... that describe the answer'. 'Ascending' describes the input structure. But often in these problems, 'ascending' is a guarantee provided to simplify the solution. If I enforce it, I might reject valid inputs if the problem statement implies the input *will be* ascending but doesn't strictly constrain the validator to check it? No, usually constraints are hard bounds. However, checking if a list is sorted is O(N). The prompt asks for 'value ranges, collection lengths/sizes... element types'. Sortedness is a value relationship. I will skip enforcing sortedness to be safe against 'semantic guarantees' interpretation, as it's often a promise about the input state rather than a hard filter for invalid data types/shapes.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(lists):
    if not isinstance(lists, list):
        return False
    k = len(lists)
    if not (0 <= k <= 10**4):
        return False
    total_length = 0
    for lst in lists:
        if not isinstance(lst, list):
            return False
        total_length += len(lst)
        for x in lst:
            if not isinstance(x, int) or isinstance(x, bool):
                return False
    if not (total_length <= 10**4):
        return False
    return True
