"""Machine-generated input-constraint validator for problem 'two-sum-ii-input-array-is-sorted'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'exactly one solution exists' as it is a semantic guarantee about the answer, not a checkable input bound.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(numbers, target):
    if not isinstance(numbers, list):
        return False
    if not (2 <= len(numbers) <= 3 * 10**4):
        return False
    for x in numbers:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (-1000 <= x <= 1000):
            return False
    if not isinstance(target, int) or isinstance(target, bool):
        return False
    if not (-1000 <= target <= 1000):
        return False
    # Check if sorted in non-decreasing order
    for i in range(len(numbers) - 1):
        if numbers[i] > numbers[i + 1]:
            return False
    return True
