"""Machine-generated input-constraint validator for problem 'uncrossed-lines'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(A, B):
    if not isinstance(A, list) or not isinstance(B, list):
        return False
    if not (1 <= len(A) <= 500) or not (1 <= len(B) <= 500):
        return False
    for x in A:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (1 <= x <= 2000):
            return False
    for x in B:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (1 <= x <= 2000):
            return False
    return True
