"""Machine-generated input-constraint validator for problem 'matrix-block-sum'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: types, matrix rectangularity, dimensions m, n, k ranges, and element value ranges.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(mat, k):
    # Check mat is a list
    if not isinstance(mat, list):
        return False
    
    # Check k is an integer (and not a bool)
    if not isinstance(k, int) or isinstance(k, bool):
        return False
    
    # Check k range
    if not (1 <= k <= 100):
        return False
    
    # Check mat dimensions and content
    m = len(mat)
    if not (1 <= m <= 100):
        return False
    
    n = None
    for row in mat:
        if not isinstance(row, list):
            return False
        if n is None:
            n = len(row)
            if not (1 <= n <= 100):
                return False
        else:
            if len(row) != n:
                return False
        
        for val in row:
            if not isinstance(val, int) or isinstance(val, bool):
                return False
            if not (1 <= val <= 100):
                return False
    
    # Handle empty matrix case if m > 0 but n could be 0? 
    # Constraints say 1 <= n, so if m >= 1, n must be >= 1. 
    # If m=0, it fails 1<=m. So we are good.
    
    return True
