"""Machine-generated input-constraint validator for problem 'new-21-game'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable bounds on the input parameters and were enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(N, K, W):
    # Check types, excluding booleans
    for val in (N, K, W):
        if not isinstance(val, int) or isinstance(val, bool):
            return False
    
    # Check constraints: 0 <= K <= N <= 10^4
    if not (0 <= K <= N <= 10**4):
        return False
    
    # Check constraints: 1 <= W <= 10^4
    if not (1 <= W <= 10**4):
        return False
        
    return True
