"""Machine-generated input-constraint validator for problem 'single-number'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'Exactly one element appears once; every other element appears exactly twice' as it is a semantic guarantee about the content distribution, not a simple type/range constraint checkable without solving the problem logic.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums):
    if not isinstance(nums, list):
        return False
    if not (1 <= len(nums) <= 3 * 10**4):
        return False
    if len(nums) % 2 == 0:
        return False
    for x in nums:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (-10**9 <= x <= 10**9):
            return False
    return True
