"""Machine-generated input-constraint validator for problem 'word-pattern'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: types, lengths, character sets, and spacing rules. Did not enforce the bijection logic as that is the problem to solve, not an input constraint.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(pattern, s):
    if not isinstance(pattern, str) or not isinstance(s, str):
        return False
    if not (1 <= len(pattern) <= 300):
        return False
    if not (1 <= len(s) <= 3000):
        return False
    for ch in pattern:
        if not ('a' <= ch <= 'z'):
            return False
    for ch in s:
        if not ('a' <= ch <= 'z' or ch == ' '):
            return False
    if s.startswith(' ') or s.endswith(' '):
        return False
    if '  ' in s:
        return False
    return True
