#!/usr/bin/env python3
"""Generate input-constraint validators for class/design problems — deterministically.

For a function problem, ``scripts/generate_constraint_validators.py`` asks an LLM to
translate the statement's prose bounds into a ``validate_input(<params>) -> bool``
predicate. A class/design problem (``kind == "class"``) is different: its input is
not a bag of typed params but a **method-call sequence**

    {"operations": ["<ClassName>", "<method>", ...],
     "args":       [[<ctor args>],  [<method args>], ...]}

whose legality is almost entirely *structural* and fully specified by the class
block in ``meta.json`` (the constructor + method signatures). So we do NOT need a
model here — we emit the validator directly from the signatures:

    def validate_input(operations, args):
        # operations/args are aligned lists; operations[0] constructs the instance
        # (exactly once, at the front); every later op is a declared method; each
        # arg list matches its op's arity and per-arg declared type.

This gate is what ``scripts/strengthen_tests.py`` / ``scripts/oracle.py`` use to keep
generated operation sequences in-domain (a fuzzer that produced a wrong method name
or arg type would be rejected). It is intentionally **structure + type only** — it
does not invent per-value numeric bounds (those are semantic and risk over-tightening;
the generators already draw args from the signatures + observed pools, so they stay in
range). Safe-in-one-direction, exactly like the function validators: a too-strict gate
only loses coverage, it never bakes an illegal input.

Output goes straight to the vetted in-tree home each problem's validator lives at,
``<root>/<slug>/input_validator/input_validator.py`` (entry point ``validate_input``),
the same file ``scripts/check_constraint_validators.py`` audits. Runs over BOTH content
roots (default + extended), where the design problems live.

Usage:
    python scripts/generate_class_validators.py                 # all class problems
    python scripts/generate_class_validators.py --slug min-stack -v
    python scripts/generate_class_validators.py --dry-run -v
    python scripts/generate_class_validators.py --force         # overwrite existing
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from app.config import settings  # noqa: E402
import generate_constraint_validators as gcv  # noqa: E402  (reuse verify_against_cases)

VALIDATOR_NAME = "validate_input"


# --------------------------------------------------------------------------- #
# Signature extraction
# --------------------------------------------------------------------------- #
def _parse_type(t: str) -> tuple[str, int]:
    """``"int[][]"`` -> ``("int", 2)``; base is lower-cased-preserving for rich types."""
    t = (t or "").strip()
    dims = 0
    while t.endswith("[]"):
        t = t[:-2].strip()
        dims += 1
    return t, dims


def class_signatures(meta: dict) -> tuple[str, dict[str, list[tuple[str, int]]]]:
    """Return ``(class_name, {op_name: [(base, dims), ...]})`` from a meta.json class block.

    The constructor is keyed under the class name; each method under its own name.
    """
    block = meta.get("class") or {}
    class_name = block.get("name") or ""
    sig: dict[str, list[tuple[str, int]]] = {}
    ctor = (block.get("constructor") or {}).get("params") or []
    sig[class_name] = [_parse_type(p.get("type", "")) for p in ctor]
    for m in block.get("methods") or []:
        name = m.get("name")
        if not name:
            continue
        sig[name] = [_parse_type(p.get("type", "")) for p in (m.get("params") or [])]
    return class_name, sig


# --------------------------------------------------------------------------- #
# Validator source emission
# --------------------------------------------------------------------------- #
_TEMPLATE = '''\
"""Machine-generated input-constraint validator for design problem {slug!r}.

Generated by scripts/generate_class_validators.py (deterministic, from the class
block in meta.json — no LLM). `validate_input(operations, args)` returns True iff
the method-call sequence is well-formed for the `{class_name}` class: aligned
operations/args lists, the constructor exactly once at the front, every later op a
declared method, and each arg list matching its op's arity and per-arg type.
Structure + type only (no per-value numeric bounds). Re-run the generator to update.
"""


# op-name -> list of (base_type, list_dims) for each positional argument.
_SIG = {sig_literal}
_CTOR = {ctor_literal}


def _scalar_ok(v, base):
    if base == "int":
        return isinstance(v, int) and not isinstance(v, bool)
    if base in ("float", "num"):
        return isinstance(v, (int, float)) and not isinstance(v, bool)
    if base == "bool":
        return isinstance(v, bool)
    if base in ("string", "str", "char"):
        return isinstance(v, str)
    if base in ("TreeNode", "ListNode", "DoublyLinkedList"):
        # Wire form: a level-order / flat value list of ints (None marks a hole),
        # or None / [] for an empty structure.
        if v is None:
            return True
        if not isinstance(v, list):
            return False
        return all(x is None or (isinstance(x, int) and not isinstance(x, bool)) for x in v)
    # Iterator / NestedInteger / object / any / unknown: opaque — don't reject.
    return True


def _type_ok(v, base, dims):
    if dims == 0:
        return _scalar_ok(v, base)
    if not isinstance(v, list):
        return False
    return all(_type_ok(e, base, dims - 1) for e in v)


def {name}(operations, args):
    if not isinstance(operations, list) or not isinstance(args, list):
        return False
    if len(operations) != len(args):
        return False
    if not operations:
        return False
    if operations[0] != _CTOR:
        return False
    for op in operations[1:]:
        if op == _CTOR or op not in _SIG:
            return False
    for op, a in zip(operations, args):
        sig = _SIG.get(op)
        if sig is None:
            return False
        if not isinstance(a, list) or len(a) != len(sig):
            return False
        for val, (base, dims) in zip(a, sig):
            if not _type_ok(val, base, dims):
                return False
    return True
'''


def build_validator_source(slug: str, meta: dict) -> str:
    class_name, sig = class_signatures(meta)
    # Emit deterministic, sorted-key literals for a stable diff.
    sig_items = ",\n    ".join(
        f"{name!r}: {params!r}" for name, params in sig.items())
    sig_literal = "{\n    " + sig_items + ",\n}" if sig else "{}"
    return _TEMPLATE.format(
        slug=slug, class_name=class_name, name=VALIDATOR_NAME,
        sig_literal=sig_literal, ctor_literal=repr(class_name),
    )


# --------------------------------------------------------------------------- #
# Driver
# --------------------------------------------------------------------------- #
def _iter_class_dirs(wanted: set[str]):
    """Yield (root, dir) for every kind==class problem across both content roots."""
    for root in settings.content_dirs:
        if not root.exists():
            continue
        for d in sorted(root.iterdir()):
            if not (d.is_dir() and (d / "meta.json").exists()):
                continue
            if wanted and d.name not in wanted:
                continue
            try:
                meta = json.loads((d / "meta.json").read_text(encoding="utf-8"))
            except (json.JSONDecodeError, OSError):
                continue
            if meta.get("kind") == "class":
                yield root, d, meta


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--slug", action="append", default=[],
                    help="only this slug (repeatable); default = all class problems")
    ap.add_argument("--force", action="store_true",
                    help="overwrite an existing input_validator.py")
    ap.add_argument("--dry-run", action="store_true",
                    help="build + self-verify but write nothing")
    ap.add_argument("-v", "--verbose", action="count", default=0,
                    help="-v prints verify detail; -vv also prints the source")
    args = ap.parse_args()
    wanted = set(args.slug)

    considered = wrote = skipped = flagged = failed = 0
    seen: set[str] = set()
    for root, d, meta in _iter_class_dirs(wanted):
        slug = d.name
        seen.add(slug)
        considered += 1
        vfile = d / "input_validator" / "input_validator.py"
        if vfile.exists() and vfile.stat().st_size > 0 and not args.force and not args.dry_run:
            skipped += 1
            if args.verbose:
                print(f"  skip  {slug:<45} (exists; --force to overwrite)")
            continue

        code = build_validator_source(slug, meta)

        # Self-verify: every stored (legal) test input must be accepted.
        vstr = "verify=n/a"
        cases_path = d / "tests" / "cases.json"
        if cases_path.exists():
            try:
                cases = json.loads(cases_path.read_text(encoding="utf-8")).get("cases", [])
                npass, tot, detail = gcv.verify_against_cases(code, cases, params=[])
                if tot == 0:
                    vstr = "verify=n/a"
                elif npass == tot:
                    vstr = f"verify=OK({npass}/{tot})"
                else:
                    vstr = f"verify=FLAG({npass}/{tot})"
                    flagged += 1
            except Exception as e:  # noqa: BLE001
                vstr = f"verify=ERR({type(e).__name__})"
                detail = str(e)
                failed += 1

        if not args.dry_run:
            vfile.parent.mkdir(parents=True, exist_ok=True)
            vfile.write_text(code, encoding="utf-8")
            wrote += 1
        print(f"  {'DRY ' if args.dry_run else 'OK  '} {slug:<45} {vstr}")
        if args.verbose and vstr.startswith(("verify=FLAG", "verify=ERR")):
            print(f"          {detail}")
        if args.verbose >= 2:
            print("\n".join("          " + ln for ln in code.splitlines()))

    missing = wanted - seen
    for m in sorted(missing):
        print(f"  - {m}: no such class problem — skipped")

    print(f"\nClass validators: considered={considered} wrote={wrote} "
          f"skipped_existing={skipped} flagged={flagged} errored={failed}"
          + ("  (dry run: nothing written)" if args.dry_run else ""))
    if flagged:
        print("FLAG(...) = the deterministic validator rejected a stored (legal) input; "
              "that means a signature/type mismatch worth inspecting.")
    return 1 if (flagged or failed) else 0


if __name__ == "__main__":
    raise SystemExit(main())
