"""Machine-generated input-constraint validator for problem 'symmetric-tree'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Interpreted 'root' as a level-order list based on the parameter description and examples, despite the 'TreeNode' type hint. Enforced node count and value range constraints. Skipped structural validity of the tree (e.g., whether the list forms a valid binary tree) as it's not explicitly constrained beyond the node count.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root):
    # The problem statement describes the input as a TreeNode object,
    # but also mentions level-order array form in examples.
    # However, the parameter declaration says 'root: TreeNode'.
    # Standard LeetCode validation for TreeNode usually involves checking
    # if it's None or an instance of a specific class. Since we don't have
    # the TreeNode class definition here, we must infer from the context.
    # Usually, in these validation tasks, if the type is 'TreeNode', we check
    # for None or a dict/object with 'val', 'left', 'right' attributes if
    # it's a custom implementation, OR we assume the input is already a
    # valid TreeNode object structure.
    #
    # Looking at the constraints:
    # 1. Number of nodes in [0, 1000]
    # 2. Node values in [-100, 100]
    #
    # If root is None, it represents an empty tree (0 nodes), which is valid.
    # If root is not None, it must be a TreeNode-like object.
    # Since we cannot import TreeNode, we will check for common representations.
    # Often in these pure-python validation contexts without the class,
    # the input might be a dictionary or a simple object. 
    # However, the prompt says "root: TreeNode (a binary tree, encoded as a level-order list...)".
    # Wait, the prompt description for the parameter says:
    # "root: TreeNode (a binary tree, encoded as a level-order list with null for absent children)"
    # This is contradictory. The type is TreeNode, but the description says it's encoded as a list.
    # Let's look at the Examples: Input: root = [1,2,2,3,4,4,3].
    # This implies the input `root` is actually a LIST, not a TreeNode object,
    # despite the type hint saying TreeNode. The text "encoded as a level-order list" confirms this.
    # So we should validate a list.

    if not isinstance(root, list):
        return False

    # Count nodes (non-null elements)
    node_count = 0
    for val in root:
        if val is None:
            continue
        # Check if value is an integer (and not bool)
        if isinstance(val, bool) or not isinstance(val, int):
            return False
        # Check value range
        if not (-100 <= val <= 100):
            return False
        node_count += 1

    # Check node count constraint
    if not (0 <= node_count <= 1000):
        return False

    return True
