"""Machine-generated input-constraint validator for problem 'top-k-frequent-elements'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  The problem statement provided contains no explicit constraints section with bounds (e.g., length of nums, range of values, range of k). Therefore, only type checks are enforced. Semantic guarantees like 'k most frequent values exist' are skipped as they are not checkable input bounds.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums, k):
    if not isinstance(nums, list):
        return False
    if not isinstance(k, int) or isinstance(k, bool):
        return False
    for x in nums:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
    if len(nums) < 1:
        return False
    if k < 1 or k > len(nums):
        return False
    return True
