"""Machine-generated input-constraint validator for problem 'sum-of-subarray-minimums'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(A):
    if not isinstance(A, list):
        return False
    if not (1 <= len(A) <= 3 * 10**4):
        return False
    for x in A:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (1 <= x <= 3 * 10**4):
            return False
    return True
