"""Machine-generated input-constraint validator for problem 'kafka-contiguous-offset'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(processed):
    if not isinstance(processed, list):
        return False
    if not (1 <= len(processed) <= 2 * 10**5):
        return False
    for x in processed:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if x < 0:
            return False
    return True
