"""Machine-generated input-constraint validator for problem 'strange-printer-ii'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced rectangular shape, dimensions 1-60, and element values 1-60. Did not enforce the semantic guarantee that the grid can be produced by the printer, as that requires solving the problem.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(targetGrid):
    if not isinstance(targetGrid, list):
        return False
    if len(targetGrid) == 0:
        return False
    m = len(targetGrid)
    if not (1 <= m <= 60):
        return False
    n = len(targetGrid[0])
    if not (1 <= n <= 60):
        return False
    for row in targetGrid:
        if not isinstance(row, list):
            return False
        if len(row) != n:
            return False
        for val in row:
            if isinstance(val, bool) or not isinstance(val, int):
                return False
            if not (1 <= val <= 60):
                return False
    return True
