"""Machine-generated input-constraint validator for problem 'tallest-billboard'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(rods):
    if not isinstance(rods, list):
        return False
    if not (0 <= len(rods) <= 20):
        return False
    for x in rods:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (1 <= x <= 1000):
            return False
    if not (sum(rods) <= 5000):
        return False
    return True
