"""Machine-generated input-constraint validator for problem 'stone-game-iii'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(stoneValue):
    if not isinstance(stoneValue, list):
        return False
    if not (1 <= len(stoneValue) <= 5 * 10**4):
        return False
    for x in stoneValue:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (-1000 <= x <= 1000):
            return False
    return True
