"""Machine-generated input-constraint validator for problem 'multiply-strings'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length bounds, digit-only content, and no leading zeros (except for '0' itself) as stated in the problem description.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(num1, num2):
    if not isinstance(num1, str) or not isinstance(num2, str):
        return False
    if not (1 <= len(num1) < 110) or not (1 <= len(num2) < 110):
        return False
    if not num1.isdigit() or not num2.isdigit():
        return False
    if len(num1) > 1 and num1[0] == '0':
        return False
    if len(num2) > 1 and num2[0] == '0':
        return False
    return True
