"""Machine-generated input-constraint validator for problem 'minimum-cost-to-hire-k-workers'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: types, list lengths equality, N bounds, K bounds, and element value ranges. Skipped semantic guarantees about solution existence or rounding.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(quality, wage, K):
    # Check types for quality and wage
    if not isinstance(quality, list) or not isinstance(wage, list):
        return False
    
    # Check type for K (int, not bool)
    if not isinstance(K, int) or isinstance(K, bool):
        return False
    
    # Check lengths match and satisfy N constraint
    if len(quality) != len(wage):
        return False
    
    N = len(quality)
    
    # Check 1 <= K <= N <= 10^4
    if not (1 <= K <= N <= 10**4):
        return False
    
    # Check elements in quality and wage
    for q, w in zip(quality, wage):
        # Check q is int (not bool)
        if not isinstance(q, int) or isinstance(q, bool):
            return False
        # Check w is int (not bool)
        if not isinstance(w, int) or isinstance(w, bool):
            return False
        # Check ranges 1 <= q, w <= 10^4
        if not (1 <= q <= 10**4):
            return False
        if not (1 <= w <= 10**4):
            return False
            
    return True
