"""Machine-generated input-constraint validator for problem 'rearrange-words-in-a-sentence'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length bounds and character format constraints (capital start, lowercase rest, single spaces). Did not enforce semantic guarantees about word rearrangement.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(text):
    if not isinstance(text, str):
        return False
    if not (1 <= len(text) <= 10**5):
        return False
    if not text:
        return False
    # Check format: starts with capital, rest lowercase letters and single spaces
    # The constraint says: "begins with a capital letter followed by lowercase letters and single spaces"
    # This implies the structure is: [A-Z][a-z]* ( [a-z]+ )* 
    # Let's verify character by character or via regex logic without importing re if possible, 
    # but standard library allows re. However, simple iteration is robust.
    
    # First char must be uppercase letter
    if not text[0].isupper() or not text[0].isalpha():
        return False
    
    # Rest of the string must be lowercase letters or spaces
    # Also, spaces must be single (no consecutive spaces) and not at start/end (implied by "sentence" structure usually, 
    # but let's stick strictly to "lowercase letters and single spaces" after the first char)
    # Actually, the constraint says "followed by lowercase letters and single spaces".
    # This usually means the allowed characters are [a-z] and ' ', and ' ' cannot appear consecutively.
    # It also implies no leading/trailing spaces because the first char is handled separately and 
    # "single spaces" between words implies internal separation.
    
    prev_was_space = False
    for i in range(1, len(text)):
        ch = text[i]
        if ch == ' ':
            if prev_was_space:
                return False # Consecutive spaces
            prev_was_space = True
        elif ch.islower() and ch.isalpha():
            prev_was_space = False
        else:
            # Any other character (uppercase, digit, punctuation, etc.) is invalid
            return False
            
    # Ensure it doesn't end with a space (implied by "single spaces" separating words, 
    # and typically sentences don't end in space in these problems)
    if text[-1] == ' ':
        return False
        
    return True
