"""Machine-generated input-constraint validator for problem 'make-sum-divisible-by-p'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums, p):
    if not isinstance(nums, list):
        return False
    if not (1 <= len(nums) <= 10**5):
        return False
    for x in nums:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (1 <= x <= 10**9):
            return False
    if not isinstance(p, int) or isinstance(p, bool):
        return False
    if not (1 <= p <= 10**9):
        return False
    return True
