"""Machine-generated input-constraint validator for problem 'ipo'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'The answer is guaranteed to fit in a 32-bit signed integer' as it is a guarantee about the output, not a checkable constraint on the input.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(k, w, profits, capital):
    # Check k
    if not isinstance(k, int) or isinstance(k, bool):
        return False
    if not (1 <= k <= 10**5):
        return False

    # Check w
    if not isinstance(w, int) or isinstance(w, bool):
        return False
    if not (0 <= w <= 10**9):
        return False

    # Check profits
    if not isinstance(profits, list):
        return False
    n = len(profits)
    if not (1 <= n <= 10**5):
        return False
    for p in profits:
        if not isinstance(p, int) or isinstance(p, bool):
            return False
        if not (0 <= p <= 10**4):
            return False

    # Check capital
    if not isinstance(capital, list):
        return False
    if len(capital) != n:
        return False
    for c in capital:
        if not isinstance(c, int) or isinstance(c, bool):
            return False
        if not (0 <= c <= 10**9):
            return False

    return True
