"""Machine-generated input-constraint validator for problem 'maximum-width-binary-tree'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Assumed 'root' is a TreeNode object as per standard LeetCode signatures, despite the confusing description mentioning level-order lists. Validated node count [1, 3000] and value range [-100, 100] via traversal. Excluded bools from int checks.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root):
    # The problem statement describes the input as a TreeNode object.
    # However, the examples and the "Format" section describe a level-order list representation.
    # In LeetCode-style problems, the function signature usually takes the root node object.
    # But the prompt says: "root: TreeNode (a binary tree, encoded as a level-order list with null for absent children)".
    # This is contradictory. Usually, if the parameter is named `root` and type is `TreeNode`, it's an object.
    # If it's a list, the parameter is often `tree` or `nodes`.
    # Let's look at the constraints: "The number of nodes is in [1, 3000]". This refers to the count of actual nodes.
    # "-100 <= node value <= 100".
    
    # If the input is a TreeNode object:
    # We need to traverse it to count nodes and check values.
    # If the input is a list (level-order):
    # We need to parse it to count non-null nodes and check values.
    
    # The prompt explicitly states: "root: TreeNode (a binary tree, encoded as a level-order list with null for absent children)".
    # This phrasing is tricky. It likely means the *conceptual* input is a tree, but the *data* provided to the validator might be the list representation if the environment passes lists.
    # HOWEVER, standard LeetCode validators for `TreeNode` problems receive the `TreeNode` object.
    # Let's re-read carefully: "your function works with TreeNode objects... Trees are shown below in LeetCode level-order array form".
    # This implies the *function* receives a TreeNode. The *description* uses arrays for clarity.
    # Therefore, `root` is a TreeNode object.
    
    # We must validate:
    # 1. root is a TreeNode object (or None, but constraints say 1 <= nodes, so root cannot be None).
    # 2. The number of nodes in the tree is between 1 and 3000.
    # 3. Each node's value is between -100 and 100.
    # 4. Node values are integers (not bools).
    
    # Since we don't have the TreeNode class definition, we assume it has 'val', 'left', 'right' attributes.
    # We must be robust. If 'root' is not an object with these attributes, return False.
    
    if root is None:
        return False # Constraint: 1 <= nodes
    
    # Check if root is a valid TreeNode-like object
    # We assume standard LeetCode TreeNode structure: val, left, right
    if not hasattr(root, 'val') or not hasattr(root, 'left') or not hasattr(root, 'right'):
        return False
        
    # Traverse the tree to count nodes and validate values
    count = 0
    queue = [root]
    
    while queue:
        node = queue.pop(0)
        if node is None:
            continue
            
        # Check value type and range
        val = node.val
        if isinstance(val, bool) or not isinstance(val, int):
            return False
        if not (-100 <= val <= 100):
            return False
            
        count += 1
        
        # Check constraints on count early if possible, but we need to traverse all to be sure of structure?
        # Actually, if count exceeds 3000, we can fail early.
        if count > 3000:
            return False
            
        # Add children to queue
        # We need to check if children are None or TreeNode objects
        left = node.left
        right = node.right
        
        # If a child is not None, it must be a TreeNode-like object
        if left is not None:
            if not hasattr(left, 'val') or not hasattr(left, 'left') or not hasattr(left, 'right'):
                return False
            queue.append(left)
            
        if right is not None:
            if not hasattr(right, 'val') or not hasattr(right, 'left') or not hasattr(right, 'right'):
                return False
            queue.append(right)
            
    # Final check on node count
    if not (1 <= count <= 3000):
        return False
        
    return True
