"""Machine-generated input-constraint validator for problem 'search-sorted-matrix'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: matrix dimensions, element types/ranges, target type/range. Skipped semantic guarantees about sorting order as they describe the input structure's property rather than raw bounds, and verifying them would require solving/analyzing the data structure deeply.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(matrix, target):
    # Check matrix type
    if not isinstance(matrix, list):
        return False
    
    # Check matrix dimensions
    if not (1 <= len(matrix) <= 500):
        return False
    
    # Check each row
    for row in matrix:
        if not isinstance(row, list):
            return False
        if not (1 <= len(row) <= 500):
            return False
        # Check elements in row
        for val in row:
            if isinstance(val, bool) or not isinstance(val, int):
                return False
            if not (-10**9 <= val <= 10**9):
                return False
    
    # Check target type and range
    if isinstance(target, bool) or not isinstance(target, int):
        return False
    if not (-10**9 <= target <= 10**9):
        return False
    
    return True
