"""Machine-generated input-constraint validator for problem 'rotate-list'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(head, k):
    if not isinstance(head, list):
        return False
    if not (0 <= len(head) <= 500):
        return False
    for x in head:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (-100 <= x <= 100):
            return False
    if isinstance(k, bool) or not isinstance(k, int):
        return False
    if not (0 <= k <= 2 * 10**9):
        return False
    return True
