"""Machine-generated input-constraint validator for problem 'inventory-reservation'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: stock is dict, requests is list with length bound, keys are strings, values/quantities are non-negative 64-bit integers. Did not enforce semantic guarantees about stock availability or request processing logic.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(stock, requests):
    # Validate stock: must be a dict
    if not isinstance(stock, dict):
        return False
    
    # Validate requests: must be a list
    if not isinstance(requests, list):
        return False
    
    # Check length of requests
    if not (0 <= len(requests) <= 2 * 10**5):
        return False
    
    # Validate each element in stock
    for k, v in stock.items():
        # Key must be string
        if not isinstance(k, str):
            return False
        # Value must be non-negative integer (not bool)
        if isinstance(v, bool) or not isinstance(v, int):
            return False
        if v < 0:
            return False
        # Check if it fits in signed 64-bit integer
        if v > 2**63 - 1:
            return False
            
    # Validate each request
    for req in requests:
        # Each request must be a list/tuple of length 2
        if not isinstance(req, (list, tuple)) or len(req) != 2:
            return False
        
        sku, qty = req
        
        # SKU must be a string
        if not isinstance(sku, str):
            return False
            
        # Qty must be non-negative integer (not bool)
        if isinstance(qty, bool) or not isinstance(qty, int):
            return False
        if qty < 0:
            return False
        # Check if it fits in signed 64-bit integer
        if qty > 2**63 - 1:
            return False
            
    return True
