"""Machine-generated input-constraint validator for problem 'smallest-string-with-swaps'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: string length, character set, pairs list length, pair structure, integer types for indices, and index bounds relative to string length.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s, pairs):
    # Check s is a string
    if not isinstance(s, str):
        return False
    
    # Check length of s
    if not (1 <= len(s) <= 10**5):
        return False
    
    # Check s contains only lowercase letters
    if not all('a' <= c <= 'z' for c in s):
        return False
    
    # Check pairs is a list
    if not isinstance(pairs, list):
        return False
    
    # Check length of pairs
    if not (0 <= len(pairs) <= 10**5):
        return False
    
    # Check each element in pairs
    for pair in pairs:
        # Each pair must be a list
        if not isinstance(pair, list):
            return False
        # Each pair must have exactly 2 elements
        if len(pair) != 2:
            return False
        # Each element must be an integer (not bool)
        for idx in pair:
            if not isinstance(idx, int) or isinstance(idx, bool):
                return False
            # Indices must be valid for string s
            if not (0 <= idx < len(s)):
                return False
    
    return True
