"""Machine-generated input-constraint validator for problem 'minimum-number-of-refueling-stops'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced all checkable constraints: types, ranges for target/startFuel/fuel, length of stations, structure of station lists, and strictly increasing positions < target. Did not enforce semantic guarantees about reachability.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(target, startFuel, stations):
    # Check target
    if not isinstance(target, int) or isinstance(target, bool):
        return False
    if not (1 <= target <= 10**9):
        return False

    # Check startFuel
    if not isinstance(startFuel, int) or isinstance(startFuel, bool):
        return False
    if not (1 <= startFuel <= 10**9):
        return False

    # Check stations
    if not isinstance(stations, list):
        return False
    if not (0 <= len(stations) <= 500):
        return False

    prev_pos = -1
    for station in stations:
        if not isinstance(station, list):
            return False
        if len(station) != 2:
            return False
        
        pos, fuel = station
        
        # Check types
        if not isinstance(pos, int) or isinstance(pos, bool):
            return False
        if not isinstance(fuel, int) or isinstance(fuel, bool):
            return False
        
        # Check ranges
        if not (1 <= fuel <= 10**9):
            return False
        if not (0 <= pos < target):
            return False
        
        # Check strictly increasing positions
        if pos <= prev_pos:
            return False
        
        prev_pos = pos

    return True
