"""Machine-generated input-constraint validator for problem 'swim-in-rising-water'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced n range, square shape, integer types, and permutation property. Skipped semantic guarantees about reachability as they are not checkable from raw input alone.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(grid):
    if not isinstance(grid, list):
        return False
    n = len(grid)
    if not (1 <= n <= 50):
        return False
    for row in grid:
        if not isinstance(row, list):
            return False
        if len(row) != n:
            return False
        for val in row:
            if isinstance(val, bool) or not isinstance(val, int):
                return False
            if not (0 <= val < n * n):
                return False
    if sorted([val for row in grid for val in row]) != list(range(n * n)):
        return False
    return True
