"""Machine-generated input-constraint validator for problem 'letter-combinations-of-a-phone-number'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(digits):
    if not isinstance(digits, str):
        return False
    if not (1 <= len(digits) <= 4):
        return False
    for ch in digits:
        if ch not in '23456789':
            return False
    return True
