"""Machine-generated input-constraint validator for problem 'k-closest-points-to-origin'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'all squared distances x^2 + y^2 are distinct' as it is a semantic guarantee about the data distribution, not a simple bound checkable without computation, though technically checkable, it's often treated as a promise in such problems. However, strictly speaking, it IS checkable from raw input. But rule 2 says 'Do NOT enforce semantic guarantees... that describe the answer'. This constraint ensures the answer is unique. I will skip it to be safe as per Rule 2's spirit regarding uniqueness guarantees.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(points, k):
    # Check k is an integer (not bool)
    if not isinstance(k, int) or isinstance(k, bool):
        return False
    
    # Check points is a list
    if not isinstance(points, list):
        return False
    
    # Check length constraints: 1 <= k <= len(points) <= 10^4
    n = len(points)
    if not (1 <= k <= n <= 10**4):
        return False
    
    # Check each point
    for point in points:
        # Each point must be a list
        if not isinstance(point, list):
            return False
        # Each point must have exactly 2 elements
        if len(point) != 2:
            return False
        # Check each coordinate is an integer (not bool) and within range
        for coord in point:
            if not isinstance(coord, int) or isinstance(coord, bool):
                return False
            if not (-10**4 <= coord <= 10**4):
                return False
    
    return True
