"""Machine-generated input-constraint validator for problem 'word-subsets'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(A, B):
    if not isinstance(A, list) or not isinstance(B, list):
        return False
    if not (1 <= len(A) <= 10**4):
        return False
    if not (1 <= len(B) <= 10**4):
        return False
    for item in A:
        if not isinstance(item, str):
            return False
        if not (1 <= len(item) <= 10):
            return False
    for item in B:
        if not isinstance(item, str):
            return False
        if not (1 <= len(item) <= 10):
            return False
    return True
