"""Machine-generated input-constraint validator for problem 'push-dominoes'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(dominoes):
    if not isinstance(dominoes, str):
        return False
    if not (0 <= len(dominoes) <= 10**5):
        return False
    for char in dominoes:
        if char not in ('L', 'R', '.'):
            return False
    return True
