"""Machine-generated input-constraint validator for problem 'time-needed-to-inform-all-employees'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'valid tree' constraint as it is a semantic guarantee about the structure of the manager array that requires traversal to verify, not a simple bound check.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(n, headID, manager, informTime):
    # Check n
    if not isinstance(n, int) or isinstance(n, bool):
        return False
    if not (1 <= n <= 10**5):
        return False

    # Check headID
    if not isinstance(headID, int) or isinstance(headID, bool):
        return False
    if not (0 <= headID < n):
        return False

    # Check manager
    if not isinstance(manager, list):
        return False
    if len(manager) != n:
        return False
    for x in manager:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (-1 <= x < n):
            return False

    # Check informTime
    if not isinstance(informTime, list):
        return False
    if len(informTime) != n:
        return False
    for x in informTime:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (0 <= x <= 1000):
            return False

    return True
