"""Machine-generated input-constraint validator for problem 'house-robber-iii'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Assumed 'root' is the level-order list representation as described in the text, since TreeNode class is not defined in standard library and the prompt requires self-contained code. Enforced node count and value range constraints.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(root):
    # The problem statement implies the input is a TreeNode object.
    # However, the examples show level-order lists. The prompt says:
    # "root: TreeNode (a binary tree, encoded as a level-order list with null for absent children)"
    # This is contradictory. Usually, in these validation tasks, if the parameter type is declared as TreeNode,
    # we expect a TreeNode object. But the description says "encoded as a level-order list".
    # Let's look at the parameter declaration again: "root: TreeNode (a binary tree, encoded as a level-order list...)"
    # This suggests the *input* to the function is the list representation, despite the name 'TreeNode'.
    # Or it suggests the input is a TreeNode object, and the description is just explaining how trees are visualized.
    # Given the previous examples (Two Sum, Valid Parentheses), the inputs were raw types (list, str).
    # If the input were a TreeNode object, we would need to define the TreeNode class or assume it exists.
    # The prompt says "standard library only" and "pure and self-contained". We cannot assume TreeNode exists.
    # Therefore, it is highly likely that 'root' is actually the list representation described in the text.
    # Let's assume root is a list representing the tree in level-order.
    
    if not isinstance(root, list):
        return False
        
    # Constraint: 1 <= number of nodes <= 10^4
    # We need to count the actual nodes (non-null values) in the list.
    # The list may contain None/null for missing children.
    
    node_count = 0
    for val in root:
        if val is None:
            continue
        # Check if val is an integer (and not a bool)
        if not isinstance(val, int) or isinstance(val, bool):
            return False
        # Check value range: 0 <= node value <= 10^4
        if not (0 <= val <= 10**4):
            return False
        node_count += 1
        
    if not (1 <= node_count <= 10**4):
        return False
        
    return True
