"""Machine-generated input-constraint validator for problem 'minimum-time-difference'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced list length, element type (string), and valid 'HH:MM' format with correct hour/minute ranges. Did not enforce semantic guarantees about the answer.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(timePoints):
    if not isinstance(timePoints, list):
        return False
    if not (2 <= len(timePoints) <= 2 * 10**4):
        return False
    for t in timePoints:
        if not isinstance(t, str):
            return False
        if len(t) != 5 or t[2] != ':':
            return False
        try:
            hh = int(t[:2])
            mm = int(t[3:])
        except ValueError:
            return False
        if not (0 <= hh <= 23):
            return False
        if not (0 <= mm <= 59):
            return False
    return True
