"""Machine-generated input-constraint validator for problem 'plus-one'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length, element range, and no leading zeros (except for single-element [0]).
Do not edit by hand; re-run the generator instead.
"""

def validate_input(digits):
    if not isinstance(digits, list):
        return False
    if not (1 <= len(digits) <= 100):
        return False
    for d in digits:
        if not isinstance(d, int) or isinstance(d, bool):
            return False
        if not (0 <= d <= 9):
            return False
    # Check for leading zeros: if length > 1, the first digit cannot be 0.
    # If length is 1, [0] is valid (represents integer 0), but the problem says
    # "large integer does not contain any leading 0's". Usually [0] is allowed
    # as a representation of 0, but strictly speaking 0 is not a 'leading' zero
    # in the sense of padding. However, standard interpretation of this constraint
    # for this specific LeetCode problem (Plus One) is that the input represents
    # a valid non-negative integer without unnecessary leading zeros.
    # The constraint "digits does not contain any leading 0's" typically implies
    # that if len(digits) > 1, digits[0] != 0. If len(digits) == 1, digits[0] can be 0.
    if len(digits) > 1 and digits[0] == 0:
        return False
    return True
