"""Machine-generated input-constraint validator for problem 'sudoku-solver'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'exactly one solution' and 'valid Sudoku' guarantees as they are semantic properties requiring solving or full validation, not raw input bounds.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(board):
    if not isinstance(board, list):
        return False
    if len(board) != 9:
        return False
    for row in board:
        if not isinstance(row, str):
            return False
        if len(row) != 9:
            return False
        for ch in row:
            if ch not in '123456789.':
                return False
    return True
