"""Machine-generated input-constraint validator for problem 'video-stitching'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(clips, T):
    if not isinstance(clips, list):
        return False
    if not (1 <= len(clips) <= 100):
        return False
    for clip in clips:
        if not isinstance(clip, list):
            return False
        if len(clip) != 2:
            return False
        a, b = clip
        if not (isinstance(a, int) and not isinstance(a, bool)):
            return False
        if not (isinstance(b, int) and not isinstance(b, bool)):
            return False
        if not (0 <= a <= b <= 100):
            return False
    if not (isinstance(T, int) and not isinstance(T, bool)):
        return False
    if not (0 <= T <= 100):
        return False
    return True
