"""Machine-generated input-constraint validator for problem 'maximum-number-of-occurrences-of-a-substring'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s, maxLetters, minSize, maxSize):
    if not isinstance(s, str):
        return False
    if not (1 <= len(s) <= 10**5):
        return False
    if not all('a' <= c <= 'z' for c in s):
        return False
    
    if not isinstance(maxLetters, int) or isinstance(maxLetters, bool):
        return False
    if not (1 <= maxLetters <= 26):
        return False
    
    if not isinstance(minSize, int) or isinstance(minSize, bool):
        return False
    if not isinstance(maxSize, int) or isinstance(maxSize, bool):
        return False
    
    if not (1 <= minSize <= maxSize):
        return False
    if not (maxSize <= min(26, len(s))):
        return False
        
    return True
