"""Machine-generated input-constraint validator for problem 'matchsticks-to-square'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length and element value constraints; skipped semantic guarantee about forming a square as it requires solving the problem.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(matchsticks):
    if not isinstance(matchsticks, list):
        return False
    if not (1 <= len(matchsticks) <= 15):
        return False
    for x in matchsticks:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (1 <= x <= 10**8):
            return False
    return True
