"""Machine-generated input-constraint validator for problem 'maximum-sum-of-two-non-overlapping-subarrays'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(A, L, M):
    if not isinstance(A, list):
        return False
    if not isinstance(L, int) or isinstance(L, bool):
        return False
    if not isinstance(M, int) or isinstance(M, bool):
        return False
    
    if not (1 <= L):
        return False
    if not (1 <= M):
        return False
    
    if not (L + M <= len(A) <= 1000):
        return False
    
    for x in A:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if not (0 <= x <= 1000):
            return False
            
    return True
