"""Machine-generated input-constraint validator for problem 'snapshot-array'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'snap ids passed to get are valid' as it is a semantic guarantee about the sequence of operations, not a static input bound. Skipped index bounds for set/get as they were not explicitly listed in the constraints section.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(length, operations):
    # Check length type and range
    if not isinstance(length, int) or isinstance(length, bool):
        return False
    if not (1 <= length <= 5 * 10**4):
        return False

    # Check operations type and length
    if not isinstance(operations, list):
        return False
    if not (1 <= len(operations) <= 5 * 10**4):
        return False

    # Check each operation
    for op in operations:
        if not isinstance(op, list):
            return False
        
        if len(op) == 3:
            # Could be "set" or "get"
            if not isinstance(op[0], str):
                return False
            if op[0] == "set":
                # ["set", index, value]
                if not isinstance(op[1], int) or isinstance(op[1], bool):
                    return False
                if not isinstance(op[2], int) or isinstance(op[2], bool):
                    return False
                # Constraints on index/value? Statement doesn't specify bounds for value.
                # Index must be valid for the array of 'length', but usually input constraints
                # guarantee valid indices or we just check types. The problem says "Implement an array..."
                # and constraints say "snap ids passed to get are valid". It doesn't explicitly
                # constrain set indices in the constraints section, but logically they must be
                # within bounds. However, rule 3 says "Do NOT invent constraints". 
                # Rule 1 says "Enforce only constraints that are checkable... value ranges".
                # The constraint section only lists length bounds and snap id validity.
                # It does NOT list index bounds for set/get. 
                # However, standard practice for these problems implies indices are valid.
                # But strictly following "Do NOT invent constraints" and "checkable from raw input alone":
                # The statement doesn't explicitly say 0 <= index < length in the constraints block.
                # It just says "Implement an array of length integers". 
                # I will stick to type checking for set/get indices/values unless explicit bounds are given.
                # Wait, looking at "snap ids passed to get are valid". This is a semantic guarantee.
                # I will skip checking if snap_id is valid (i.e. < current snapshot count) as per Rule 2.
                # I will also skip checking if index is within [0, length) as it's not in the explicit constraints list.
                pass
            elif op[0] == "get":
                # ["get", index, snap_id]
                if not isinstance(op[1], int) or isinstance(op[1], bool):
                    return False
                if not isinstance(op[2], int) or isinstance(op[2], bool):
                    return False
            else:
                # Unknown 3-element operation
                return False
        elif len(op) == 1:
            # Could be "snap"
            if not isinstance(op[0], str):
                return False
            if op[0] != "snap":
                return False
        else:
            # Invalid operation length
            return False

    return True
