"""Machine-generated input-constraint validator for problem 'number-of-sub-arrays-of-size-k-and-average-greater-than-or-equal-to-threshold'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(arr, k, threshold):
    if not isinstance(arr, list):
        return False
    if not (1 <= len(arr) <= 10**5):
        return False
    for x in arr:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (1 <= x <= 10**4):
            return False
    if isinstance(k, bool) or not isinstance(k, int):
        return False
    if not (1 <= k <= len(arr)):
        return False
    if isinstance(threshold, bool) or not isinstance(threshold, int):
        return False
    if not (0 <= threshold <= 10**4):
        return False
    return True
