"""Machine-generated input-constraint validator for problem 'valid-anagram'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  The statement provides no explicit constraints on length or character sets, so only type checks are enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s, t):
    if not isinstance(s, str) or isinstance(s, bool):
        return False
    if not isinstance(t, str) or isinstance(t, bool):
        return False
    return True
