"""Machine-generated input-constraint validator for problem 'paint-house'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length of costs, length of each row, integer type (excluding bools), and non-negative values. Skipped semantic constraints about adjacent houses.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(costs):
    if not isinstance(costs, list):
        return False
    if not (1 <= len(costs) <= 100):
        return False
    for row in costs:
        if not isinstance(row, list):
            return False
        if len(row) != 3:
            return False
        for val in row:
            if isinstance(val, bool) or not isinstance(val, int):
                return False
            if val < 0:
                return False
    return True
