"""Machine-generated input-constraint validator for problem 'kth-smallest-element-in-a-sorted-matrix'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped the constraint that rows and columns are sorted in ascending order, as this is a semantic guarantee about the data structure rather than a simple input bound checkable without solving/verifying the problem logic.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(matrix, k):
    if not isinstance(matrix, list):
        return False
    if not isinstance(k, int) or isinstance(k, bool):
        return False
    
    n = len(matrix)
    if not (1 <= n <= 300):
        return False
    
    for row in matrix:
        if not isinstance(row, list):
            return False
        if len(row) != n:
            return False
        for x in row:
            if not isinstance(x, int) or isinstance(x, bool):
                return False
    
    if not (1 <= k <= n * n):
        return False
        
    return True
