"""Machine-generated input-constraint validator for problem 'word-break'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length constraint on s and type constraints on s and wordDict. No explicit bounds were given for wordDict length or word lengths, so none were imposed.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s, wordDict):
    if not isinstance(s, str):
        return False
    if not (1 <= len(s) <= 300):
        return False
    if not isinstance(wordDict, list):
        return False
    for word in wordDict:
        if not isinstance(word, str):
            return False
    return True
