"""Machine-generated input-constraint validator for problem 'in-memory-file-system'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length of operations, valid command names, argument counts per command, string types for paths/content, and absolute path format. Did not enforce semantic validity of paths (e.g., no '..' or empty segments) as these are not explicitly constrained in the problem statement beyond being absolute.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(operations):
    if not isinstance(operations, list):
        return False
    if not (1 <= len(operations) <= 300):
        return False
    
    valid_commands = {"mkdir", "addContentToFile", "readContentFromFile", "ls"}
    
    for op in operations:
        if not isinstance(op, list):
            return False
        if len(op) < 1:
            return False
        
        command = op[0]
        if not isinstance(command, str):
            return False
        if command not in valid_commands:
            return False
        
        if command == "mkdir":
            if len(op) != 2:
                return False
            path = op[1]
            if not isinstance(path, str):
                return False
            if not path.startswith("/"):
                return False
        
        elif command == "addContentToFile":
            if len(op) != 3:
                return False
            path = op[1]
            content = op[2]
            if not isinstance(path, str):
                return False
            if not path.startswith("/"):
                return False
            if not isinstance(content, str):
                return False
        
        elif command == "readContentFromFile":
            if len(op) != 2:
                return False
            path = op[1]
            if not isinstance(path, str):
                return False
            if not path.startswith("/"):
                return False
        
        elif command == "ls":
            if len(op) != 2:
                return False
            path = op[1]
            if not isinstance(path, str):
                return False
            if not path.startswith("/"):
                return False
                
    return True
