"""Machine-generated input-constraint validator for problem 'rank-teams-by-votes'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length bounds, string type, uppercase-only characters, and that all votes are permutations of the same set of letters. Did not enforce semantic ranking rules as those describe the output, not input validity.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(votes):
    if not isinstance(votes, list):
        return False
    if not (1 <= len(votes) <= 1000):
        return False
    if len(votes) == 0:
        return False
    
    # Check that all elements are strings
    for vote in votes:
        if not isinstance(vote, str):
            return False
    
    # Check that all votes are permutations of the same set of characters
    # and contain only uppercase letters
    first_vote = votes[0]
    if len(first_vote) == 0:
        return False
    
    # Verify first vote contains only uppercase letters
    if not first_vote.isalpha() or not first_vote.isupper():
        return False
    
    # Get the set of characters from the first vote
    expected_chars = set(first_vote)
    expected_len = len(first_vote)
    
    for vote in votes:
        # Check length matches
        if len(vote) != expected_len:
            return False
        # Check contains only uppercase letters
        if not vote.isalpha() or not vote.isupper():
            return False
        # Check it's a permutation of the same characters
        if set(vote) != expected_chars:
            return False
        # Check no duplicate characters (it's a permutation)
        if len(set(vote)) != len(vote):
            return False
            
    return True
