"""Machine-generated input-constraint validator for problem 'number-of-ways-to-stay-in-the-same-place-after-some-steps'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(steps, arrLen):
    if not isinstance(steps, int) or isinstance(steps, bool):
        return False
    if not isinstance(arrLen, int) or isinstance(arrLen, bool):
        return False
    if not (1 <= steps <= 500):
        return False
    if not (1 <= arrLen <= 10**6):
        return False
    return True
