"""Machine-generated input-constraint validator for problem 'regex-full-match'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length bounds, character sets, and the structural constraint that every '*' has a valid preceding element. Did not enforce semantic matchability as that requires solving the problem.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(s, p):
    if not isinstance(s, str) or not isinstance(p, str):
        return False
    if not (0 <= len(s) <= 20):
        return False
    if not (0 <= len(p) <= 30):
        return False
    allowed_s = set("abcdefghijklmnopqrstuvwxyz")
    allowed_p = set("abcdefghijklmnopqrstuvwxyz.*")
    if not all(c in allowed_s for c in s):
        return False
    if not all(c in allowed_p for c in p):
        return False
    # Check that every '*' has a valid preceding element
    # A valid preceding element is any character except '*'
    # i.e., '*' cannot be at index 0, and cannot follow another '*'
    for i, char in enumerate(p):
        if char == '*':
            if i == 0:
                return False
            if p[i - 1] == '*':
                return False
    return True
