"""Machine-generated input-constraint validator for problem 'maximum-area-of-a-piece-of-cake-after-horizontal-and-vertical-cuts'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced value ranges for h, w, and cut positions. Enforced that cuts are strictly inside the cake (0 < cut < dimension). Enforced distinctness of cuts as stated. Did not enforce list lengths as no explicit bounds were given other than implied by distinctness and range.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(h, w, horizontalCuts, verticalCuts):
    # Check h and w are integers (not bools) and within range
    if not isinstance(h, int) or isinstance(h, bool):
        return False
    if not isinstance(w, int) or isinstance(w, bool):
        return False
    if not (2 <= h <= 10**9):
        return False
    if not (2 <= w <= 10**9):
        return False

    # Check horizontalCuts is a list
    if not isinstance(horizontalCuts, list):
        return False
    # Check verticalCuts is a list
    if not isinstance(verticalCuts, list):
        return False

    # Validate horizontalCuts elements
    for cut in horizontalCuts:
        if not isinstance(cut, int) or isinstance(cut, bool):
            return False
        if not (0 < cut < h):
            return False

    # Validate verticalCuts elements
    for cut in verticalCuts:
        if not isinstance(cut, int) or isinstance(cut, bool):
            return False
        if not (0 < cut < w):
            return False

    # Check distinctness of horizontalCuts
    if len(horizontalCuts) != len(set(horizontalCuts)):
        return False

    # Check distinctness of verticalCuts
    if len(verticalCuts) != len(set(verticalCuts)):
        return False

    return True
