"""Machine-generated input-constraint validator for problem 'minimum-height-trees'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped 'edges forms a valid tree' connectivity/cycle checks as they are semantic guarantees requiring graph traversal, but enforced len(edges) == n-1 and node label ranges as they are checkable structural constraints.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(n, edges):
    # Check n type and range
    if not isinstance(n, int) or isinstance(n, bool):
        return False
    if not (1 <= n <= 2 * 10**4):
        return False

    # Check edges type
    if not isinstance(edges, list):
        return False

    # Check edges length constraint implied by tree definition (n-1 edges)
    # The problem statement says "len(edges) == n-1" in the description.
    # While "edges forms a valid tree" is a semantic guarantee, the length
    # is a structural constraint checkable from input.
    if len(edges) != n - 1:
        return False

    # Check each edge
    for edge in edges:
        if not isinstance(edge, list):
            return False
        if len(edge) != 2:
            return False
        u, v = edge
        if not isinstance(u, int) or isinstance(u, bool):
            return False
        if not isinstance(v, int) or isinstance(v, bool):
            return False
        # Check node labels are within 0..n-1
        if not (0 <= u < n):
            return False
        if not (0 <= v < n):
            return False

    return True
