"""Machine-generated input-constraint validator for problem 'reverse-linked-list-ii'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(head, m, n):
    if not isinstance(head, list):
        return False
    if not (1 <= len(head) <= 500):
        return False
    for x in head:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
    if not isinstance(m, int) or isinstance(m, bool):
        return False
    if not isinstance(n, int) or isinstance(n, bool):
        return False
    if not (1 <= m <= n <= len(head)):
        return False
    return True
