"""Machine-generated input-constraint validator for problem 'patching-array'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length bounds, element positivity (from 'positive integers'), and n range. Skipped 'sorted' as it is a semantic property of the array order, though technically checkable, it is often treated as a guarantee in such problems; however, strictly speaking, 'sorted' is checkable. I will enforce it to be safe as it is a structural constraint on the input data.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums, n):
    if not isinstance(nums, list):
        return False
    if not (0 <= len(nums) <= 1000):
        return False
    for x in nums:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if x <= 0:
            return False
    if not isinstance(n, int) or isinstance(n, bool):
        return False
    if not (1 <= n <= 2**31 - 1):
        return False
    return True
