"""Machine-generated input-constraint validator for problem 'swap-nodes-in-pairs'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced list type, length bounds, and integer element types (excluding bools). No other constraints were stated.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(head):
    if not isinstance(head, list):
        return False
    if not (0 <= len(head) <= 1000):
        return False
    for x in head:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
    return True
