"""Machine-generated input-constraint validator for problem 'longest-happy-string'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(a, b, c):
    if not isinstance(a, int) or isinstance(a, bool):
        return False
    if not isinstance(b, int) or isinstance(b, bool):
        return False
    if not isinstance(c, int) or isinstance(c, bool):
        return False
    if not (0 <= a <= 100):
        return False
    if not (0 <= b <= 100):
        return False
    if not (0 <= c <= 100):
        return False
    if not (a + b + c > 0):
        return False
    return True
