"""Machine-generated input-constraint validator for problem 'largest-component-common-factor'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length, element range, element type (int, not bool), and distinctness. Distinctness is a checkable input constraint stated in the problem.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(nums):
    if not isinstance(nums, list):
        return False
    if not (1 <= len(nums) <= 2 * 10**4):
        return False
    seen = set()
    for x in nums:
        if isinstance(x, bool) or not isinstance(x, int):
            return False
        if not (1 <= x <= 10**5):
            return False
        if x in seen:
            return False
        seen.add(x)
    return True
