"""Machine-generated input-constraint validator for problem 'two-city-scheduling'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced length bounds, even length, rectangular shape (2 columns), and value ranges. Skipped semantic guarantee about optimal assignment.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(costs):
    if not isinstance(costs, list):
        return False
    n = len(costs)
    if not (2 <= n <= 100):
        return False
    if n % 2 != 0:
        return False
    for row in costs:
        if not isinstance(row, list):
            return False
        if len(row) != 2:
            return False
        for val in row:
            if isinstance(val, bool) or not isinstance(val, int):
                return False
            if not (1 <= val <= 1000):
                return False
    return True
