"""Machine-generated input-constraint validator for problem 'minimum-arrows-burst-balloons'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(points):
    if not isinstance(points, list):
        return False
    if not (1 <= len(points) <= 10**5):
        return False
    for point in points:
        if not isinstance(point, list):
            return False
        if len(point) != 2:
            return False
        start, end = point
        if not isinstance(start, int) or isinstance(start, bool):
            return False
        if not isinstance(end, int) or isinstance(end, bool):
            return False
        if not (start <= end):
            return False
    return True
