"""Machine-generated input-constraint validator for problem 'web-crawler-same-host'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Enforced URL count bounds, string types, and http:// prefix. Did not enforce semantic reachability or hostname matching as those are solution properties.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(startUrl, graph):
    # Check startUrl type
    if not isinstance(startUrl, str):
        return False
    
    # Check startUrl format: must start with http://
    if not startUrl.startswith("http://"):
        return False
    
    # Check graph type
    if not isinstance(graph, dict):
        return False
    
    # Check number of URLs constraint: 1 <= number of URLs <= 10^4
    # The "number of URLs" refers to the keys in the graph
    num_urls = len(graph)
    if not (1 <= num_urls <= 10**4):
        return False
    
    # Validate each key and value in the graph
    for url, neighbors in graph.items():
        # Key must be a string
        if not isinstance(url, str):
            return False
        # Key must start with http://
        if not url.startswith("http://"):
            return False
        
        # Value must be a list
        if not isinstance(neighbors, list):
            return False
        
        # Each neighbor must be a string starting with http://
        for neighbor in neighbors:
            if not isinstance(neighbor, str):
                return False
            if not neighbor.startswith("http://"):
                return False
    
    return True
