"""Machine-generated input-constraint validator for problem 'prison-cells-after-n-days'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(cells, N):
    if not isinstance(cells, list):
        return False
    if len(cells) != 8:
        return False
    for x in cells:
        if not isinstance(x, int) or isinstance(x, bool):
            return False
        if x not in (0, 1):
            return False
    if not isinstance(N, int) or isinstance(N, bool):
        return False
    if not (1 <= N <= 10**9):
        return False
    return True
