"""Machine-generated input-constraint validator for problem 'integer-to-roman'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  All stated constraints are checkable and enforced.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(num):
    if not isinstance(num, int) or isinstance(num, bool):
        return False
    if not (1 <= num <= 3999):
        return False
    return True
