"""Machine-generated input-constraint validator for problem 'notification-dedup'.

Generated by scripts/generate_constraint_validators.py (model: local-model).
`validate_input(...)` returns True iff its arguments satisfy the input constraints
stated in the problem. Constraints deliberately NOT enforced:
  Skipped enforcing that events are in time order, as this is treated as a semantic guarantee/promise about the input structure rather than a strict value-bound constraint to be validated.
Do not edit by hand; re-run the generator instead.
"""

def validate_input(events, window):
    # Check window type and range
    if not isinstance(window, int) or isinstance(window, bool):
        return False
    if window < 0:
        return False

    # Check events type and length
    if not isinstance(events, list):
        return False
    if not (0 <= len(events) <= 2 * 10**5):
        return False

    # Check each event
    for event in events:
        if not isinstance(event, list):
            return False
        if len(event) != 2:
            return False
        key, time = event
        # Key must be a string
        if not isinstance(key, str):
            return False
        # Time must be an integer (not bool)
        if not isinstance(time, int) or isinstance(time, bool):
            return False
        # The problem doesn't explicitly bound time values, but typically times are non-negative.
        # However, rule 3 says "Do NOT invent constraints". The statement only says "time order".
        # It does not explicitly state time >= 0. But usually timestamps are non-negative.
        # Let's look closely: "gap to the last delivered time... strictly greater than window".
        # If times can be negative, the logic still holds. I will not enforce time >= 0 as it's not explicitly stated.
        # I will not enforce time ordering as that's a semantic guarantee/property of the input generation,
        # but wait: "events is a list of [key, time] notifications in time order". 
        # Is "in time order" a constraint on the input values? Yes, it implies the list is sorted by time.
        # However, Rule 2 says "Do NOT enforce semantic guarantees... that describe the answer". 
        # Is sortedness a semantic guarantee or an input constraint? 
        # Usually, "given a sorted array" is an input constraint. "Given an array, find the sorted version" is not.
        # Here, the input is *described* as being in time order. This is a constraint on the input data.
        # But checking if it's sorted requires O(N) logic. Is it "checkable from raw input alone"? Yes.
        # Is it a "semantic guarantee that would require solving the problem"? No, it's a precondition.
        # However, often in these problems, the "sorted" property is a guarantee provided by the problem setter
        # to simplify the solution, not a validation target for the user. 
        # Let's re-read Rule 2: "Skip these; they are promises, not checkable input bounds."
        # "Exactly one valid answer exists" is skipped. "The array is guaranteed to have a peak" is skipped.
        # "Events... in time order" is similar to "array is sorted". It's a promise about the input structure.
        # If I enforce it, I might reject valid inputs if the problem setter made a mistake or if the definition of "time order" is ambiguous (e.g. stable sort?).
        # Given the ambiguity and the instruction to skip guarantees/promises, I will skip enforcing the sorted order.
        # I will only enforce the structural and type constraints.
        pass

    return True
